/**
 * agent-router.ts
 * Every client-facing reply is generated by Qwen. There is no canned-response
 * library, no keyword matcher and no learning cache — the only non-LLM path is
 * the deterministic roadmap builder, which exists because the Dashboard needs a
 * fixed, machine-readable step structure rather than prose.
 *
 *   workflow trigger  → protocol.buildWorkflow()          (no model call)
 *   everything else   → RAG grounding → streamText(qwen)  (tool: start_roadmap)
 */

import { z } from 'zod';
import { tool, streamText, stepCountIs, type ModelMessage } from 'ai';
import { detectDegeneration } from './response-quality';
import { eq } from 'drizzle-orm';
import { db } from './db';
import { chatSessions } from './schema';
import { buildWorkflow } from './protocol';
import { localizeWorkflow, needsLocalization, fallbackLang } from './workflow-localize';
import { qwen, hasQwenKey, QWEN_PROVIDER_OPTIONS } from './qwen';
import { consumeCredit, getCreditBalance, refundCredit } from './credits';
import { saveIntake, INTAKE_FIELDS, readIntake } from './visa-intake';
import { saveUniversityIntake, submitUniversityApplication, readUniversityIntake, startUniversityService, UNIVERSITY_FIELDS, missingUniversityChoice, hasChosenUniversity } from './university-intake';
import { paymentDetailsFor, formatIban, formatAmount } from './university-payment-details';
import {
  TURKISH_UNIVERSITIES,
  findUniversity,
  searchUniversities,
  universitiesInCity,
  universityCities,
} from './turkish-universities';
import { getChecklistStatus } from './checklist-status';
import { saveCriminalIntake, submitCriminalCase, CRIMINAL_FIELDS } from './criminal-intake';
import { saveIkametIntake, readIkametIntake, IKAMET_FIELDS } from './ikamet-intake';
import { saveInsuranceIntake, readInsuranceIntake, INSURANCE_FIELDS } from './insurance-intake';
import { saveBusinessIntake, readBusinessIntake, BUSINESS_FIELDS } from './business-intake';
import { checklistView, findChecklist, pickLang } from './document-checklists';
import { generateFormPdf, storeGeneratedForm, type FormKind } from './form-docs';
import {
  getSupportAccountSummary,
  restoreMissingCreditsForUser,
  resetUserTokenQuota,
} from './support-tools';
import {
  buildSystemPrompt,
  normalizeAgent,
  normalizeLang,
  ROADMAP_TOOL_DESCRIPTION,
  VISA_INTAKE_TOOL_DESCRIPTION,
  UNIVERSITY_INTAKE_TOOL_DESCRIPTION,
  CRIMINAL_INTAKE_TOOL_DESCRIPTION,
  IKAMET_INTAKE_TOOL_DESCRIPTION,
  INSURANCE_INTAKE_TOOL_DESCRIPTION,
  BUSINESS_INTAKE_TOOL_DESCRIPTION,
  DOCUMENT_CHECKLIST_TOOL_DESCRIPTION,
  type AgentType,
  type Lang,
} from './prompts';

/**
 * Snapshot of a visa application after an intake turn, sent to the client so
 * the chat can show a live checklist. Deliberately carries no values — only
 * which fields are answered — so passport data never rides the SSE stream.
 */
export type VisaIntakeState = {
  collected: string[];
  missing: string[];
  documentAttached: boolean;
  status: string;
};

/**
 * Snapshot of a university application after an intake turn. Same
 * values-never-leave-the-server rule as the visa state.
 */
export type UniversityIntakeState = {
  collected: string[];
  missing: string[];
  status: string;
};

/**
 * Snapshot of an İkamet / insurance / business application after an intake
 * turn. Same labels-only contract as the visa and university states.
 */
export type FieldIntakeState = {
  collected: string[];
  missing: string[];
  status: string;
};

/**
 * A generated document delivered to the chat. `documentId` is served by
 * GET /api/documents/[id] (owner-checked); the route turns it into a
 * downloadable file chip on the assistant message.
 */
export type AttachmentSnapshot = {
  filename: string;
  documentId: number;
};

/** A requested document checklist, resolved to the conversation language. */
export type DocumentChecklistSnapshot = {
  service: string;
  agent: 'student' | 'permit';
  items: Array<{ title: string; whereToGet: string }>;
};

/** Thrown when DASHSCOPE_API_KEY is missing — the route turns this into a 503. */
export class MissingModelKeyError extends Error {
  constructor() {
    super('Qwen is not configured on this server (DASHSCOPE_API_KEY is missing).');
    this.name = 'MissingModelKeyError';
  }
}

export interface AgentInput {
  query: string;
  language: string;
  assistantType: string;
  sessionId?: string;
  /** Recent conversation history, oldest first. */
  messages?: Array<{ role: string; content: string }>;
  userName?: string;
  isStepQuery?: boolean;
  /** Reply will be spoken aloud — forces plain text and a much shorter answer. */
  isVoice?: boolean;
  /** Signed-in user id. Guests cannot hold credits, so they cannot build roadmaps. */
  userId?: number;
  /** The user has seen the "this uses 1 service" prompt and agreed. */
  creditsConfirmed?: boolean;
}

export type AgentResult =
  | {
      kind: 'workflow';
      /** Complete text — no model involved, so there is nothing to stream. */
      content: string;
      dashboardState: Record<string, unknown>;
      /** Credit spent to produce this, so the route can refund on failure. */
      consumedCreditId?: number;
    }
  | {
      kind: 'stream';
      textStream: AsyncIterable<string>;
      /** Knowledge-base article titles used for grounding, for the citation line. */
      sources: string[];
      /** Populated if the model called start_roadmap. Read after the stream ends. */
      getDashboardState: () => Record<string, unknown> | null;
      /** Visa intake progress, when the intake tool ran this turn. */
      getVisaIntake: () => VisaIntakeState | null;
      /** University intake progress, when the university tool ran this turn. */
      getUniversityIntake: () => UniversityIntakeState | null;
      /** İkamet intake progress, when the ikamet tool ran this turn. */
      getIkametIntake: () => FieldIntakeState | null;
      /** Insurance intake progress, when the insurance tool ran this turn. */
      getInsuranceIntake: () => FieldIntakeState | null;
      /** Business intake progress, when the business tool ran this turn. */
      getBusinessIntake: () => FieldIntakeState | null;
      /**
       * Document checklist requested this turn — items already resolved to the
       * conversation language, ready for the client card.
       */
      getDocumentChecklist: () => DocumentChecklistSnapshot | null;
      /** Generated form delivered this turn, when deliver_form ran. */
      getAttachment: () => AttachmentSnapshot | null;
      getConsumedCreditId: () => number | null;
      /** Set when the model wanted a roadmap but the user has not confirmed yet. */
      getPendingConfirm: () => PendingConfirm | null;
    }
  | {
      /** A roadmap was requested but costs a credit — ask before spending. */
      kind: 'confirm_required';
      pending: PendingConfirm;
    };

export interface PendingConfirm {
  service: string;
  location: string;
  creditsAvailable: number;
  nextExpiry: string | null;
  /** Guest — must sign in before they can hold or spend credits. */
  requiresAuth: boolean;
  /**
   * The paperwork this roadmap will tell them to gather. Shown before the
   * credit is spent, so nobody pays to discover they need documents they
   * cannot get. Derived from the same deterministic generator that builds the
   * roadmap itself, so the preview cannot drift from the real thing.
   */
  documents: string[];
}

/**
 * List the documents a roadmap would require, without building or storing one.
 * buildWorkflow() is pure and makes no API call, so this costs nothing.
 */
function previewDocuments(service: string, location: string, agent: AgentType, lang: Lang): string[] {
  try {
    const built = buildWorkflow(service, agent, lang, location);
    const docs = built?.combined_result?.documents ?? [];
    return docs.slice(0, 8);
  } catch {
    return [];
  }
}

const MAX_HISTORY_TURNS = 12;

// ---------------------------------------------------------------------------
// Deterministic roadmap path
// ---------------------------------------------------------------------------

/** Matches the chip flow's synthesized query, e.g. "Cafe & Restaurant - New Application in Kadıköy". */
const WORKFLOW_PATTERN =
  /^(.+?) - (New|Renewal|Extension|Follow-up|Transfer|Re-registration|Get New|Find New|Set Up New|Form New|Review New|Hire|File New|New Transaction|New Matter)/i;

function parseWorkflowQuery(query: string): { service: string; location: string } | null {
  const m = query.match(WORKFLOW_PATTERN);
  if (!m) return null;
  const parts = query.split(' in ');
  return {
    service: m[1].trim(),
    location: parts.length > 1 ? parts[parts.length - 1].trim() : 'Istanbul',
  };
}

function roadmapSummary(
  service: string,
  location: string,
  state: NonNullable<ReturnType<typeof buildWorkflow>>,
  lang: Lang,
): string {
  const steps = state.execution_plan.steps.length;
  const days = state.combined_result.timeline_days;
  const permits = state.combined_result.permits.length;
  const body = state.combined_result.summary;

  const byLang: Record<Lang, string> = {
    en: `✅ **Your ${service} roadmap in ${location} is ready!**\n\n${body}\n\n📋 **${steps} steps** · ⏱️ **~${days} days** · 📁 **${permits} permits required**\n\n⬇️ Opening your Dashboard...`,
    tr: `✅ **${location} için ${service} yol haritanız hazır!**\n\n${body}\n\n📋 **${steps} adım** · ⏱️ **~${days} gün** · 📁 **${permits} izin gerekli**\n\n⬇️ Gösterge Paneliniz açılıyor...`,
    ar: `✅ **خارطة طريقك لـ ${service} في ${location} جاهزة!**\n\n${body}\n\n📋 **${steps} خطوة** · ⏱️ **~${days} يوماً** · 📁 **${permits} تصاريح مطلوبة**\n\n⬇️ يتم فتح لوحة القيادة...`,
    tk: `✅ **${location} üçin ${service} ýol kartaňyz taýyn!**\n\n${body}\n\n📋 **${steps} ädim** · ⏱️ **~${days} gün** · 📁 **${permits} rugsatnama gerek**\n\n⬇️ Dolandyryş Paneliňiz açylýar...`,
    az: `✅ **${location} üçün ${service} yol xəritəniz hazırdır!**\n\n${body}\n\n📋 **${steps} addım** · ⏱️ **~${days} gün** · 📁 **${permits} icazə tələb olunur**\n\n⬇️ İdarə Paneliniz açılır...`,
    uz: `✅ **${location} bo'yicha ${service} yo'l xaritangiz tayyor!**\n\n${body}\n\n📋 **${steps} qadam** · ⏱️ **~${days} kun** · 📁 **${permits} ruxsatnoma kerak**\n\n⬇️ Boshqaruv panelingiz ochilmoqda...`,
    kk: `✅ **${location} бойынша ${service} жол картаңыз дайын!**\n\n${body}\n\n📋 **${steps} қадам** · ⏱️ **~${days} күн** · 📁 **${permits} рұқсат қажет**\n\n⬇️ Басқару панеліңіз ашылуда...`,
    fa: `✅ **نقشه راه ${service} شما در ${location} آماده است!**\n\n${body}\n\n📋 **${steps} مرحله** · ⏱️ **~${days} روز** · 📁 **${permits} مجوز لازم است**\n\n⬇️ در حال باز کردن داشبورد شما...`,
    ru: `✅ **Ваш план действий для «${service}» в районе ${location} готов!**\n\n${body}\n\n📋 **Шагов: ${steps}** · ⏱️ **~${days} дн.** · 📁 **Нужно разрешений: ${permits}**\n\n⬇️ Открываю панель управления...`,
  };
  return byLang[lang] ?? byLang.en;
}

async function buildRoadmap(
  service: string,
  location: string,
  agent: AgentType,
  lang: Lang,
  sessionId?: string,
): Promise<{ content: string; dashboardState: Record<string, unknown> } | null> {
  let state = buildWorkflow(service, agent, lang, location);
  if (!state) return null;

  // az/uz/kk/fa/ru have no static step texts in protocol.ts — translate the
  // deterministic structure natively. On model failure, rebuild with the
  // closest base language so the roadmap is still readable.
  if (needsLocalization(lang)) {
    const localized = await localizeWorkflow(state, lang);
    if (localized) {
      state = localized;
    } else {
      const base = buildWorkflow(service, agent, fallbackLang(lang), location);
      if (base) state = base;
    }
  }

  if (sessionId && !sessionId.startsWith('guest-')) {
    db.update(chatSessions)
      .set({ dashboard_state: JSON.stringify(state), updated_at: new Date() })
      .where(eq(chatSessions.id, sessionId))
      .catch(() => {
        /* session may not exist yet for guests — the client keeps a local copy */
      });
  }

  return {
    content: roadmapSummary(service, location, state, lang),
    dashboardState: state as unknown as Record<string, unknown>,
  };
}

// ---------------------------------------------------------------------------
// Retrieval grounding
// ---------------------------------------------------------------------------

async function retrieveGrounding(
  query: string,
  agent: AgentType,
  lang: Lang,
): Promise<{ context: string; sources: string[] }> {
  try {
    const { retrieveChunks } = await import('./rag');
    const chunks = await retrieveChunks(query, agent, lang, 3);
    if (!chunks.length) return { context: '', sources: [] };
    return {
      context: chunks.map((c, i) => `[Source ${i + 1}: ${c.title}]\n${c.chunkText}`).join('\n\n'),
      sources: [...new Set(chunks.map(c => c.title))],
    };
  } catch {
    return { context: '', sources: [] };
  }
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export async function streamAgentReply(input: AgentInput): Promise<AgentResult> {
  const agent = normalizeAgent(input.assistantType);
  const lang = normalizeLang(input.language);
  const isStepQuery = input.isStepQuery === true;

  // ── Deterministic roadmap: the service chips post a structured query ──────
  // A roadmap is the paid deliverable, so this path is gated on a credit. The
  // model-driven start_roadmap tool below is gated identically — leaving either
  // door open would make the paywall optional.
  if (!isStepQuery) {
    const parsed = parseWorkflowQuery(input.query);
    if (parsed) {
      const gate = await checkRoadmapCredit(input, parsed.service, parsed.location, agent, lang);
      if (gate.kind === 'blocked') return { kind: 'confirm_required', pending: gate.pending };

      const built = await buildRoadmap(parsed.service, parsed.location, agent, lang, input.sessionId);
      if (built) return { kind: 'workflow', ...built, consumedCreditId: gate.creditId ?? undefined };

      // Nothing was produced — do not keep the user's money.
      if (gate.creditId) await refundCredit(gate.creditId, input.userId!, 'unknown service');
    }
  }

  if (!hasQwenKey()) throw new MissingModelKeyError();

  const { context, sources } = await retrieveGrounding(input.query, agent, lang);

  // ── start_roadmap: the free-text route into the Dashboard ─────────────────
  // Replaces the old hand-written state machine — the model decides when both
  // the service and the district are known, instead of a typo-tolerance table.
  let dashboardState: Record<string, unknown> | null = null;
  let visaIntake: VisaIntakeState | null = null;
  let universityIntake: UniversityIntakeState | null = null;
  let ikametIntake: FieldIntakeState | null = null;
  let insuranceIntake: FieldIntakeState | null = null;
  let businessIntake: FieldIntakeState | null = null;
  let documentChecklist: DocumentChecklistSnapshot | null = null;
  let attachment: AttachmentSnapshot | null = null;
  let roadmapText: string | null = null;
  let consumedCreditId: number | null = null;
  let pendingConfirm: PendingConfirm | null = null;

  /**
   * Whether the university checklist may be shown — the student has named a
   * university AND the service credit has been spent. Seeded below only when
   * the turn actually concerns university registration (every other turn skips
   * the query) and flipped when start_university_service succeeds, so the
   * checklist backstop can stay synchronous.
   */
  let universityChecklistUnlocked = false;

  /**
   * Visa appointment intake. Unlike start_roadmap this produces no deliverable
   * and costs no credit — it is just structured note-taking during the
   * conversation. The credit is charged by the booking service itself, once an
   * operator actually claims the finished application.
   *
   * Every field is optional so the model can save whatever it has right now;
   * blanks are ignored on merge, so a partial call can never erase an earlier
   * answer.
   */
  const collectVisaApplication = tool({
    description: VISA_INTAKE_TOOL_DESCRIPTION,
    inputSchema: z.object(
      Object.fromEntries(
        INTAKE_FIELDS.map((f) => [f.key, z.string().optional().describe(f.label)]),
      ) as Record<string, z.ZodOptional<z.ZodString>>,
    ),
    execute: async (answers: Record<string, string | undefined>) => {
      // Intake is tied to a stored session — a guest session vanishes, and the
      // operator's booking watcher would have nothing to claim.
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can save their visa application details.',
        };
      }

      const saved = await saveIntake({
        sessionId: input.sessionId,
        userId: input.userId ?? null,
        answers,
      });

      visaIntake = {
        collected: INTAKE_FIELDS.filter((f) => saved.data[f.key]).map((f) => f.short),
        missing: saved.missing.map((f) => f.short),
        documentAttached: saved.documentPresent,
        status: saved.status,
      };

      return {
        ok: true as const,
        saved: Object.keys(answers).filter((k) => answers[k]),
        stillNeeded: saved.missing.map((f) => f.label),
        documentAttached: saved.documentPresent,
        message: saved.missing.length
          ? 'Ask only for the details in stillNeeded, a few at a time.'
          : saved.documentPresent
            ? 'All details are collected and the document is attached. Tell the user their application is complete and will be submitted for them.'
            : 'All details are collected. Ask the user to attach their acceptance letter with the + button.',
      };
    },
  });

  /**
   * University placement intake. Collecting answers is free; the paid step is
   * the submission itself — one service credit, charged only after the user
   * explicitly confirms, the same way start_roadmap is gated. The save half
   * mirrors the visa intake exactly: every field is optional, blanks are
   * ignored on merge, and a partial call can never erase an earlier answer.
   */
  const collectUniversityApplication = tool({
    description: UNIVERSITY_INTAKE_TOOL_DESCRIPTION,
    inputSchema: z.object(
      Object.fromEntries(
        UNIVERSITY_FIELDS.map((f) => [f.key, z.string().optional().describe(f.label)]),
      ) as Record<string, z.ZodOptional<z.ZodString>>,
    ),
    execute: async (answers: Record<string, string | undefined>) => {
      // Intake is tied to a stored session — a guest session vanishes, and
      // there would be no application for the placement team to pick up.
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can save their university application details.',
        };
      }

      const saved = await saveUniversityIntake({
        sessionId: input.sessionId,
        userId: input.userId ?? null,
        answers,
      });

      universityIntake = {
        collected: UNIVERSITY_FIELDS.filter((f) => saved.data[f.key]).map((f) => f.short),
        missing: saved.missing.map((f) => f.short),
        status: saved.status,
      };

      const servicePaid = Boolean(saved.application.credit_id);
      const justChose =
        !universityChecklistUnlocked && hasChosenUniversity(saved.data) && !servicePaid;
      if (hasChosenUniversity(saved.data) && servicePaid) universityChecklistUnlocked = true;

      if (saved.missing.length) {
        return {
          ok: true as const,
          saved: Object.keys(answers).filter((k) => answers[k]),
          stillNeeded: saved.missing.map((f) => f.label),
          message: justChose
            ? `Saved ${saved.data.chosenUniversity} as their university. Now call start_university_service — starting the application is the paid step, and it is what unlocks the document checklist and the university's payment details. Do not list documents before it succeeds.`
            : 'Ask only for the details in stillNeeded, a few at a time.',
        };
      }

      // Every field is collected — the remaining step is the paid submission.
      const submitted = await submitUniversityApplication({
        sessionId: input.sessionId,
        userId: input.userId ?? null,
        confirmed: input.creditsConfirmed === true,
      });

      const pendingFor = (
        creditsAvailable: number,
        nextExpiry: string | null,
        requiresAuth: boolean,
      ): PendingConfirm => ({
        service: 'University Application',
        location: 'Türkiye',
        creditsAvailable,
        nextExpiry,
        requiresAuth,
        documents: [],
      });

      switch (submitted.kind) {
        case 'missing_application':
        case 'incomplete':
          return {
            ok: false as const,
            message: 'The application could not be saved. Ask the user to try again.',
          };
        case 'auth_required':
          pendingConfirm = pendingFor(0, null, true);
          return {
            ok: false as const,
            reason: 'confirmation_required',
            message:
              'Tell the user they need to sign in before their university application can be submitted.',
          };
        case 'confirmation_required':
          pendingConfirm = pendingFor(
            submitted.available,
            submitted.nextExpiry?.toISOString() ?? null,
            false,
          );
          return {
            ok: false as const,
            reason: 'confirmation_required',
            message:
              'All details are collected. Tell the user in one short sentence that submitting their university application to our placement team uses one service credit, and wait for them to confirm.',
          };
        case 'no_credit':
          pendingConfirm = pendingFor(0, submitted.nextExpiry?.toISOString() ?? null, false);
          return {
            ok: false as const,
            reason: 'confirmation_required',
            message:
              'All details are collected, but the user has no service credit. Tell them submitting the application uses one credit and they can buy one from the pricing page.',
          };
        case 'already_submitted':
          return {
            ok: true as const,
            message:
              'This application is already submitted and was already charged. Tell the user their application is with the placement team.',
          };
        case 'submitted':
          universityIntake = { ...universityIntake, status: 'submitted' };
          return {
            ok: true as const,
            message:
              'The application is submitted and one credit was charged. Tell the user the placement team will review their profile and contact them with university options.',
          };
        // The credit was already spent when the service started, so finishing
        // the profile hands it over at no extra cost.
        case 'handed_over':
          universityIntake = { ...universityIntake, status: 'submitted' };
          return {
            ok: true as const,
            message:
              'Their profile is complete and has gone to the placement team — no further charge, the credit was used when the service started. ' +
              'Tell them the team will review it and contact them, and remind them of any documents still to upload.',
          };
      }
    },
  });

  /**
   * Criminal defense intake. Free and confirmation-free — a detention or a
   * charge is an emergency, so completion forwards the case to the human
   * lawyer immediately instead of gating it behind a credit.
   */
  const collectCriminalCase = tool({
    description: CRIMINAL_INTAKE_TOOL_DESCRIPTION,
    inputSchema: z.object(
      Object.fromEntries(
        CRIMINAL_FIELDS.map((f) => [f.key, z.string().optional().describe(f.label)]),
      ) as Record<string, z.ZodOptional<z.ZodString>>,
    ),
    execute: async (answers: Record<string, string | undefined>) => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can record their case for the lawyer.',
        };
      }

      const saved = await saveCriminalIntake({
        sessionId: input.sessionId,
        userId: input.userId ?? null,
        answers,
      });

      if (saved.missing.length) {
        return {
          ok: true as const,
          saved: Object.keys(answers).filter((k) => answers[k]),
          stillNeeded: saved.missing.map((f) => f.label),
          message: 'Ask only for the details in stillNeeded, a few at a time.',
        };
      }

      const submitted = await submitCriminalCase({
        sessionId: input.sessionId,
        userId: input.userId ?? null,
      });

      switch (submitted.kind) {
        case 'missing_application':
        case 'incomplete':
          return {
            ok: false as const,
            message: 'The case could not be saved. Ask the user to try again.',
          };
        case 'auth_required':
          return {
            ok: false as const,
            message: 'Tell the user they need to sign in before their case can be sent to the lawyer.',
          };
        case 'already_forwarded':
          return {
            ok: true as const,
            message:
              'This case was already sent to our lawyer. Tell the user the lawyer\'s office will contact them on the phone number they gave.',
          };
        case 'forwarded':
          return {
            ok: true as const,
            message:
              'The case is complete and has been sent to our lawyer Emre Aslan. Tell the user the lawyer\'s office will contact them on the phone number they gave, and that they must not make any statement to the police without a lawyer present.',
          };
      }
    },
  });

  /**
   * İkamet (residence permit) intake. Free note-taking with the same
   * merge-blank contract as the visa intake; completion means the filled
   * application document can be generated for the user.
   */
  const collectIkametApplication = tool({
    description: IKAMET_INTAKE_TOOL_DESCRIPTION,
    inputSchema: z.object(
      Object.fromEntries(
        IKAMET_FIELDS.map((f) => [f.key, z.string().optional().describe(f.label)]),
      ) as Record<string, z.ZodOptional<z.ZodString>>,
    ),
    execute: async (answers: Record<string, string | undefined>) => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can save their İkamet application details.',
        };
      }

      try {
        const saved = await saveIkametIntake({
          sessionId: input.sessionId,
          userId: input.userId ?? null,
          answers,
        });

        ikametIntake = {
          collected: IKAMET_FIELDS.filter((f) => saved.data[f.key]).map((f) => f.short),
          missing: saved.missing.map((f) => f.short),
          status: saved.status,
        };

        return {
          ok: true as const,
          saved: Object.keys(answers).filter((k) => answers[k]),
          stillNeeded: saved.missing.map((f) => f.label),
          message: saved.missing.length
            ? 'Ask only for the details in stillNeeded, a few at a time.'
            : 'All details are collected. Tell the user their data is saved and they can ask for their filled İkamet application document.',
        };
      } catch {
        return { ok: false as const, message: 'Ask the user to try again in a moment.' };
      }
    },
  });

  /**
   * SGK student health insurance intake — same free, merge-blank contract.
   */
  const collectInsuranceApplication = tool({
    description: INSURANCE_INTAKE_TOOL_DESCRIPTION,
    inputSchema: z.object(
      Object.fromEntries(
        INSURANCE_FIELDS.map((f) => [f.key, z.string().optional().describe(f.label)]),
      ) as Record<string, z.ZodOptional<z.ZodString>>,
    ),
    execute: async (answers: Record<string, string | undefined>) => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can save their insurance application details.',
        };
      }

      try {
        const saved = await saveInsuranceIntake({
          sessionId: input.sessionId,
          userId: input.userId ?? null,
          answers,
        });

        insuranceIntake = {
          collected: INSURANCE_FIELDS.filter((f) => saved.data[f.key]).map((f) => f.short),
          missing: saved.missing.map((f) => f.short),
          status: saved.status,
        };

        return {
          ok: true as const,
          saved: Object.keys(answers).filter((k) => answers[k]),
          stillNeeded: saved.missing.map((f) => f.label),
          message: saved.missing.length
            ? 'Ask only for the details in stillNeeded, a few at a time.'
            : 'All details are collected. Tell the user their data is saved and they can ask for their filled insurance application document.',
        };
      } catch {
        return { ok: false as const, message: 'Ask the user to try again in a moment.' };
      }
    },
  });

  /**
   * Business permit intake — same free, merge-blank contract.
   */
  const collectBusinessApplication = tool({
    description: BUSINESS_INTAKE_TOOL_DESCRIPTION,
    inputSchema: z.object(
      Object.fromEntries(
        BUSINESS_FIELDS.map((f) => [f.key, z.string().optional().describe(f.label)]),
      ) as Record<string, z.ZodOptional<z.ZodString>>,
    ),
    execute: async (answers: Record<string, string | undefined>) => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can save their business application details.',
        };
      }

      try {
        const saved = await saveBusinessIntake({
          sessionId: input.sessionId,
          userId: input.userId ?? null,
          answers,
        });

        businessIntake = {
          collected: BUSINESS_FIELDS.filter((f) => saved.data[f.key]).map((f) => f.short),
          missing: saved.missing.map((f) => f.short),
          status: saved.status,
        };

        return {
          ok: true as const,
          saved: Object.keys(answers).filter((k) => answers[k]),
          stillNeeded: saved.missing.map((f) => f.label),
          message: saved.missing.length
            ? 'Ask only for the details in stillNeeded, a few at a time.'
            : 'All details are collected. Tell the user their data is saved and they can ask for their filled business permit application document.',
        };
      } catch {
        return { ok: false as const, message: 'Ask the user to try again in a moment.' };
      }
    },
  });

  /**
   * Document checklist — the free "what do I need to upload" answer. The
   * deterministic catalog is resolved to the conversation language here, so
   * the model (and the client card) get near-native strings; the model still
   * renders them natively in its reply.
   */
  /**
   * Returns a tool result when the university checklist must be withheld, or
   * null when the student has chosen a university and it can be shown.
   *
   * Guests have no application row to read, so they are gated on the choice
   * being present in the conversation rather than in the database — the model
   * is told to ask, and only a signed-in student can upload anything anyway.
   */
  const universityChoiceGate = async () => {
    if (!input.sessionId || input.sessionId.startsWith('guest-')) {
      return {
        ok: false as const,
        needsUniversityChoice: true,
        cities: universityCities().slice(0, 6).map((c) => `${c.city} (${c.count})`),
        message:
          'Do NOT list documents yet. First ask which Turkish university they want to apply to. ' +
          'If they do not know, call suggest_universities to offer real options. ' +
          'Once they name one, call collect_university_application to save it, then call this tool again.',
      };
    }

    const state = await readUniversityIntake(input.sessionId);
    const data = state?.data ?? {};

    if (!hasChosenUniversity(data)) {
      const stillNeeded = missingUniversityChoice(data).map((f) => f.label);
      return {
        ok: false as const,
        needsUniversityChoice: true,
        stillNeeded,
        message:
          'Do NOT list or show documents yet — the student has not chosen a university. ' +
          'Ask for the details in stillNeeded, warmly and a few at a time. ' +
          'If they do not know which university, call suggest_universities and present the options. ' +
          'Save each answer with collect_university_application, and once chosenUniversity is saved, call this tool again.',
      };
    }

    // University chosen but the service is not paid for. The checklist, the
    // uploads and the university's payment details are the paid product, so
    // they wait behind the credit rather than being given away first.
    if (!state?.application.credit_id) {
      return {
        ok: false as const,
        needsServicePayment: true,
        university: String(data.chosenUniversity).trim(),
        message:
          'Do NOT list the documents yet. The student has chosen a university, so the next step is starting the service. ' +
          'Call start_university_service now — it reports the cost and asks them to confirm. ' +
          'Once it reports the service is active, call this tool again to show the checklist.',
      };
    }

    return null;
  };

  /**
   * Real universities the student can actually apply to, filtered by what they
   * told us. Suggestions are drawn from the vetted list in
   * turkish-universities.ts — the model must not invent institutions, tuition
   * figures or entry requirements, none of which are in that data.
   */
  const suggestUniversities = tool({
    description:
      'Suggest Turkish private (foundation) universities for a student who has not chosen one yet. ' +
      'Call this as soon as a student wants university registration but has not named a university, or asks for recommendations. ' +
      'Pass whatever they have told you — city, field of study, GPA. ' +
      'Present the returned universities as a short numbered list with their city and website, then ask which one they want. ' +
      'NEVER invent a university, a tuition price, or a GPA requirement: the tool returns everything we actually know. ' +
      'If they ask about cost or entry grades, say plainly that you will confirm those with the university and move on.',
    inputSchema: z.object({
      city: z.string().optional().describe('Preferred city in Türkiye, if they named one.'),
      fieldOfStudy: z.string().optional().describe('What they want to study, if known.'),
      nameGuess: z
        .string()
        .optional()
        .describe('A university name the student mentioned, however roughly spelled.'),
    }),
    execute: async ({ city, fieldOfStudy, nameGuess }) => {
      // A name they already said wins over a city filter — they are trying to
      // confirm a specific school, not browse.
      if (nameGuess?.trim()) {
        const exact = findUniversity(nameGuess);
        if (exact) {
          return {
            ok: true as const,
            resolved: { name: exact.name, city: exact.city, website: exact.website },
            message:
              `${exact.name} is on our list (${exact.city}). Confirm this is the one they mean, then save it with ` +
              'collect_university_application as chosenUniversity and call get_document_checklist.',
          };
        }
        const near = searchUniversities(nameGuess);
        if (near.length) {
          return {
            ok: true as const,
            options: near.map((u) => ({ name: u.name, city: u.city, website: u.website })),
            message:
              'Several universities match that name. Show them as a numbered list and ask which one they mean.',
          };
        }
      }

      const pool = city?.trim() ? universitiesInCity(city, 10) : [];
      const options = (pool.length ? pool : TURKISH_UNIVERSITIES.slice(0, 10)).map((u) => ({
        name: u.name,
        city: u.city,
        website: u.website,
      }));

      return {
        ok: true as const,
        options,
        cities: universityCities().slice(0, 6).map((c) => `${c.city} (${c.count})`),
        totalOnList: TURKISH_UNIVERSITIES.length,
        fieldOfStudy: fieldOfStudy ?? null,
        message:
          (city?.trim() && !pool.length
            ? `We have no partner universities listed in "${city}". Say so, offer the cities in "cities" instead, and show the options below. `
            : '') +
          'Present these as a short numbered list — name, city, website — in the student\'s language. ' +
          'Say we work with ' + TURKISH_UNIVERSITIES.length + ' private universities in Türkiye and can check any of them. ' +
          'Then ask which one they want to apply to. Do NOT state tuition or entry grades — we do not have verified figures. ' +
          'Save their pick with collect_university_application (chosenUniversity).',
      };
    },
  });

  /**
   * What the student has actually uploaded, and what is still outstanding.
   *
   * Without this the agent is blind to the upload card sitting next to it: it
   * can list what is required but never say what is still missing, so it either
   * stays vague ("please upload the remaining documents") or re-asks for files
   * the student already sent. Read-only — it never creates an application row.
   */
  const checkMissingDocuments = tool({
    description:
      'Check which documents the student has already uploaded for a service and which are still missing. ' +
      'Call this whenever they ask what is left, say they have uploaded something, or return to a conversation where a checklist was already shown. ' +
      'Then name the missing documents explicitly as a short list — never say "some documents are missing" without naming them. ' +
      'If everything is in, say so and move to the next step.',
    inputSchema: z.object({
      service: z
        .string()
        .describe('The service, e.g. "University Registration", "Student Visa", "İkamet".'),
    }),
    execute: async ({ service }) => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before they can upload documents or track what is missing.',
        };
      }

      const checklist = findChecklist(service, agent);
      if (!checklist) {
        return { ok: false as const, message: 'No matching checklist. Ask which service they mean.' };
      }

      const status = await getChecklistStatus({
        sessionId: input.sessionId,
        serviceId: checklist.id,
        lang,
      });
      if (!status) {
        return { ok: false as const, message: 'No upload record for that service yet.' };
      }

      const missing = status.items.filter((i) => !i.uploaded).map((i) => i.title);
      const uploaded = status.items.filter((i) => i.uploaded).map((i) => i.title);

      return {
        ok: true as const,
        service: checklist.id,
        uploaded,
        missing,
        uploadedCount: status.uploadedCount,
        total: status.total,
        complete: status.complete,
        message: status.complete
          ? `All ${status.total} documents are uploaded. Congratulate them briefly and tell them what happens next.`
          : `${status.uploadedCount} of ${status.total} uploaded. Name every document in "missing" as a short list in the student's language, then ask for the next one and say briefly where it comes from.`,
      };
    },
  });

  /**
   * Starts the placement service: spends the one credit, then hands back the
   * university's official tuition-payment details so the student can make the
   * first transfer and upload the receipt.
   *
   * Payment details come only from the hand-verified registry. When a
   * university is not in it the tool says so explicitly and the model is told
   * to promise the details rather than produce them — a fabricated IBAN is an
   * international transfer nobody can reverse.
   */
  const startUniversityServiceTool = tool({
    description:
      'Start the university placement service for the university the student already chose. This spends their one service credit. ' +
      'Call this after chosenUniversity is saved and BEFORE showing the document checklist. ' +
      'On the first call it reports the cost and asks for confirmation — tell the student plainly what it costs and wait for their yes. ' +
      'When the service becomes active the tool returns the university\'s official payment details and the first payment amount: present them exactly as returned, changing nothing. ' +
      'If the tool says we do not hold the payment details, tell the student our team will email them the official bank details — NEVER invent an IBAN, a bank name or an amount.',
    inputSchema: z.object({}),
    execute: async () => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message: 'Tell the user they need to sign in before they can start the service.',
        };
      }

      const started = await startUniversityService({
        sessionId: input.sessionId,
        userId: input.userId ?? null,
        confirmed: input.creditsConfirmed === true,
      });

      const pendingFor = (
        creditsAvailable: number,
        nextExpiry: string | null,
        requiresAuth: boolean,
      ): PendingConfirm => ({
        service: 'University Application',
        location: 'Türkiye',
        creditsAvailable,
        nextExpiry,
        requiresAuth,
        documents: [],
      });

      /** The bank block, or an honest admission that we do not hold one yet. */
      const paymentBlock = (university: string) => {
        const details = paymentDetailsFor(university);
        if (!details) {
          return {
            hasPaymentDetails: false as const,
            paymentMessage:
              `We do not hold verified bank details for ${university} yet. Tell the student our team will email them the official payment details within one working day, and that they should upload the receipt here once they have paid. ` +
              'Do NOT invent an IBAN, a bank name, or a payment amount.',
          };
        }
        return {
          hasPaymentDetails: true as const,
          firstPayment: formatAmount(details.firstPayment, details.currency),
          firstPaymentNote: details.firstPaymentNote,
          accountHolder: details.accountHolder,
          bankName: details.bankName,
          iban: formatIban(details.iban),
          swift: details.swift ?? null,
          reference: details.reference ?? null,
          paymentMessage:
            `Show the student these payment details for ${university} exactly as given — the amount, account holder, bank, IBAN, SWIFT and reference — as a clear block in their language. ` +
            'Say the first payment is ' +
            formatAmount(details.firstPayment, details.currency) +
            ' (' + details.firstPaymentNote + '). ' +
            'Then tell them to upload the transfer receipt as the tuition fee receipt in the checklist. Change no digit of the IBAN.',
        };
      };

      switch (started.kind) {
        case 'no_university':
          return {
            ok: false as const,
            message:
              'No university is saved yet. Ask which university they want and save it with collect_university_application first.',
          };
        case 'auth_required':
          pendingConfirm = pendingFor(0, null, true);
          return {
            ok: false as const,
            reason: 'confirmation_required',
            message: 'Tell the user they need to sign in before the service can start.',
          };
        case 'confirmation_required':
          pendingConfirm = pendingFor(
            started.available,
            started.nextExpiry?.toISOString() ?? null,
            false,
          );
          return {
            ok: false as const,
            reason: 'confirmation_required',
            university: started.university,
            creditsAvailable: started.available,
            message:
              `Tell the student that starting their application to ${started.university} uses one service credit (they have ${started.available}), ` +
              'and that it unlocks their document checklist, the uploads, and the university\'s official payment details. ' +
              'Ask them to confirm, and wait — do not call this tool again until they say yes.',
          };
        case 'no_credit':
          pendingConfirm = pendingFor(0, started.nextExpiry?.toISOString() ?? null, false);
          return {
            ok: false as const,
            reason: 'confirmation_required',
            message:
              `Starting the application to ${started.university} needs one service credit and they have none. ` +
              'Tell them warmly they can buy one on the pricing page, and what it unlocks.',
          };
        case 'already_started':
          universityChecklistUnlocked = true;
          return {
            ok: true as const,
            university: started.university,
            ...paymentBlock(started.university),
            alreadyActive: true,
            message:
              `The service for ${started.university} is already active — they were not charged again. ` +
              'Then call get_document_checklist to show what is still needed.',
          };
        case 'started':
          universityChecklistUnlocked = true;
          return {
            ok: true as const,
            university: started.university,
            ...paymentBlock(started.university),
            message:
              `The service is now active for ${started.university} and one credit was used. Congratulate them in one short line. ` +
              'Then call get_document_checklist so they get their upload list.',
          };
      }
    },
  });

  const getDocumentChecklist = tool({
    description: DOCUMENT_CHECKLIST_TOOL_DESCRIPTION,
    inputSchema: z.object({
      service: z
        .string()
        .describe('The service the user is asking about, e.g. "University Registration", "Student Visa", "İkamet", "Health Insurance", "Restaurant", "Company Formation".'),
    }),
    execute: async ({ service }) => {
      const checklist = findChecklist(service, agent);
      if (!checklist) {
        return {
          ok: false as const,
          message:
            'No matching checklist. Answer from your own knowledge instead, and offer the suggested services below the chat.',
        };
      }

      // University registration is gated on the student having chosen a
      // university. Several of these documents are issued by one named
      // university (acceptance letter, tuition receipt) or cost real money to
      // apostille, so handing over the upload card before the choice invites
      // the student to spend on the wrong school. Ask first, upload after.
      if (checklist.id === 'university_registration') {
        const gate = await universityChoiceGate();
        if (gate) return gate;
      }

      // Each item carries the key its upload is filed under, so the client
      // card can turn individual rows green as documents arrive.
      const items = checklistView(checklist, pickLang(lang));

      documentChecklist = { service: checklist.id, agent: checklist.agent, items };

      return {
        ok: true as const,
        service: checklist.id,
        items: items.map((i) => `${i.title} — ${i.whereToGet}`),
        message:
          'List ALL of these documents for the user in their own language, as a clear checklist with where each one comes from. Then ask if they want to start collecting their details with you.',
      };
    },
  });

  /**
   * Form delivery — turns the collected intake data into a filled replica PDF
   * of the official application form and attaches it to the chat. Free: it
   * only formats data the user already gave. The official processed document
   * still comes from the portal, where the dashboard runbook points the
   * download button out.
   */
  const deliverForm = tool({
    description:
      'Generate the filled application document (PDF) from the details the user already gave and deliver it in the chat as a downloadable file. ' +
      'Call this when the user asks for their filled form — İkamet application (first or renewal), visa appointment form, health insurance application, university application packet, or business permit application. ' +
      'If the intake is incomplete the tool returns what is still missing: tell the user which details you still need, a few at a time. ' +
      'When it succeeds, tell the user in their own language that their filled document is ready and attached below the message.',
    inputSchema: z.object({
      form: z
        .enum(['ikamet', 'ikamet_renewal', 'visa', 'insurance', 'university', 'business'])
        .describe('Which filled document to generate.'),
    }),
    execute: async ({ form }: { form: FormKind }) => {
      if (!input.sessionId || input.sessionId.startsWith('guest-')) {
        return {
          ok: false as const,
          message:
            'Tell the user they need to sign in before you can generate their filled document.',
        };
      }

      try {
        let data: Record<string, string> = {};
        let missing: string[] = [];

        switch (form) {
          case 'visa': {
            const state = await readIntake(input.sessionId);
            if (!state) {
              return {
                ok: false as const,
                message:
                  'No visa application was started in this chat yet. Ask the user for their details first (use collect_visa_application as they answer).',
              };
            }
            data = state.data;
            missing = state.missing.map((f) => f.label);
            break;
          }
          case 'university': {
            const state = await readUniversityIntake(input.sessionId);
            if (!state) {
              return {
                ok: false as const,
                message:
                  'No university application was started in this chat yet. Ask the user for their details first (use collect_university_application as they answer).',
              };
            }
            data = state.data;
            missing = state.missing.map((f) => f.label);
            break;
          }
          case 'ikamet':
          case 'ikamet_renewal': {
            const state = await readIkametIntake(input.sessionId);
            if (!state) {
              return {
                ok: false as const,
                message:
                  'No İkamet application was started in this chat yet. Ask the user for their details first (use collect_ikamet_application as they answer).',
              };
            }
            data = state.data;
            missing = state.missing.map((f) => f.label);
            break;
          }
          case 'insurance': {
            const state = await readInsuranceIntake(input.sessionId);
            if (!state) {
              return {
                ok: false as const,
                message:
                  'No insurance application was started in this chat yet. Ask the user for their details first (use collect_insurance_application as they answer).',
              };
            }
            data = state.data;
            missing = state.missing.map((f) => f.label);
            break;
          }
          case 'business': {
            const state = await readBusinessIntake(input.sessionId);
            if (!state) {
              return {
                ok: false as const,
                message:
                  'No business application was started in this chat yet. Ask the user for their details first (use collect_business_application as they answer).',
              };
            }
            data = state.data;
            missing = state.missing.map((f) => f.label);
            break;
          }
        }

        if (missing.length) {
          return {
            ok: false as const,
            stillNeeded: missing,
            message: 'Do not generate the document yet. Ask only for the details in stillNeeded, a few at a time.',
          };
        }

        const { bytes, filename } = await generateFormPdf(form, data);
        const { documentId } = await storeGeneratedForm({
          sessionId: input.sessionId,
          userId: input.userId ?? null,
          kind: form,
          filename,
          bytes,
        });

        attachment = { filename, documentId };
        return {
          ok: true as const,
          filename,
          message:
            'The filled document was generated and is attached below the message. Confirm that to the user in one short sentence in their own language.',
        };
      } catch (e) {
        console.error('[agent-router] deliver_form failed', e);
        return {
          ok: false as const,
          message: 'The document could not be generated. Ask the user to try again in a moment.',
        };
      }
    },
  });

  /**
   * Customer service tools — real database access so the support agent can
   * actually fix account problems: check credits and purchases, repair paid
   * purchases whose credits never landed, and refill the question quota.
   * All of them need a signed-in user; guests must sign in first.
   */
  const checkMyCredits = tool({
    description:
      'Look up the signed-in user\'s real account: available credits, expiry, purchases, question quota, and any paid purchase whose credits are missing.',
    inputSchema: z.object({}),
    execute: async () => {
      if (!input.userId) {
        return {
          ok: false as const,
          message: 'Ask the user to sign in first so their account can be checked.',
        };
      }
      try {
        const summary = await getSupportAccountSummary(input.userId);
        return { ok: true as const, summary };
      } catch {
        return { ok: false as const, message: 'The account could not be read. Ask the user to try again in a moment.' };
      }
    },
  });

  const restoreMissingCredits = tool({
    description:
      'For the signed-in user, create the credits that a PAID purchase never received (failed callback). Idempotent — call this after check_my_credits shows mismatches.',
    inputSchema: z.object({}),
    execute: async () => {
      if (!input.userId) {
        return {
          ok: false as const,
          message: 'Ask the user to sign in first before restoring their credits.',
        };
      }
      try {
        const result = await restoreMissingCreditsForUser(input.userId);
        return { ok: true as const, ...result };
      } catch {
        return { ok: false as const, message: 'The repair failed. Ask the user to try again in a moment.' };
      }
    },
  });

  /**
   * Apply the user's SCHEDULED free-quota refresh, if one is owed.
   *
   * Not a grant. The tool used to top anyone up on request, so asking customer
   * service to "reset" returned an unlimited free allowance — free model usage
   * for anyone who thought to ask twice. It now defers entirely to the refresh
   * schedule, and reports the next refresh time when one is not due.
   */
  const resetMyQuota = tool({
    description:
      "Apply the signed-in user's scheduled free-question refresh, but ONLY if it is already due. " +
      'This is NOT a way to grant extra questions: if the refresh is not due the tool refuses and returns when it next lands. ' +
      'When it refuses, tell the user plainly when their questions refresh, and that service credits are how they continue before then. ' +
      'Never imply you can top them up, add questions, or make an exception — you cannot, and saying so sets up a promise the system will not keep.',
    inputSchema: z.object({}),
    execute: async () => {
      if (!input.userId) {
        return {
          ok: false as const,
          message: 'Ask the user to sign in first before checking their quota.',
        };
      }
      try {
        const result = await resetUserTokenQuota(input.userId);
        if (!result.ok) {
          return {
            ok: false as const,
            reason: 'not_due' as const,
            tokenBalance: result.tokenBalance,
            refreshesAt: result.refreshesAt.toISOString(),
            message:
              `Their questions are not due to refresh yet — the next one is at ${result.refreshesAt.toISOString()} and they have ${result.tokenBalance} left. ` +
              'Say that plainly and offer service credits as the way to continue now. Do NOT offer to reset it anyway.',
          };
        }
        return { ok: true as const, tokenBalance: result.tokenBalance };
      } catch {
        return { ok: false as const, message: 'The quota could not be checked. Ask the user to try again in a moment.' };
      }
    },
  });

  const startRoadmap = tool({
    description: ROADMAP_TOOL_DESCRIPTION,
    inputSchema: z.object({
      service: z
        .string()
        .describe('The business type or service, e.g. "Cafe & Restaurant", "Retail Shop", "Company Formation", "Residence Permit".'),
      district: z
        .string()
        .describe('The district or city the user is in, e.g. "Kadıköy", "Ankara".'),
    }),
    execute: async ({ service, district }) => {
      // Same paywall as the chip path. When unconfirmed the tool refuses and
      // the route asks the user; the model is told to stop describing steps so
      // it does not hand over the deliverable for free in prose.
      const gate = await checkRoadmapCredit(input, service, district, agent, lang);
      if (gate.kind === 'blocked') {
        pendingConfirm = gate.pending;
        return {
          ok: false as const,
          reason: 'confirmation_required',
          message:
            'Do not list the roadmap steps. Tell the user in one short sentence that building the roadmap uses one service credit, and wait for them to confirm.',
        };
      }

      const built = await buildRoadmap(service, district, agent, lang, input.sessionId);
      if (!built) {
        if (gate.creditId) await refundCredit(gate.creditId, input.userId!, 'unknown service');
        return { ok: false as const };
      }
      dashboardState = built.dashboardState;
      roadmapText = built.content;
      consumedCreditId = gate.creditId ?? null;
      return { ok: true as const };
    },
  });

  const history: ModelMessage[] = (input.messages ?? [])
    .slice(-MAX_HISTORY_TURNS)
    .filter(m => m.content?.trim())
    .map(m => ({
      role: m.role === 'assistant' ? ('assistant' as const) : ('user' as const),
      content: m.content,
    }));

  const messages: ModelMessage[] = [...history, { role: 'user', content: input.query }];

  // Seed the choice flag, but only for a turn that could actually show the
  // university checklist — every other student turn skips the query entirely.
  if (
    agent === 'student' &&
    input.sessionId &&
    !input.sessionId.startsWith('guest-') &&
    findChecklist(input.query ?? '', agent)?.id === 'university_registration'
  ) {
    const state = await readUniversityIntake(input.sessionId);
    universityChecklistUnlocked =
      hasChosenUniversity(state?.data ?? {}) && Boolean(state?.application.credit_id);
  }

  // Tool policy per agent: support gets the account-repair tools; the lawyer
  // only records defense cases; the student collects visa/university/ikamet/
  // insurance intakes; the permit agent collects business intakes. Both
  // student and permit can look up document checklists and build roadmaps.
  const toolSet: Record<string, any> | undefined = isStepQuery
    ? undefined
    : agent === 'support'
      ? {
          check_my_credits: checkMyCredits,
          restore_missing_credits: restoreMissingCredits,
          reset_my_quota: resetMyQuota,
        }
      : agent === 'lawyer'
        ? { collect_criminal_case: collectCriminalCase }
        : agent === 'student'
          ? {
              start_roadmap: startRoadmap,
              collect_visa_application: collectVisaApplication,
              collect_university_application: collectUniversityApplication,
              collect_ikamet_application: collectIkametApplication,
              collect_insurance_application: collectInsuranceApplication,
              suggest_universities: suggestUniversities,
              start_university_service: startUniversityServiceTool,
              get_document_checklist: getDocumentChecklist,
              check_missing_documents: checkMissingDocuments,
              deliver_form: deliverForm,
            }
          : {
              start_roadmap: startRoadmap,
              collect_business_application: collectBusinessApplication,
              get_document_checklist: getDocumentChecklist,
              deliver_form: deliverForm,
            };

  const callOptions = {
    model: qwen(),
    system: buildSystemPrompt({
      agent,
      lang,
      isStepQuery,
      userName: input.userName,
      ragContext: context || undefined,
      isVoice: input.isVoice === true,
    }),
    messages,
    // Step explanations are long-form; ordinary chat replies stay short and
    // conversational (see the brevity rules in prompts.ts).
    maxOutputTokens: isStepQuery ? 1200 : 400,
    tools: toolSet,
    // AI SDK v6 defaults to stepCountIs(1): without this, a tool call that
    // produces no prose stops the loop before the model writes its follow-up
    // question — the agent saves data and then says nothing.
    stopWhen: stepCountIs(3),
    providerOptions: QWEN_PROVIDER_OPTIONS,
  };

  /**
   * Deterministic backstop for the upload checklist.
   *
   * The prompt tells the model to call get_document_checklist whenever a
   * service is named, but for services it knows well (İkamet especially) it
   * reliably prefers to answer from memory. A prose list is useless here: the
   * checklist event is the only thing that renders the upload card, so without
   * it the applicant is told what to bring and given nowhere to bring it.
   *
   * So when the user's own words clearly name a service and the model did not
   * call the tool, resolve the checklist ourselves. The model's prose still
   * stands; this only re-attaches the card it should have produced.
   */
  const ensureChecklist = () => {
    if (documentChecklist) return;
    const match = findChecklist(input.query ?? '', agent);
    if (!match) return;
    // The backstop must respect the same gate the tool does, or "I want to
    // register at a university" would attach the upload card on the very first
    // message and undo the choice-first flow entirely. This reads the flag
    // rather than the database because the getters it serves are synchronous;
    // the flag is seeded before the model runs and flipped by the intake tool
    // the moment a university is saved.
    if (match.id === 'university_registration' && !universityChecklistUnlocked) return;
    documentChecklist = {
      service: match.id,
      agent: match.agent,
      items: checklistView(match, pickLang(lang)),
    };
  };

  // ── Turkmen: validate before showing, because Qwen intermittently loops ────
  if (lang === 'tk') {
    const text = await generateValidatedTurkmen(callOptions, () => {
      // A retry re-runs the tool, so clear anything the failed attempt set.
      dashboardState = null;
      visaIntake = null;
      universityIntake = null;
      ikametIntake = null;
      insuranceIntake = null;
      businessIntake = null;
      documentChecklist = null;
      attachment = null;
      roadmapText = null;
    });
    const finalText = text || roadmapText || TURKMEN_FALLBACK;
    return {
      kind: 'stream',
      textStream: (async function* () { yield finalText; })(),
      sources,
      getDashboardState: () => dashboardState,
      getVisaIntake: () => visaIntake,
      getUniversityIntake: () => universityIntake,
      getIkametIntake: () => ikametIntake,
      getInsuranceIntake: () => insuranceIntake,
      getBusinessIntake: () => businessIntake,
      getDocumentChecklist: () => { ensureChecklist(); return documentChecklist; },
      getAttachment: () => attachment,
      getConsumedCreditId: () => consumedCreditId,
      getPendingConfirm: () => pendingConfirm,
    };
  }

  const result = streamText(callOptions);

  // When the tool fires, the model usually emits no prose — we supply the
  // deterministic summary instead so the wording matches the chip flow exactly.
  async function* merged(): AsyncGenerator<string> {
    let emitted = 0;
    for await (const delta of result.textStream) {
      emitted += delta.length;
      yield delta;
    }
    if (roadmapText && emitted < 40) yield roadmapText;
  }

  return {
    kind: 'stream',
    textStream: merged(),
    sources,
    getDashboardState: () => dashboardState,
    getVisaIntake: () => visaIntake,
    getUniversityIntake: () => universityIntake,
    getIkametIntake: () => ikametIntake,
    getInsuranceIntake: () => insuranceIntake,
    getBusinessIntake: () => businessIntake,
    getDocumentChecklist: () => { ensureChecklist(); return documentChecklist; },
    getAttachment: () => attachment,
    getConsumedCreditId: () => consumedCreditId,
    getPendingConfirm: () => pendingConfirm,
  };
}

// ---------------------------------------------------------------------------
// Roadmap paywall
//
// One credit buys one finalised roadmap. Two rules make this safe:
//   - the credit is spent BEFORE the roadmap is built, so a crash cannot hand
//     out a free one (the caller refunds if the build then fails);
//   - a credit is only ever spent when the user has explicitly confirmed,
//     because a roadmap otherwise fires from a single chip tap and a mis-click
//     would cost real money.
// ---------------------------------------------------------------------------

type CreditGate =
  | { kind: 'allowed'; creditId: number | null }
  | { kind: 'blocked'; pending: PendingConfirm };

async function checkRoadmapCredit(
  input: AgentInput,
  service: string,
  location: string,
  agent: AgentType,
  lang: Lang,
): Promise<CreditGate> {
  const documents = previewDocuments(service, location, agent, lang);
  // Guests cannot own credits. Prompt sign-in rather than silently failing.
  if (!input.userId) {
    return {
      kind: 'blocked',
      pending: { service, location, creditsAvailable: 0, nextExpiry: null, requiresAuth: true, documents },
    };
  }

  const balance = await getCreditBalance(input.userId);

  // Unconfirmed, or nothing to spend — either way, ask first.
  if (!input.creditsConfirmed || balance.available < 1) {
    return {
      kind: 'blocked',
      pending: {
        service,
        location,
        creditsAvailable: balance.available,
        nextExpiry: balance.nextExpiry?.toISOString() ?? null,
        requiresAuth: false,
        documents,
      },
    };
  }

  const creditId = await consumeCredit(input.userId, input.sessionId);
  if (creditId === null) {
    // Lost a race against a concurrent request — treat as no credit.
    return {
      kind: 'blocked',
      pending: { service, location, creditsAvailable: 0, nextExpiry: null, requiresAuth: false, documents },
    };
  }

  return { kind: 'allowed', creditId };
}

// ---------------------------------------------------------------------------
// Turkmen degeneracy guard
//
// Qwen's Turkmen collapses into a repetition loop in roughly 40% of attempts.
// Failures are independent between attempts — the same prompt that loops once
// usually comes back clean — so regenerating works where prompt tuning and
// repetition penalties (both measured) did not.
//
// Generation is streamed internally and checked as it arrives, so a loop is
// killed within a couple of hundred characters instead of grinding on to the
// token limit. That keeps retries cheap enough to afford several of them.
//
// The cost is that Turkmen replies cannot be streamed to the *client*: a loop
// is only visible once enough text exists to measure, and text already sent
// cannot be retracted. A short pause beats hundreds of repeated words.
// ---------------------------------------------------------------------------

const MAX_TURKMEN_ATTEMPTS = 5;
/** Re-check the partial reply roughly every this many characters. */
const TURKMEN_CHECK_INTERVAL = 250;

const TURKMEN_FALLBACK =
  'Bagyşlaň, bu soraga jogaby taýýarlamakda kynçylyk ýüze çykdy. Sowalyňyzy başgaça beýan edip görüň ýa-da aşakdaky hödürlenen hyzmatlardan birini saýlaň.';

async function generateValidatedTurkmen(
  options: Parameters<typeof streamText>[0],
  resetToolState: () => void,
): Promise<string> {
  for (let attempt = 1; attempt <= MAX_TURKMEN_ATTEMPTS; attempt++) {
    if (attempt > 1) resetToolState();

    const controller = new AbortController();
    let text = '';
    let abortedForLoop = false;
    let nextCheckAt = TURKMEN_CHECK_INTERVAL;

    try {
      const result = streamText({ ...options, abortSignal: controller.signal });

      for await (const delta of result.textStream) {
        text += delta;
        if (text.length >= nextCheckAt) {
          nextCheckAt = text.length + TURKMEN_CHECK_INTERVAL;
          if (detectDegeneration(text).degenerate) {
            abortedForLoop = true;
            controller.abort();
            break;
          }
        }
      }
    } catch (e) {
      // An abort we requested is expected control flow, not an error.
      if (!abortedForLoop) {
        if (attempt === MAX_TURKMEN_ATTEMPTS) throw e;
        continue;
      }
    }

    const report = detectDegeneration(text);
    if (!abortedForLoop && !report.degenerate) return text;

    console.warn(
      `[agent-router] Turkmen attempt ${attempt}/${MAX_TURKMEN_ATTEMPTS} degenerate` +
        `${abortedForLoop ? ' (aborted early)' : ''} — ` +
        `uniqueRatio=${report.uniqueRatio.toFixed(2)}, "${report.topPhrase}" ×${report.topPhraseCount}`,
    );
  }

  console.error('[agent-router] All Turkmen attempts degenerate — serving fallback');
  return TURKMEN_FALLBACK;
}
