'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
  translateHistory: (content: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    navbar_home: 'Home',
    navbar_chat: 'AI Agents',
    navbar_dashboard: 'Dashboard',
    navbar_get_started: 'Get Started',
    home_hero_title: 'The AI Platform for Turkish Business, Law & Education.',
    home_hero_subtitle: 'Navigate permits, legal protocols, and university registration effortlessly. Our specialized AI agents build your personalized roadmap in seconds.',
    home_hero_greeting_user: 'Hi Hamza',
    home_hero_question: 'Where should we start?',
    home_hero_cta: 'Get Started',
    hero_cat_upload: 'Upload documents',
    hero_cat_status: 'Check status',
    hero_cat_protocols: 'District protocols',
    hero_cat_safety: 'Fire safety guide',
    how_it_works_label: 'How it works',
    process_title: 'The AI Process',
    process_subtitle: 'Let our AI Agents handle the heavy lifting for you.',
    process_step1_title: 'Describe',
    process_step1_desc: 'Tell us about your business, legal issue, or university goals in plain language. Our AI instantly understands local regulations and requirements.',
    process_step2_title: 'Analyze',
    process_step2_desc: 'Our specialized AI agents cross-reference municipal protocols, laws, and academic guidelines to build your exact roadmap.',
    process_step3_title: 'Execute',
    process_step3_desc: 'We map out every step—from e-Devlet filings and ID renewals to university enrollment—so you can focus on your goals without the bureaucratic headache.',
    dashboard_title: 'Business Dashboard',
    dashboard_sync: 'Sync',
    dashboard_ask_ai: 'Ask AI',
    dashboard_upload: 'Upload Docs',
    chat_placeholder: 'Ask TurkGateway AI agents...',
    chat_new: 'New Chat',
    chat_greeting: 'Hello there.',
    chat_subtitle: 'How can I help with Istanbul permits today?',
    chat_q1: 'What permits do I need for a restaurant in Istanbul?',
    chat_q2: 'How long does the fire safety inspection take?',
    chat_q3: 'What documents does the municipality require?',
    chat_q4: 'What is the cost of a fire safety certificate?',
    dashboard_updated: 'Updated',
    dashboard_live_session: 'Live Session',
    dashboard_days: 'days',
    dashboard_active: 'active',
    dashboard_running: 'Running',
    dashboard_stopped: 'Stopped',
    dashboard_agent_status: 'Agent processing workflow',
    dashboard_ask_ai_step: 'Ask AI about this step',
    dashboard_no_session: 'No active session',
    dashboard_processing: 'Processing...',
    dashboard_compliance_score: 'Compliance Score',
    dashboard_steps_complete: 'Steps Complete',
    dashboard_est_days: 'Est. Days Left',
    dashboard_active_agents: 'Active AI Agents',
    dashboard_overall_progress: 'Overall Progress',
    dashboard_workflow_steps: 'Workflow Steps',
    dashboard_roadmap: 'ROADMAP',
    agent_badge: 'Agent',
    dashboard_action_required: 'Action Required',
    dashboard_all_clear: 'All clear',
    dashboard_action_required_desc: 'Please complete the {step} step to proceed.',
    dashboard_bot_processing: 'System is currently processing agent tasks.',
    dashboard_whats_next: 'What\'s next',
    dashboard_next_step_desc: 'Once your initial documents are approved, your final Business License (İşyeri Açma ve Çalışma Ruhsatı) will be processed.',
    dashboard_init_title: 'Initialize Workflow',
    dashboard_init_summary: 'Start a chat to generate your permit plan.',
    dashboard_init_detail: 'Once you describe your business in the chat, the AI will generate a customized permit path for you here.',
    dashboard_mark_complete: 'Mark as Complete',
    dashboard_mark_done: 'Mark step as done',
    dashboard_syncing: 'Synchronizing with Local Municipality...',
    dashboard_toast_success: 'Document uploaded successfully!',
    dashboard_auto_execute: 'Auto-Execute Bot',
    status_completed: 'Completed',
    status_in_progress: 'In Progress',
    status_pending: 'Pending',
    chat_welcome: 'Hi {name}',
    chat_begin: 'Where do we begin?',
    chat_placeholder_permit: 'Ask business AI...',
    chat_placeholder_student: 'Ask student AI...',
    chat_placeholder_lawyer: 'Ask legal AI...',
    chat_ask_placeholder: 'Ask anything',
    chat_voice: 'Voice',
    chat_listening: 'Listening...',
    chat_switch_assistant: 'SWITCH AGENT',
    chat_suggestion_business: 'Open Business',
    chat_suggestion_permit: 'Get Permits',
    chat_suggestion_location: 'District Rules',
    chat_suggestion_duration: 'Timelines',
    chat_suggestion_cost: 'Costs & Fees',
    chat_suggestion_obtain: 'Get Business Permit',
    chat_suggestion_steps: 'Process Steps',
    chat_suggestion_docs: 'Required Docs',
    chat_suggestion_help: 'How it works',
    sidebar_new_chat: 'New Chat',
    sidebar_recent: 'Recent',
    sidebar_help: 'Help',
    sidebar_activity: 'Activity',
    sidebar_settings: 'Settings',
    navbar_pricing: 'Pricing',
    navbar_services: 'Services',
    navbar_download: 'Download',
    sidebar_upgrade: 'Upgrade',
    sidebar_home: 'Home',
    sidebar_dashboard: 'Dashboard',
    sidebar_my_stuff: 'My stuff',
    sidebar_favorites: 'Favorites',
    sidebar_no_favorites: 'No favorites yet',
    sidebar_gems: 'Gems',
    sidebar_logout: 'Logout',
    navbar_logout: 'Logout',
    navbar_login: 'Login',
    navbar_signup: 'Sign Up',
    navbar_subscribers: 'Subscribers',
    dashboard_no_permits: 'No active permits found',
    sidebar_switch_assistant: 'Switch Assistant',
    sidebar_sign_in_prompt: 'Sign in to start saving your chats',
    sidebar_sign_in_desc: 'Once you\'re signed in, you can access your recent chats here.',

    help_title: 'Help Center',
    help_faq: 'FAQ',
    help_contact: 'Contact Support',
    help_docs: 'Documentation',
    help_feedback: 'Send Feedback',
    help_search: 'Search for help...',
    home_stat_districts: 'Districts covered',
    home_stat_types: 'Permit types',
    home_stat_time: 'Time saved',
    home_stat_success: 'Success rate',
    home_feature_agents: 'Multi-Agent AI',
    home_feature_agents_desc: 'LangGraph orchestrated agents run planning, classification, and compliance checking in parallel.',
    home_feature_districts: 'All 39 Districts',
    home_feature_districts_desc: 'Full Istanbul coverage — supporting all 39 municipalities with distinct local protocols.',
    home_feature_tracking: 'Real-Time Tracking',
    home_feature_tracking_desc: 'Every step of your permit application is tracked. Nothing falls through the cracks.',
    home_step1_title: 'Tell us about your business',
    home_step1_desc: 'Answer a few questions about your business type, location, and scope.',
    home_step2_title: 'AI maps your permit path',
    home_step2_desc: 'Our agent system identifies every permit and document required for your case.',
    home_step3_title: 'Upload documents',
    home_step3_desc: 'We guide you through each required document with checklists and templates.',
    home_step4_title: 'Receive your approval',
    home_step4_desc: 'Track every approval in real time. Estimated timelines per municipality.',
    dashboard_toast_success_payment: 'Subscription activated! Welcome to Premium.',
    dashboard_toast_error_payment: 'Payment failed. Please try again.',
    dashboard_toast_error_sub: 'Failed to start subscription',
    assistant_permit: 'Business',
    assistant_student: 'Student',
    assistant_lawyer: 'Lawyer',
    dashboard_student_title: 'Student Dashboard',
    dashboard_legal_title: 'Lawyer Dashboard',
    dashboard_free_plan: 'Free Plan',
    dashboard_premium: 'Premium',
    dashboard_upgrade: 'Upgrade',
    dashboard_starting: 'Starting...',
    dashboard_integration: 'Integration',
    dashboard_simulating: 'Simulating Local Municipality API...',
    loading_preparing: 'Initializing AI Protocol Engine...',
    loading_verifying: 'Verifying credentials with e-Devlet...',
    loading_analyzing: 'Analyzing district protocols...',
    loading_building: 'Building your custom roadmap...',
    loading_finalizing: 'Finalizing synchronization...',
    dashboard_rpa_desc: 'Our RPA bot requires your credentials to log into {url} and automatically submit the verified documents on your behalf.',
    dashboard_id_label: 'T.C. Kimlik No',
    dashboard_password_label: 'Password',
    dashboard_id_placeholder: '11-digit ID number',
    dashboard_password_placeholder: '••••••••••••',
    dashboard_disabled_law: 'DISABLED UNTIL LAW APPROVAL',
    dashboard_privacy_notice: 'Your credentials are used solely for this session and are NEVER logged into our database.',
    auth_login_title: 'Welcome Back',
    auth_login_subtitle: 'Access your personalized TurkGateway AI Agents.',
    auth_signup_title: 'Create Account',
    auth_signup_subtitle: 'Start your journey with TurkGateway AI Agents.',
    auth_email: 'Email address',
    auth_password: 'Password',
    auth_full_name: 'Full Name',
    auth_forgot_password: 'Forgot password?',
    auth_no_account: 'Don\'t have an account?',
    auth_has_account: 'Already have an account?',
    auth_signing_in: 'Signing in...',
    auth_signing_up: 'Creating account...',
    auth_enter_password: 'Enter your password',
    auth_email_not_found: "Couldn't find your TurkGateway Account",
    chat_permit_desc: 'Business & Municipal Protocol',
    chat_student_desc: 'Academic Tasks & ID Renewals',
    chat_lawyer_desc: 'Legal Advice & Compliance',
    chat_sug_renew: 'Renew Kimlik/ID',
    chat_sug_uni: 'Best Universities',
    chat_sug_roadmap: 'Register Roadmap',
    chat_sug_deadlines: 'Deadlines',
    chat_sug_visas: 'Student Visas',
    chat_sug_shelp: 'Student Help',
    chat_sug_contract: 'Contract Review',
    chat_sug_formation: 'Company Formation',
    chat_sug_employ: 'Employment Law',
    chat_sug_times: 'Legal Timelines',
    chat_sug_resid: 'Residency/Permit',
    chat_sug_dispute: 'Legal Disputes',
    pricing_title: 'Simple, transparent pricing',
    pricing_subtitle: 'Start free. Upgrade when you need compliance automation that scales.',
    pricing_monthly: 'Monthly',
    pricing_annual: 'Annual',
    pricing_save: 'Save {amount}/yr',
    pricing_free_desc: 'For individuals exploring permit requirements. No credit card required.',
    pricing_premium_desc: 'Full capabilities for businesses managing compliance at scale in Istanbul.',
    pricing_current: 'Current Plan',
    pricing_upgrade: 'Upgrade to Premium',
    quota_reached_title: 'Model quota reached',
    quota_reached_desc: "Your plan's baseline quota has been exhausted. Please wait for the refresh or upgrade to continue.",
    quota_refresh_msg: "Your plan's baseline quota will refresh on",
    quota_dismiss: 'Dismiss',
    tokens_unit: 'Tokens',
    pricing_most_popular: 'Most Popular',
    pricing_compare: 'Compare plans',
    pricing_compare_subtitle: 'Everything you need to make the right decision.',
    pricing_faq_title: 'Frequently asked questions',
    pricing_faq_subtitle: 'Have a question not listed here?',
    pricing_contact_us: 'Contact us',
    pricing_cta_title: 'Ready to streamline your compliance?',
    pricing_cta_subtitle: 'Join businesses across Istanbul using TurkGateway to automate their regulatory workflows.',
    pricing_secure_checkout: 'Secure checkout via iyzico',
    pricing_cancel_anytime: 'Cancel anytime',
    pricing_vat_included: 'VAT invoice included',
    pricing_feat_ai: 'AI Permit Consultations',
    pricing_feat_sessions: 'Active Sessions',
    pricing_feat_history: 'Project History',
    pricing_feat_docs: 'Document Management',
    pricing_feat_priority: 'Priority Agent Workflows',
    pricing_feat_support: '1-on-1 Regulatory Support',
    pricing_feat_access: 'Early Access to New Regulations',
    pricing_feat_multi: 'Multi-language Support (TR/EN/AR)',
    pricing_feat_comm: 'Community Access',
    pricing_feat_limited: 'Limited',
    pricing_feat_unlimited: 'Unlimited',
    pricing_feat_7days: '7 days',
    pricing_faq_q1: 'Can I cancel my subscription at any time?',
    pricing_faq_a1: 'Yes. You can cancel your Premium subscription at any time from your account settings. You will retain access until the end of your current billing period.',
    pricing_faq_q2: 'Is my payment information secure?',
    pricing_faq_a2: 'All payments are processed by iyzico, a PCI-DSS Level 1 certified payment provider. We never store your card details on our servers.',
    pricing_faq_q3: 'What happens when I upgrade from Free to Premium?',
    pricing_faq_a3: 'Your account is upgraded instantly. All limits are lifted and priority features become available immediately after payment confirmation.',
    pricing_faq_q4: 'Do you offer invoices for business accounting?',
    pricing_faq_a4: 'Yes. A VAT-compliant invoice is automatically issued via iyzico after every successful payment and can be downloaded from your account.',
    pricing_trust_enc: 'Bank-level encryption',
    pricing_trust_pci: 'PCI-DSS Compliant',
    pricing_trust_supp: 'Priority support',
    pricing_trust_resp: 'avg. 2h response',
    pricing_trust_cancel: 'Cancel anytime',
    pricing_trust_lockin: 'No lock-in contracts',
    pricing_get_started: 'Get started with Premium',
    pricing_ready: 'Ready to streamline your compliance?',
    connect_in: 'in',
    agent_name: 'TurkGateway AI Agent',
    agent_thinking: 'Agent is thinking...',
    footer_version: 'Municipal Protocol Engine • v2.5',
    dist_adalar: 'Adalar', dist_arnavutkoy: 'Arnavutköy', dist_atasehir: 'Ataşehir', dist_avcilar: 'Avcılar', dist_bagcilar: 'Bağcılar',
    dist_bahcelievler: 'Bahçelievler', dist_bakirkoy: 'Bakırköy', dist_basaksehir: 'Başakşehir', dist_bayrampasa: 'Bayrampaşa', dist_besiktas: 'Beşiktaş',
    dist_beykoz: 'Beykoz', dist_beylikduzu: 'Beylikdüzü', dist_beyoglu: 'Beyoğlu', dist_buyukcekmece: 'Büyükçekmece', dist_catalca: 'Çatalca',
    dist_cekmekoy: 'Çekmeköy', dist_esenler: 'Esenler', dist_esenyurt: 'Esenyurt', dist_eyupsultan: 'Eyüpsultan', dist_fatih: 'الفاتح',
    dist_gaziosmanpasa: 'Gaziosmanpaşa', dist_gungoren: 'Güngören', dist_kadikoy: 'Kadıköy', dist_kagithane: 'Kağıthane', dist_kartal: 'Kartal',
    dist_kucukcekmece: 'Küçükçekmece', dist_maltepe: 'Maltepe', dist_pendik: 'Pendik', dist_sancaktepe: 'Sancaktepe', dist_sariyer: 'Sarıyer',
    dist_sile: 'Şile', dist_silivri: 'Silivri', dist_sisli: 'Şişli', dist_sultanbeyli: 'Sultanbeyli', dist_sultangazi: 'Sultangazi',
    dist_tuzla: 'Tuzla', dist_umraniye: 'Ümraniye', dist_uskudar: 'Üsküdar', dist_zeytinburnu: 'Zeytinburnu',
    biz_restaurant: 'Restaurant', biz_cafe: 'Café', biz_retail: 'Retail Store', biz_office: 'Office', biz_pharmacy: 'Pharmacy',
    biz_bakery: 'Bakery', biz_barber: 'Barber Shop', biz_gym: 'Gym', biz_shop: 'Shop', biz_store: 'Store', biz_company: 'Company',
    settings_title: 'Settings',
    settings_appearance: 'Appearance',
    settings_profile: 'Profile',
    settings_history: 'Chat History',
    settings_security_title: 'Security & Privacy',
    settings_theme: 'Theme',
    settings_lang: 'Language',
    settings_2fa_title: 'Two-Factor Authentication',
    settings_2fa_desc: 'Add an extra layer of security to your account.',
    settings_2fa_enable: 'Enable 2FA',
    settings_sessions_title: 'Active Sessions',
    settings_sessions_desc: 'Manage and sign out of other active sessions.',
    settings_sessions_logout: 'Sign out other sessions',
    settings_danger_zone: 'Danger Zone',
    settings_delete_desc: 'Once you delete your account, there is no going back. Please be certain.',
    settings_delete_account: 'Delete Account',
    settings_delete_confirm: 'TYPE "DELETE" TO CONFIRM ACCOUNT REMOVAL',
    settings_delete_yes: 'Yes, delete my account',
    settings_confirm_clear: 'Yes, clear history',
    settings_cancel: 'Cancel',
    settings_clear_history: 'Clear History',
    biz_clothing: 'Clothing Store', biz_hotel: 'Hotel', biz_clinic: 'Clinic', biz_school: 'School',
    scroll_right: 'Scroll Right',
    click_to_flip: 'Tap to reveal',
    auth_terms: 'Terms',
    auth_privacy: 'Privacy',
    auth_help: 'Help',
    footer_english: 'English',
    footer_turkish: 'Turkish',
    footer_arabic: 'Arabic',
    auth_login_header: 'Sign in',
    auth_login_subheader: 'with your TurkGateway Account',
    auth_forgot_email: 'Forgot email?',
    auth_guest_notice: 'Not your computer? Use Guest mode to sign in privately.',
    auth_learn_more: 'Learn more about using Guest mode',
    auth_next: 'Next',
    auth_change_email: 'Change email',
    auth_signup_header: 'Create account',
    auth_signup_subheader: 'to continue to TurkGateway',
    auth_signin_instead: 'Sign in instead',
    auth_sign_in_as: 'Sign in as',
    services_title: 'Explore AI Agents',
    services_subtitle: 'Scale your administrative journey with professional AI support.',
    services_permit_desc: 'Business licenses, retail permits, and industrial compliance setup.',
    services_student_desc: 'University registration, residence permits, and student renewals.',
    services_lawyer_desc: 'Professional legal assistance and compliance verifications.',
    services_feat_retail: 'Retail establishment permits',
    services_feat_restaurant: 'Restaurant & Cafe Licensing',
    services_feat_fire: 'Fire safety compliance',
    services_feat_municipal: 'Municipal protocols',
    services_feat_uni: 'University registration',
    services_feat_visa: 'Student visa application',
    services_feat_kimlik: 'Getting & renewing ID (Kimlik)',
    services_feat_nufus: 'Getting Nüfus (Address registration)',
    services_feat_contract: 'Contract review',
    services_feat_formation: 'Company formation',
    services_feat_disputes: 'Legal disputes',
    services_feat_compliance: 'Compliance checks',
    services_status_available: 'Available',
    services_status_active: 'Active',
    services_status_waitlist: 'Waitlist',
    services_status_soon: 'Coming Soon',
    services_cta_describe: 'Describe what you need',
    services_ai_does_work: 'AI does the work',
    services_ai_desc: 'TurkGateway works through each step, looping you in before anything significant. Watch in real time or walk away.',
    services_control_title: "You're in control",
    services_control_desc: 'You choose which portals and databases TurkGateway can access. Before an agent acts, it shows you the plan.',
    services_encryption: 'End-to-End Encryption',
    services_privacy: 'Privacy First',
    services_allow_files: 'Allow Agent to change files?',
    services_allow_desc: 'This includes municipal forms and e-Devlet downloads. Agent will be able to read, edit, and temporarily store files.',
    services_allow_access: 'Allow Access',
    services_always_allow: 'Always Allow',
    services_list_title: "Let's knock something off your list",
    services_task_tax: 'Tax Compliance',
    services_task_register: 'Register Company',
    services_task_enroll: 'University Enrollment',
    services_task_permit: 'Get Work Permit',
    services_task_legal: 'Legal Consultation',
    services_task_renewal: 'Kimlik Renewal',
    services_cta_title: 'Describe what you need',
    services_cta_desc: 'Tell TurkGateway what you want to achieve. Our agents pick the fastest path: connecting to government portals, municipal APIs, or using advanced OCR to process your documents instantly.',
    services_launch_agent: 'Launch Agent',
    services_chat_greeting: 'How can I help you today?',
    services_setup_agent: 'Setup Agent',
    services_start_agent: 'Start Agent',
    services_type_service: 'Type of Service',
    services_select_service: 'Select Service',
    services_select_uni: 'Select University',
    services_select_uni_placeholder: 'Select a University',
    services_district: 'Istanbul District',
    services_select_district: 'Select District',
    services_secure_session: 'Secure 256-bit Encrypted Session',
    services_res_register: "Perfect. I've initialized the Legal Agent. I am connecting to the MERSİS portal to generate your LLC establishment roadmap. Here are the first steps...",
    services_res_tax: "I am retrieving the latest VDK corporate tax checklists and generating an automated audit protocol for your digital business.",
    services_res_permit: "Initiating Business Agent. Connecting to the Ministry of Labor portal to fetch the current quota exemptions and employer requirements.",
    services_res_enroll: "Student Agent initialized. Fetching the specific YÖK requirements for Koç University and your residence permit documentation list.",
    services_res_renewal: "I will guide you through the e-ikamet extension application. Connecting to the GÖÇ Administration API to verify your current permit status...",
    services_res_legal: "Legal Agent checking in. I have accessed the Turkish Commercial Code framework to generate a review standard for your trade contract.",
    services_prompt_register: "I want to open a new LLC in Turkey. What are the legal requirements and steps?",
    services_prompt_tax: "I need to ensure my digital business is fully compliant with Turkish corporate tax.",
    services_prompt_permit: "I want to apply for a work permit for a foreign employee in Istanbul.",
    services_prompt_enroll: "I need help registering at Koç University and applying for a student visa.",
    services_prompt_renewal: "My e-ikamet (residence permit) expires next month, how do I renew it?",
    services_prompt_legal: "I want to review an international trade contract under Turkish commercial law.",
    guest_modal_title: "Thanks for trying TurkGateWay",
    guest_modal_desc: "Log in or sign up to get smarter responses, unlock roadmaps, and more.",
    login: "Log in",
    signup_free: "Sign up for free",
    stay_logged_out: "Stay logged out",
    chat_tab_suggested: 'Suggested',
    chat_tab_chat: 'Chat',
    chip_cafe_restaurant: 'Cafe & Restaurant',
    chip_retail_shop: 'Retail Shop',
    chip_office_tech: 'Office & Tech',
    chip_pharmacy: 'Pharmacy',
    chip_clinic: 'Clinic',
    chip_residence_permit: 'Residence Permit',
    chip_uni_reg: 'University Registration',
    chip_ikamet: 'ID / İkamet',
    chip_denklik: 'Denklik (Equivalency)',
    chip_dormitory: 'Dormitory & Housing',
    chip_student_visa: 'Student Visa',
    chip_istanbul_kart: 'IstanbulKart',
    chip_company_formation: 'Company Formation',
    chip_contract_review: 'Contract Review',
    chip_employment_law: 'Employment Law',
    chip_legal_disputes: 'Legal Disputes',
    chip_residency_visas: 'Residency & Visas',
    chip_real_estate: 'Real Estate Law',
    help_hero: 'How can we help you?',
    help_cat_docs_title: 'Documentation',
    help_cat_docs_desc: 'Detailed guides for business permits, students, and lawyer protocols',
    help_cat_community_title: 'Community',
    help_cat_community_desc: 'Join 10k+ businesses and students in Istanbul',
    help_cat_resources_title: 'Resource Center',
    help_cat_resources_desc: 'Checklists, laws and PDF templates',
    help_explore: 'Explore',
    help_faq_q1: 'How do I start a new session with an AI Agent?',
    help_faq_a1: 'Navigate to the Services page and select your goal (e.g., Opening a Business, University Registration). The Smart Router will automatically connect you with the specialized Agent (Permit, Student, or Legal) and set up the localized context for your specific needs.',
    help_faq_q2: 'Why does the Business Agent ask for my district and business type?',
    help_faq_a2: 'Bureaucratic requirements in Turkey vary heavily by municipality (ilçe) and sector (NACE code). By providing this information, our Context Engine ensures the AI fetches the exact municipal guidelines and tax rules applicable to your specific situation.',
    help_faq_q3: 'Can the AI generate official forms and documents for me?',
    help_faq_a3: 'Yes! The Agents provide step-by-step roadmaps and can guide you through preparing documents for e-Devlet, Göç İdaresi (Residence Permits), and MERSİS (Company Formation). However, you must still officially submit these documents to the government yourself.',
    help_faq_q4: "How accurate is the Legal Agent's advice?",
    help_faq_a4: 'The Legal Agent is trained on up-to-date Turkish Commercial Code and Labor Laws. While it provides excellent foundational guidance and contract review, it does not replace a licensed attorney for official court proceedings or binding legal representation.',
    help_faq_q5: 'How do I change the language of the AI responses?',
    help_faq_a5: 'You can change the interface language using the globe icon in the navigation bar. The Smart Router will automatically instruct the AI to respond in your selected language (English, Turkish, or Arabic), utilizing our localized prompt caching system.',
    help_faq_q6: 'Is my conversation history saved securely?',
    help_faq_a6: 'Yes. Your active sessions are stored locally in your browser to maintain context. If you clear your browser data or delete the session from the sidebar, the conversational memory for that session will be permanently erased.',
    help_still_questions: 'Still have questions?',
    help_support_desc: 'Our support team is available 24/7 to help you navigate municipal complexities.',
    help_email_support: 'Email Support',
    help_ask_ai: 'Ask the AI Assistant',
    download_hero1: 'Your AI Agent,',
    download_hero2: 'Native on Desktop.',
    download_desc: 'Experience the full power of TurkGateway directly from your Desktop. Faster responses, dedicated window, and seamless background operations for Windows, Mac, and Linux.',
    download_feat1_title: 'Native Performance',
    download_feat1_desc: 'Runs outside the browser with dedicated resources for faster AI.',
    download_feat2_title: 'Local Processing',
    download_feat2_desc: 'Embedded local backend keeps sensitive documents offline.',
    download_feat3_title: 'Auto-Updates',
    download_feat3_desc: 'Silent background updates keep you on the latest version.',
    docs_back: 'Back to Help Center',
    docs_title: 'TurkGateway AI Infrastructure',
    docs_subtitle: 'Explore the technical architecture, routing mechanisms, and data pipelines powering our specialized Agentic AI platform for Turkish bureaucracy.',
    docs_sec_architecture: 'System Architecture',
    docs_sec_router: 'Smart Router & Context',
    docs_sec_permit: 'Business Agent',
    docs_sec_student: 'Student Agent',
    docs_sec_legal: 'Legal Agent',
    docs_sec_terms: 'Terms of Service',
    docs_sec_privacy: 'Privacy Policy',
    docs_sec_resources: 'Resource Center',
  },
  tr: {
    navbar_home: 'Ana Sayfa',
    navbar_chat: 'AI Agents',
    navbar_dashboard: 'Dashboard',
    navbar_get_started: 'Başla',
    home_hero_title: 'Türkiye\'de İş, Hukuk ve Eğitim İçin AI Platformu.',
    home_hero_subtitle: 'İzinler, hukuki protokoller ve üniversite kayıt süreçlerinde kolayca ilerleyin. Uzman ajanlarımız, size özel yol haritanızı anında oluşturur.',
    home_hero_greeting_user: 'Selam Hamza',
    home_hero_question: 'Nereden başlayalım?',
    home_hero_cta: 'Başla',
    hero_cat_upload: 'Belge yükle',
    hero_cat_status: 'Durumu kontrol et',
    hero_cat_protocols: 'Belediye protokolleri',
    hero_cat_safety: 'Yangın güvenliği rehberi',
    how_it_works_label: 'Nasıl çalışır',
    process_title: 'Yapay Zeka Süreci',
    process_subtitle: 'Ağır bürokratik işlemleri Yapay Zeka Ajanlarımıza bırakın.',
    process_step1_title: 'Tarif Et',
    process_step1_desc: 'İşletmenizi, hukuki sorununuzu veya üniversite hedeflerinizi kendi kelimelerinizle anlatın. Yapay zekamız yerel mevzuatları anında kavrar.',
    process_step2_title: 'Analiz Et',
    process_step2_desc: 'Uzman AI ajanlarımız, size özel yol haritasını çıkarmak için belediye protokollerini, yasaları ve akademik yönergeleri tarar.',
    process_step3_title: 'Uygula',
    process_step3_desc: 'e-Devlet işlemlerinden kimlik yenilemeye ve üniversite kayıtlarına kadar her adımı planlıyoruz; böylece bürokrasiyle uğraşmadan hedeflerinize odaklanabilirsiniz.',
    dashboard_title: 'İşletme Paneli',
    dashboard_sync: 'Senkronize Et',
    dashboard_ask_ai: 'AI\'ya Sor',
    dashboard_upload: 'Belge Yükle',
    chat_placeholder: 'TurkGateway AI ajanlarına sorun...',
    chat_new: 'Yeni Sohbet',
    chat_greeting: 'Selam.',
    chat_subtitle: 'Bugün İstanbul izinleri konusunda nasıl yardımcı olabilirim?',
    chat_q1: 'İstanbul\'da restoran için hangi izinlere ihtiyacım var?',
    chat_q2: 'Yangın güvenliği denetimi ne kadar sürer?',
    chat_q3: 'Belediye hangi belgeleri istiyor?',
    chat_q4: 'Yangın güvenlik sertifikasının maliyeti nedir?',
    dashboard_updated: 'Güncellendi',
    dashboard_live_session: 'Canlı Oturum',
    dashboard_days: 'gün',
    dashboard_active: 'aktif',
    dashboard_running: 'Çalışıyor',
    dashboard_stopped: 'Durduruldu',
    dashboard_agent_status: 'Ajan iş akışını işliyor',
    dashboard_ask_ai_step: 'Bu adım hakkında AI\'ya sor',
    dashboard_no_session: 'Aktif oturum yok',
    dashboard_processing: 'İşleniyor...',
    dashboard_compliance_score: 'Uyum Skoru',
    dashboard_auto_execute: 'Botu Otomatik Çalıştır',
    dashboard_steps_complete: 'Tamamlanan Adımlar',
    dashboard_est_days: 'Tahmini Kalan Gün',
    dashboard_active_agents: 'Aktif AI Ajanları',
    dashboard_overall_progress: 'Genel İlerleme',
    dashboard_workflow_steps: 'İş Akışı Adımları',
    dashboard_roadmap: 'YOL HARİTASI',
    agent_badge: 'Ajan',
    dashboard_action_required: 'Eylem Gerekiyor',
    dashboard_all_clear: 'Her şey yolunda',
    dashboard_action_required_desc: 'Lütfen devam etmek için {step} adımını tamamlayın.',
    dashboard_bot_processing: 'Sistem şu anda ajan görevlerini işliyor.',
    dashboard_whats_next: 'Sıradaki ne?',
    dashboard_next_step_desc: 'Başlangıç belgeleriniz onaylandıktan sonra, nihai İşyeri Açma ve Çalışma Ruhsatınız işleme alınacaktır.',
    dashboard_init_title: 'İş Akışını Başlat',
    dashboard_init_summary: 'İzin planınızı oluşturmak için bir sohbet başlatın.',
    dashboard_init_detail: 'Sohbet kısmında işinizi tarif ettiğinizde, yapay zeka size özel izin yolunu burada oluşturacaktır.',
    dashboard_mark_complete: 'Tamamlandı Olarak İşaretle',
    dashboard_mark_done: 'Adımı tamamlandı işaretle',
    dashboard_syncing: 'Yerel Belediye ile senkronize ediliyor...',
    dashboard_toast_success: 'Belge başarıyla yüklendi!',
    status_completed: 'Tamamlandı',
    status_in_progress: 'Devam Ediyor',
    status_pending: 'Beklemede',
    chat_welcome: 'Selam {name}',
    chat_begin: 'Nereden başlayalım?',
    chat_placeholder_permit: 'Ruhsat ajanınıza sorun...',
    chat_placeholder_student: 'Öğrenci ajanınıza sorun...',
    chat_placeholder_lawyer: 'Hukuk ajanınıza sorun...',
    chat_suggestion_business: 'İşletme Aç',
    chat_suggestion_permit: 'İzin Al',
    chat_suggestion_location: 'İlçe Kuralları',
    chat_suggestion_duration: 'Süreler',
    chat_suggestion_cost: 'Maliyetler',
    chat_suggestion_obtain: 'Ruhsat Al',
    chat_suggestion_steps: 'Adımları Gör',
    chat_suggestion_docs: 'Belgeler',
    chat_suggestion_help: 'Nasıl Çalışır?',
    chat_ask_placeholder: 'Her şeyi sor',
    chat_voice: 'Sesli',
    chat_listening: 'Dinleniyor...',
    sidebar_new_chat: 'Yeni Sohbet',
    sidebar_recent: 'Geçmiş',
    sidebar_help: 'Yardım',
    sidebar_activity: 'Etkinlik',
    sidebar_settings: 'Ayarlar',
    navbar_pricing: 'Fiyatlandırma',
    navbar_services: 'Hizmetler',
    navbar_download: 'İndir',
    sidebar_upgrade: 'Yükselt',
    sidebar_home: 'Ana Sayfa',
    sidebar_dashboard: 'Dashboard',
    sidebar_my_stuff: 'Benimkiler',
    sidebar_favorites: 'Favoriler',
    sidebar_no_favorites: 'Henüz favori yok',
    sidebar_gems: 'Cevherler',
    sidebar_logout: 'Çıkış Yap',
    navbar_logout: 'Çıkış Yap',
    navbar_login: 'Giriş Yap',
    navbar_signup: 'Üye Ol',
    navbar_subscribers: 'Aboneler',
    dashboard_no_permits: 'Aktif izin bulunamadı',
    sidebar_switch_assistant: 'Asistanı Değiştir',
    sidebar_sign_in_prompt: 'Sohbetlerinizi kaydetmek için giriş yapın',
    sidebar_sign_in_desc: 'Giriş yaptıktan sonra geçmiş sohbetlerinize buradan erişebilirsiniz.',

    help_title: 'Yardım Merkezi',
    help_faq: 'SSS',
    help_contact: 'Destekle İletişime Geç',
    help_docs: 'Dokümantasyon',
    help_feedback: 'Geri Bildirim Gönder',
    help_search: 'Yardım ara...',
    home_stat_districts: 'Kapsanan İlçe',
    home_stat_types: 'İzin Türü',
    home_stat_time: 'Zaman Tasarrufu',
    home_stat_success: 'Başarı Oranı',
    home_feature_agents: 'Çoklu Ajan Yapay Zeka',
    home_feature_agents_desc: 'LangGraph orkestrasyonlu ajanlar; planlama, sınıflandırma ve uyum kontrollerini paralel yürütür.',
    home_feature_districts: 'Tüm 39 İlçe',
    home_feature_districts_desc: 'Tüm İstanbul kapsamı — yerel protokolleri olan 39 belediyenin tamamını destekler.',
    home_feature_tracking: 'Gerçek Zamanlı Takip',
    home_feature_tracking_desc: 'İzin başvurunuzun her adımı takip edilir. Hiçbir detay gözden kaçmaz.',
    home_step1_title: 'İşletmenizden bahsedin',
    home_step1_desc: 'İşletme türünüz, konumunuz ve kapsamınız hakkında birkaç soruyu yanıtlayın.',
    home_step2_title: 'AI izin yolunuzu haritalar',
    home_step2_desc: 'Ajan sistemimiz, durumunuz için gerekli her izni ve belgeyi tanımlar.',
    home_step3_title: 'Belgeleri yükleyin',
    home_step3_desc: 'Kontrol listeleri ve şablonlarla her gerekli belgede size rehberlik ediyoruz.',
    home_step4_title: 'Onayınızı alın',
    home_step4_desc: 'Her onayı gerçek zamanlı takip edin. Belediye bazlı tahmini süreler.',
    dashboard_toast_success_payment: 'Abonelik aktif edildi! Premium\'a hoş geldiniz.',
    dashboard_toast_error_payment: 'Ödeme başarısız. Lütfen tekrar deneyin.',
    dashboard_toast_error_sub: 'Abonelik başlatılamadı',
    assistant_permit: 'Başvuru',
    assistant_student: 'Öğrenci',
    assistant_lawyer: 'Avukat',
    dashboard_student_title: 'Öğrenci Paneli',
    dashboard_legal_title: 'Avukat Paneli',
    dashboard_free_plan: 'Ücretsiz Plan',
    dashboard_premium: 'Premium',
    dashboard_upgrade: 'Yükselt',
    dashboard_starting: 'Başlatılıyor...',
    dashboard_integration: 'Entegrasyonu',
    dashboard_simulating: 'Yerel Belediye API\'sı Simüle Ediliyor...',
    loading_preparing: 'AI Protokol Motoru Başlatılıyor...',
    loading_verifying: 'e-Devlet ile kimlik bilgileri doğrulanıyor...',
    loading_analyzing: 'İlçe protokolleri analiz ediliyor...',
    loading_building: 'Özel yol haritanız oluşturuluyor...',
    loading_finalizing: 'Senkronizasyon tamamlanıyor...',
    dashboard_rpa_desc: 'RPA botumuz, {url} adresine giriş yapmak ve doğrulanan belgeleri adınıza otomatik olarak göndermek için kimlik bilgilerinize ihtiyaç duyar.',
    dashboard_id_label: 'T.C. Kimlik No',
    dashboard_password_label: 'Şifre',
    dashboard_id_placeholder: '11 haneli kimlik numarası',
    dashboard_password_placeholder: '••••••••••••',
    dashboard_disabled_law: 'YASAL ONAY ALINANA KADAR DEVRE DIŞI',
    dashboard_privacy_notice: 'Kimlik bilgileriniz yalnızca bu oturum için kullanılır ve asla veritabanımıza kaydedilmez.',
    auth_login_title: 'Tekrar Hoş Geldiniz',
    auth_login_subtitle: 'Kişiselleştirilmiş TurkGateway AI Ajanlarınıza erişin.',
    auth_signup_title: 'Hesap Oluştur',
    auth_signup_subtitle: 'TurkGateway AI Ajanları ile yolculuğunuza başlayın.',
    auth_email: 'E-posta adresi',
    auth_password: 'Şifre',
    auth_full_name: 'Ad Soyad',
    auth_forgot_password: 'Şifremi unuttum?',
    auth_no_account: 'Hesabınız yok mu?',
    auth_has_account: 'Zaten hesabınız var mı?',
    auth_signing_in: 'Giriş yapılıyor...',
    auth_signing_up: 'Hesap oluşturuluyor...',
    auth_enter_password: 'Şifrenizi girin',
    auth_email_not_found: 'TurkGateway Hesabınız bulunamadı',
    chat_switch_assistant: 'AJAN SEÇİMİ',
    chat_permit_desc: 'İşletme ve Belediye Protokolü',
    chat_student_desc: 'Akademik Görevler ve Kimlik Yenileme',
    chat_lawyer_desc: 'Hukuki Ajanlık ve Uyum',
    chat_sug_renew: 'Kimlik Yenileme',
    chat_sug_uni: 'En İyi Üniversiteler',
    chat_sug_roadmap: 'Kayıt Yol Haritası',
    chat_sug_deadlines: 'Son Tarihler',
    chat_sug_visas: 'Öğrenci Vizeleri',
    chat_sug_shelp: 'Öğrenci Yardımı',
    chat_sug_contract: 'Sözleşme İncelemesi',
    chat_sug_formation: 'Şirket Kurulumu',
    chat_sug_employ: 'İş Hukuku',
    chat_sug_times: 'Yasal Süreler',
    chat_sug_resid: 'İkamet/İzin',
    chat_sug_dispute: 'Hukuki Uyuşmazlıklar',
    pricing_title: 'Basit, şeffaf fiyatlandırma',
    pricing_subtitle: 'Ücretsiz başlayın. Ölçeklenen uyumluluk otomasyonuna ihtiyaç duyduğunuzda yükseltin.',
    pricing_monthly: 'Aylık',
    pricing_annual: 'Yıllık',
    pricing_save: 'Yılda {amount} tasarruf edin',
    pricing_free_desc: 'İzin gereksinimlerini keşfeden bireyler için. Kredi kartı gerekmez.',
    pricing_premium_desc: 'İstanbul\'da ölçekli uyumluluk yöneten işletmeler için tam kapasite.',
    pricing_current: 'Mevcut Plan',
    pricing_upgrade: 'Premium sürümüne geç',
    quota_reached_title: 'Model kotasına ulaşıldı',
    quota_reached_desc: "Planınızın temel kotası tükendi. Devam etmek için lütfen yenilenmesini bekleyin veya yükseltin.",
    quota_refresh_msg: "Planınızın temel kotası şu tarihte yenilenecek:",
    quota_dismiss: 'Kapat',
    tokens_unit: 'Token',
    pricing_most_popular: 'En Popüler',
    pricing_compare: 'Planları karşılaştırın',
    pricing_compare_subtitle: 'Doğru kararı vermek için ihtiyacınız olan her şey.',
    pricing_faq_title: 'Sıkça sorulan sorular',
    pricing_faq_subtitle: 'Burada listelenmeyen bir sorunuz mu var?',
    pricing_contact_us: 'Bize ulaşın',
    pricing_cta_title: 'Uyumluluğunuzu kolaylaştırmaya hazır mısınız?',
    pricing_cta_subtitle: 'Mevzuat iş akışlarını otomatikleştirmek için TurkGateway kullanan İstanbul genelindeki işletmelere katılın.',
    pricing_secure_checkout: 'iyzico üzerinden güvenli ödeme',
    pricing_cancel_anytime: 'İstediğiniz zaman iptal edin',
    pricing_vat_included: 'KDV dahil fatura',
    pricing_feat_ai: 'AI İzin Ajanlığı',
    pricing_feat_sessions: 'Aktif Oturumlar',
    pricing_feat_history: 'Proje Geçmişi',
    pricing_feat_docs: 'Belge Yönetimi',
    pricing_feat_priority: 'Öncelikli Temsilci İş Akışları',
    pricing_feat_support: 'Bire Bir Mevzuat Desteği',
    pricing_feat_access: 'Yeni Düzenlemelere Erken Erişim',
    pricing_feat_multi: 'Çoklu Dil Desteği (TR/EN/AR)',
    pricing_feat_comm: 'Topluluk Erişimi',
    pricing_feat_limited: 'Sınırlı',
    pricing_feat_unlimited: 'Sınırsız',
    pricing_feat_7days: '7 gün',
    pricing_faq_q1: 'Aboneliğimi istediğim zaman iptal edebilir miyim?',
    pricing_faq_a1: 'Evet. Premium aboneliğinizi hesap ayarlarınızdan istediğiniz zaman iptal edebilirsiniz. Mevcut faturalandırma döneminizin sonuna kadar erişiminizi sürdürürsünüz.',
    pricing_faq_q2: 'Ödeme bilgilerim güvende mi?',
    pricing_faq_a2: 'Tüm ödemeler, PCI-DSS Seviye 1 sertifikalı bir ödeme sağlayıcısı olan iyzico tarafından işlenir. Kart bilgilerinizi asla sunucularımızda saklamayız.',
    pricing_faq_q3: 'Ücretsizden Premium\'a yükselttiğimde ne olur?',
    pricing_faq_a3: 'Hesabınız anında yükseltilir. Tüm sınırlar kaldırılır ve ödeme onayından hemen sonra öncelikli özellikler kullanılabilir hale gelir.',
    pricing_faq_q4: 'İşletme muhasebesi için fatura sunuyor musunuz?',
    pricing_faq_a4: 'Evet. Her başarılı ödemeden sonra iyzico aracılığıyla otomatik olarak KDV uyumlu bir fatura kesilir ve hesabınızdan indirilebilir.',
    pricing_trust_enc: 'Banka düzeyinde şifreleme',
    pricing_trust_pci: 'PCI-DSS Uyumlu',
    pricing_trust_supp: 'Öncelikli destek',
    pricing_trust_resp: 'ort. 2 saat yanıt',
    pricing_trust_cancel: 'İstediğiniz zaman iptal edin',
    pricing_trust_lockin: 'Taahhüt yok',
    pricing_get_started: 'Premium ile başlayın',
    pricing_ready: 'Uyumluluğunuzu kolaylaştırmaya hazır mısınız?',
    connect_in: 'İçinde',
    agent_name: 'TurkGateway Yapay Zeka Ajanı',
    agent_thinking: 'Ajan düşünüyor...',
    footer_version: 'Belediye Protokol Motoru • v2.5',
    dist_adalar: 'Adalar', dist_arnavutkoy: 'Arnavutköy', dist_atasehir: 'Ataşehir', dist_avcilar: 'Avcılar', dist_bagcilar: 'Bağcılar',
    dist_bahcelievler: 'Bahçelievler', dist_bakirkoy: 'Bakırköy', dist_basaksehir: 'Başakşehir', dist_bayrampasa: 'Bayrampaşa', dist_besiktas: 'Beşiktaş',
    dist_beykoz: 'Beykoz', dist_beylikduzu: 'Beylikdüzü', dist_beyoglu: 'Beyoğlu', dist_buyukcekmece: 'Büyükçekmece', dist_catalca: 'Çatalca',
    dist_cekmekoy: 'Çekmeköy', dist_esenler: 'Esenler', dist_esenyurt: 'Esenyurt', dist_eyupsultan: 'Eyüpsultan', dist_fatih: 'Fatih',
    dist_gaziosmanpasa: 'Gaziosmanpaşa', dist_gungoren: 'Güngören', dist_kadikoy: 'Kadıköy', dist_kagithane: 'Kağıthane', dist_kartal: 'Kartal',
    dist_kucukcekmece: 'Küçükçekmece', dist_maltepe: 'Maltepe', dist_pendik: 'Pendik', dist_sancaktepe: 'Sancaktepe', dist_sariyer: 'Sarıyer',
    dist_sile: 'Şile', dist_silivri: 'Silivri', dist_sisli: 'Şişli', dist_sultanbeyli: 'Sultanbeyli', dist_sultangazi: 'Sultangazi',
    dist_tuzla: 'Tuzla', dist_umraniye: 'Ümraniye', dist_uskudar: 'Üsküdar', dist_zeytinburnu: 'Zeytinburnu',
    biz_restaurant: 'Restoran', biz_cafe: 'Kafe', biz_retail: 'Perakende Mağaza', biz_office: 'Ofis', biz_pharmacy: 'Eczane',
    biz_bakery: 'Fırın', biz_barber: 'Berber', biz_gym: 'Spor Salonu', biz_shop: 'Dükkan', biz_store: 'Mağaza', biz_company: 'Şirket',
    biz_clothing: 'Giyim Mağazası', biz_hotel: 'Otel', biz_clinic: 'Klinik', biz_school: 'Okul',
    settings_title: 'Ayarlar',
    settings_appearance: 'Görünüm',
    settings_profile: 'Profil',
    settings_history: 'Sohbet Geçmişi',
    settings_security_title: 'Güvenlik ve Gizlilik',
    settings_theme: 'Tema',
    settings_lang: 'Dil',
    settings_2fa_title: 'İki Faktörlü Doğrulama',
    settings_2fa_desc: 'Hesabınıza ekstra bir güvenlik katmanı ekleyin.',
    settings_2fa_enable: '2FA\'yı Etkinleştir',
    settings_sessions_title: 'Aktif Oturumlar',
    settings_sessions_desc: 'Diğer aktif oturumları yönetin ve çıkış yapın.',
    settings_sessions_logout: 'Diğer oturumlardan çıkış yap',
    settings_danger_zone: 'Tehlikeli Bölge',
    settings_delete_desc: 'Hesabınızı sildiğinizde geri dönüş yoktur. Lütfen emin olun.',
    settings_delete_account: 'Hesabı Sil',
    settings_delete_confirm: 'HESAP SİLMEYİ ONAYLAMAK İÇİN "SİL" YAZIN',
    settings_delete_yes: 'Evet, hesabımı sil',
    settings_confirm_clear: 'Evet, geçmişi temizle',
    settings_cancel: 'İptal',
    settings_clear_history: 'Geçmişi Temizle',
    scroll_right: 'Sağa Kaydır',
    click_to_flip: 'Görmek için dokun',
    auth_terms: 'Şartlar',
    auth_privacy: 'Gizlilik',
    auth_help: 'Yardım',
    footer_english: 'İngilizce',
    footer_turkish: 'Türkçe',
    footer_arabic: 'Arapça',
    auth_login_header: 'Oturum açın',
    auth_login_subheader: 'TurkGateway Hesabınızı kullanın',
    auth_forgot_email: 'E-postanızı mı unuttunuz?',
    auth_guest_notice: 'Size ait olmayan bir bilgisayar mı kullanıyorsunuz? Gizli oturum açmak için Misafir modunu kullanın.',
    auth_learn_more: 'Misafir modunu kullanma hakkında daha fazla bilgi edinin',
    auth_next: 'Sonraki',
    auth_change_email: 'E-postayı değiştir',
    auth_signup_header: 'Hesap oluşturun',
    auth_signup_subheader: 'TurkGateway\'e devam etmek için',
    auth_signin_instead: 'Bunun yerine oturum açın',
    auth_sign_in_as: 'Şu kişi olarak oturum aç',
    services_title: 'AI Ajanlarını Keşfedin',
    services_subtitle: 'Profesyonel AI desteği ile idari yolculuğunuzu ölçeklendirin.',
    services_permit_desc: 'İşletme ruhsatları, perakende izinleri ve endüstriyel uyum kurulumu.',
    services_student_desc: 'Üniversite kaydı, ikamet izinleri ve öğrenci yenilemeleri.',
    services_lawyer_desc: 'Profesyonel hukuki yardım ve uyum doğrulamaları.',
    services_feat_retail: 'Perakende kuruluş izinleri',
    services_feat_restaurant: 'Restoran ve Kafe Ruhsatlandırma',
    services_feat_fire: 'Yangın güvenliği uyumu',
    services_feat_municipal: 'Belediye protokolleri',
    services_feat_uni: 'Üniversite kaydı',
    services_feat_visa: 'Öğrenci vizesi başvurusu',
    services_feat_kimlik: 'Kimlik alma ve yenileme (Kimlik)',
    services_feat_nufus: 'Nüfus kaydı (Adres kaydı)',
    services_feat_contract: 'Sözleşme incelemesi',
    services_feat_formation: 'Şirket kurulumu',
    services_feat_disputes: 'Hukuki uyuşmazlıklar',
    services_feat_compliance: 'Uyum kontrolleri',
    services_status_available: 'Mevcut',
    services_status_active: 'Aktif',
    services_status_waitlist: 'Bekleme Listesi',
    services_status_soon: 'Yakında',
    services_cta_describe: 'Neye ihtiyacınız olduğunu belirtin',
    services_ai_does_work: 'AI işi yapar',
    services_ai_desc: 'TurkGateway her adımda çalışır, önemli bir şeyden önce sizi bilgilendirir. Gerçek zamanlı izleyin veya ayrılın.',
    services_control_title: 'Kontrol sizde',
    services_control_desc: 'TurkGateway\'in hangi portallara ve veritabanlarına erişebileceğini siz seçersiniz.',
    services_encryption: 'Uçtan Uca Şifreleme',
    services_privacy: 'Önce Gizlilik',
    services_allow_files: 'Ajana dosyaları değiştirme izni verilsin mi?',
    services_allow_desc: 'Bu, belediye formlarını ve e-Devlet indirmelerini içerir. Ajan dosyaları okuyabilir, düzenleyebilir ve geçici olarak saklayabilir.',
    services_allow_access: 'Erişime İzin Ver',
    services_always_allow: 'Her Zaman İzin Ver',
    services_list_title: 'Listenizden bir şeyler eksiltelim',
    services_task_tax: 'Vergi Uyumu',
    services_task_register: 'Şirket Kurulumu',
    services_task_enroll: 'Üniversite Kaydı',
    services_task_permit: 'Çalışma İzni Al',
    services_task_legal: 'Hukuki Ajanlık',
    services_task_renewal: 'Kimlik Yenileme',
    services_cta_title: 'Neye ihtiyacınız olduğunu anlatın',
    services_cta_desc: 'TurkGateway\'e neyi başarmak istediğinizi söyleyin. Ajanlarımız en hızlı yolu seçer: devlet portallarına, belediye API\'lerine bağlanmak veya belgelerinizi anında işlemek için gelişmiş OCR kullanmak.',
    services_launch_agent: 'Ajanı Başlat',
    services_chat_greeting: 'Bugün size nasıl yardımcı olabilirim?',
    services_setup_agent: 'Ajanı Ayarla',
    services_start_agent: 'Ajanı Başlat',
    services_type_service: 'Hizmet Türü',
    services_select_service: 'Hizmet Seçin',
    services_select_uni: 'Üniversite Seçin',
    services_select_uni_placeholder: 'Bir Üniversite Seçin',
    services_district: 'İstanbul İlçesi',
    services_select_district: 'İlçe Seçin',
    services_secure_session: 'Güvenli 256-bit Şifreli Oturum',
    services_res_register: 'Harika. Hukuk Ajanını başlattım. Limited şirket kurulum yol haritanızı oluşturmak için MERSİS portalına bağlanıyorum. İşte ilk adımlar...',
    services_res_tax: 'En son VDK kurumlar vergisi kontrol listelerini alıyorum ve dijital işletmeniz için otomatik bir denetim protokolü oluşturuyorum.',
    services_res_permit: 'İzin Ajanı başlatılıyor. Mevcut kota muafiyetlerini ve işveren gereksinimlerini almak için Çalışma Bakanlığı portalına bağlanıyorum.',
    services_res_enroll: 'Öğrenci Ajanı başlatıldı. Koç Üniversitesi için özel YÖK gereksinimlerini ve ikamet izni belge listenizi alıyorum.',
    services_res_renewal: 'e-ikamet uzatma başvurusunda size rehberlik edeceğim. Mevcut izin durumunuzu doğrulamak için GÖÇ İdaresi API\'sine bağlanıyorum...',
    services_res_legal: 'Hukuk Ajanı kontrol ediyor. Ticari sözleşmeniz için bir inceleme standardı oluşturmak amacıyla Türk Ticaret Kanunu çerçevesine eriştim.',
    services_prompt_register: 'Türkiye\'de yeni bir limited şirket açmak istiyorum. Yasal gereklilikler ve adımlar nelerdir?',
    services_prompt_tax: 'Dijital işletmemin Türk kurumlar vergisiyle tam uyumlu olduğundan emin olmam gerekiyor.',
    services_prompt_permit: 'İstanbul\'daki yabancı bir çalışan için çalışma izni başvurusu yapmak istiyorum.',
    services_prompt_enroll: 'Koç Üniversitesi\'ne kaydolmak ve öğrenci vizesi başvurusu yapmak için yardıma ihtiyacım var.',
    services_prompt_renewal: 'e-ikametim (ikamet iznim) gelecek ay sona eriyor, nasıl yenilerim?',
    services_prompt_legal: 'Türk ticaret hukuku kapsamında uluslararası bir ticaret sözleşmesini incelemek istiyorum.',
    guest_modal_title: "TurkGateWay'i denediğiniz için teşekkürler",
    guest_modal_desc: "Daha akıllı yanıtlar almak, yol haritalarının kilidini açmak ve daha fazlası için giriş yapın veya kaydolun.",
    login: "Giriş yap",
    signup_free: "Ücretsiz üye ol",
    stay_logged_out: "Oturum açmadan devam et",
    chat_tab_suggested: 'Önerilen',
    chat_tab_chat: 'Sohbet',
    chip_cafe_restaurant: 'Kafe & Restoran',
    chip_retail_shop: 'Perakende Mağaza',
    chip_office_tech: 'Ofis & Teknoloji',
    chip_pharmacy: 'Eczane',
    chip_clinic: 'Klinik',
    chip_residence_permit: 'İkamet İzni',
    chip_uni_reg: 'Üniversite Kaydı',
    chip_ikamet: 'Kimlik / İkamet',
    chip_denklik: 'Denklik (Eşdeğerlik)',
    chip_dormitory: 'Yurt & Konaklama',
    chip_student_visa: 'Öğrenci Vizesi',
    chip_istanbul_kart: 'İstanbulKart',
    chip_company_formation: 'Şirket Kurulumu',
    chip_contract_review: 'Sözleşme İncelemesi',
    chip_employment_law: 'İş Hukuku',
    chip_legal_disputes: 'Hukuki Uyuşmazlıklar',
    chip_residency_visas: 'İkamet & Vize',
    chip_real_estate: 'Gayrimenkul Hukuku',
    help_hero: 'Size nasıl yardımcı olabiliriz?',
    help_cat_docs_title: 'Dokümantasyon',
    help_cat_docs_desc: 'İşletme izinleri, öğrenciler ve avukat protokolleri için ayrıntılı kılavuzlar',
    help_cat_community_title: 'Topluluk',
    help_cat_community_desc: "İstanbul'daki 10.000+ işletme ve öğrenciye katılın",
    help_cat_resources_title: 'Kaynak Merkezi',
    help_cat_resources_desc: 'Kontrol listeleri, yasalar ve PDF şablonları',
    help_explore: 'Keşfet',
    help_faq_q1: 'Bir AI Ajanıyla nasıl yeni oturum başlatırım?',
    help_faq_a1: "Hizmetler sayfasına gidin ve hedefinizi seçin (ör. İşletme Açma, Üniversite Kaydı). Akıllı Yönlendirici sizi otomatik olarak ilgili Ajanla (İzin, Öğrenci veya Hukuk) bağlayacak ve özel ihtiyaçlarınız için yerelleştirilmiş bağlamı ayarlayacaktır.",
    help_faq_q2: 'İşletme Ajanı neden bölgemi ve işletme türümü soruyor?',
    help_faq_a2: "Türkiye'deki bürokratik gereksinimler belediyeye (ilçe) ve sektöre (NACE kodu) göre büyük farklılıklar gösterir. Bu bilgiyi sağlayarak Bağlam Motorumuz, AI'nın durumunuza özgü tam belediye yönergelerini ve vergi kurallarını getirmesini sağlar.",
    help_faq_q3: 'AI benim için resmi form ve belgeler oluşturabilir mi?',
    help_faq_a3: "Evet! Ajanlar adım adım yol haritaları sunar ve e-Devlet, Göç İdaresi (İkamet İzinleri) ve MERSİS (Şirket Kuruluşu) için belge hazırlamanızda size rehberlik edebilir. Ancak bu belgeleri hükümete resmi olarak kendiniz sunmanız gerekir.",
    help_faq_q4: 'Hukuk Ajanının tavsiyeleri ne kadar doğru?',
    help_faq_a4: "Hukuk Ajanı güncel Türk Ticaret Kanunu ve İş Hukuku üzerine eğitilmiştir. Mükemmel temel rehberlik ve sözleşme incelemesi sunarken, resmi mahkeme işlemleri veya bağlayıcı hukuki temsil için lisanslı bir avukatın yerini almaz.",
    help_faq_q5: 'AI yanıtlarının dilini nasıl değiştirebilirim?',
    help_faq_a5: 'Gezinme çubuğundaki küre simgesini kullanarak arayüz dilini değiştirebilirsiniz. Akıllı Yönlendirici, yerelleştirilmiş önbellek sistemimizi kullanarak AI\'ya seçtiğiniz dilde (İngilizce, Türkçe veya Arapça) yanıt vermesini otomatik olarak talimat verecektir.',
    help_faq_q6: 'Konuşma geçmişim güvenli bir şekilde kaydediliyor mu?',
    help_faq_a6: 'Evet. Aktif oturumlarınız bağlamı korumak için tarayıcınızda yerel olarak saklanır. Tarayıcı verilerinizi temizlerseniz veya kenar çubuğundan oturumu silerseniz, o oturumun konuşma belleği kalıcı olarak silinecektir.',
    help_still_questions: 'Hâlâ sorunuz mu var?',
    help_support_desc: 'Destek ekibimiz, belediye karmaşıklıklarında size yardımcı olmak için 7/24 hizmetinizdedir.',
    help_email_support: 'E-posta Desteği',
    help_ask_ai: 'AI Asistanına Sor',
    download_hero1: 'AI Ajanınız,',
    download_hero2: "Masaüstünde.",
    download_desc: "TurkGateway'in tüm gücünü doğrudan Masaüstünüzden deneyimleyin. Windows, Mac ve Linux için daha hızlı yanıtlar, özel pencere ve kesintisiz arka plan işlemleri.",
    download_feat1_title: 'Yerel Performans',
    download_feat1_desc: 'Daha hızlı AI için özel kaynaklarla tarayıcı dışında çalışır.',
    download_feat2_title: 'Yerel İşleme',
    download_feat2_desc: 'Gömülü yerel arka uç, hassas belgeleri çevrimdışı tutar.',
    download_feat3_title: 'Otomatik Güncellemeler',
    download_feat3_desc: 'Arka planda sessiz güncellemeler sizi en son sürümde tutar.',
    docs_back: 'Yardım Merkezine Dön',
    docs_title: 'TurkGateway AI Altyapısı',
    docs_subtitle: "Türk bürokratik platformumuzun teknik mimarisini, yönlendirme mekanizmalarını ve veri işlem hatlarını keşfedin.",
    docs_sec_architecture: 'Sistem Mimarisi',
    docs_sec_router: 'Akıllı Yönlendirici & Bağlam',
    docs_sec_permit: 'İşletme Ajanı',
    docs_sec_student: 'Öğrenci Ajanı',
    docs_sec_legal: 'Hukuk Ajanı',
    docs_sec_terms: 'Kullanım Şartları',
    docs_sec_privacy: 'Gizlilik Politikası',
    docs_sec_resources: 'Kaynak Merkezi',
  },
  ar: {
    navbar_home: 'الرئيسية',
    navbar_chat: 'AI Agents',
    navbar_dashboard: 'لوحة التحكم',
    navbar_get_started: 'ابدأ الآن',
    home_hero_title: 'منصة الذكاء الاصطناعي للأعمال والقانون والتعليم في تركيا.',
    home_hero_subtitle: 'تنقل بين التصاريح والبروتوكولات القانونية والتسجيل الجامعي بسهولة. يقوم وكلاؤنا المتخصصون بإنشاء خارطة طريق مخصصة لك في ثوانٍ.',
    home_hero_greeting_user: 'أهلاً حمزة',
    home_hero_question: 'من أين نبدأ؟',
    home_hero_cta: 'ابدأ الآن',
    hero_cat_upload: 'رفع المستندات',
    hero_cat_status: 'تحقق من الحالة',
    hero_cat_protocols: 'بروتوكولات البلدية',
    hero_cat_safety: 'دليل السلامة من الحرائق',
    how_it_works_label: 'كيف يعمل',
    process_title: 'عملية الذكاء الاصطناعي',
    process_subtitle: 'دع وكلاء الذكاء الاصطناعي لدينا يتولون المهام الصعبة نيابة عنك.',
    process_step1_title: 'صف حالتك',
    process_step1_desc: 'أخبرنا عن عملك أو مشكلتك القانونية أو أهدافك الجامعية بلغة بسيطة. يفهم الذكاء الاصطناعي اللوائح والمتطلبات المحلية على الفور.',
    process_step2_title: 'التحليل',
    process_step2_desc: 'يقوم وكلاؤنا المتخصصون بمراجعة بروتوكولات البلدية والقوانين والمبادئ التوجيهية الأكاديمية لبناء خارطة طريقك الدقيقة.',
    process_step3_title: 'التنفيذ',
    process_step3_desc: 'نحن نخطط لكل خطوة—من ملفات e-Devlet وتجديد الهوية إلى التسجيل الجامعي—لتتمكن من التركيز على أهدافك دون صداع بيروقراطي.',
    dashboard_title: 'لوحة الأعمال',
    dashboard_sync: 'مزامنة',
    dashboard_ask_ai: 'اسأل الذكاء الاصطناعي',
    dashboard_upload: 'رفع المستندات',
    chat_placeholder: 'اسأل وكلاء TurkGateway AI...',
    chat_new: 'دردشة جديدة',
    chat_greeting: 'أهلاً بك.',
    chat_subtitle: 'كيف يمكنني مساعدتك في تصاريح إسطنبول اليوم؟',
    chat_q1: 'ما هي التصاريح التي أحتاجها لمطعم في إسطنبول؟',
    chat_q2: 'كم يستغرق فحص السلامة من الحرائق؟',
    chat_q3: 'ما هي المستندات التي تطلبها البلدية؟',
    chat_q4: 'ما هي تكلفة شهادة السلامة من الحرائق؟',
    dashboard_updated: 'تم التحديث',
    dashboard_live_session: 'جلسة مباشرة',
    dashboard_days: 'أيام',
    dashboard_active: 'نشط',
    dashboard_running: 'يعمل',
    dashboard_stopped: 'متوقف',
    dashboard_agent_status: 'الوكيل يعالج سير العمل',
    dashboard_ask_ai_step: 'اسأل الذكاء الاصطناعي عن هذه الخطوة',
    dashboard_no_session: 'لا توجد جلسة نشطة',
    dashboard_processing: 'جاري المعالجة...',
    loading_preparing: 'بدء تشغيل محرك بروتوكول الذكاء الاصطناعي...',
    loading_verifying: 'التحقق من البيانات عبر e-Devlet...',
    loading_analyzing: 'تحليل بروتوكولات البلدية...',
    loading_building: 'بناء خارطة الطريق المخصصة...',
    loading_finalizing: 'إنهاء عملية المزامنة...',
    dashboard_compliance_score: 'درجة الامتثال',
    dashboard_steps_complete: 'الخطوات المكتملة',
    dashboard_est_days: 'الأيام المتبقية المتوقعة',
    dashboard_active_agents: 'وكلاء الذكاء الاصطناعي النشطون',
    dashboard_overall_progress: 'التقدم العام',
    dashboard_workflow_steps: 'خطوات سير العمل',
    dashboard_roadmap: 'خارطة الطريق',
    agent_badge: 'وكيل',
    dashboard_action_required: 'إجراء مطلوب',
    dashboard_all_clear: 'كل شيء جاهز',
    dashboard_action_required_desc: 'يرجى إكمال خطوة {step} للمتابعة.',
    dashboard_bot_processing: 'يقوم النظام حاليًا بمعالجة مهام الوكيل.',
    dashboard_whats_next: 'ماذا بعد؟',
    dashboard_next_step_desc: 'بمجرد الموافقة على مستنداتك الأولية، سيتم تفعيل رخصة فتح وممارسة العمل (İşyeri Açma ve Çalışma Ruhsatı) الخاصة بك.',
    dashboard_init_title: 'بدء سير العمل',
    dashboard_init_summary: 'ابدأ دردشة لإنشاء خطة التصريح الخاصة بك.',
    dashboard_init_detail: 'بمجرد وصف عملك في الدردشة ، سيقوم الذكاء الاصطناعي بإنشاء مسار تصريح مخصص لك هنا.',
    dashboard_mark_complete: 'تحديد كمكتمل',
    dashboard_mark_done: 'حدد الخطوة كمكتملة',
    dashboard_syncing: 'جاري المزامنة مع البلدية المحلية...',
    chat_listening: 'جاري الاستماع...',
    dashboard_toast_success: 'تم رفع المستند بنجاح!',
    status_completed: 'مكتمل',
    status_in_progress: 'قيد التنفيذ',
    status_pending: 'قيد الانتظار',
    dashboard_auto_execute: 'تشغيل البوت تلقائياً',
    chat_welcome: 'أهلاً {name}',
    chat_begin: 'من أين نبدأ؟',
    chat_placeholder_permit: 'اسأل وكيل التراخيص الخاص بك...',
    chat_placeholder_student: 'اسأل وكيل الطلاب الخاص بك...',
    chat_placeholder_lawyer: 'اسأل وكيلك القانوني...',
    chat_switch_assistant: 'اختيار الوكيل',
    chat_suggestion_business: 'فتح عمل',
    chat_suggestion_permit: 'الحصول على تصريح',
    chat_suggestion_location: 'قواعد المنطقة',
    chat_suggestion_duration: 'الجداول الزمنية',
    chat_suggestion_cost: 'التكاليف',
    chat_suggestion_obtain: 'تصريح عمل',
    chat_suggestion_steps: 'الخطوات',
    chat_suggestion_docs: 'المستندات المطلوبة',
    chat_suggestion_help: 'كيف يعمل؟',
    chat_ask_placeholder: 'اسأل عن أي شيء',
    chat_voice: 'صوتي',
    sidebar_new_chat: 'دردشة جديدة',
    sidebar_recent: 'الأخيرة',
    sidebar_help: 'المساعدة',
    sidebar_activity: 'النشاط',
    sidebar_settings: 'الإعدادات',
    navbar_pricing: 'التسعير',
    navbar_services: 'الخدمات',
    navbar_download: 'تحميل',
    sidebar_upgrade: 'ترقية',
    sidebar_home: 'الرئيسية',
    sidebar_dashboard: 'لوحة التحكم',
    sidebar_my_stuff: 'أشيائي',
    sidebar_favorites: 'المفضلة',
    sidebar_no_favorites: 'لا توجد مفضلات بعد',
    sidebar_gems: 'الجواهر',
    sidebar_logout: 'تسجيل الخروج',
    navbar_logout: 'تسجيل الخروج',
    navbar_login: 'تسجيل الدخول',
    navbar_signup: 'إنشاء حساب',
    navbar_subscribers: 'المشتركين',
    dashboard_no_permits: 'لم يتم العثور على تصاريح نشطة',
    sidebar_switch_assistant: 'تبديل المساعد',
    sidebar_sign_in_prompt: 'سجل الدخول لبدء حفظ دردشاتك',
    sidebar_sign_in_desc: 'بمجرد تسجيل الدخول، يمكنك الوصول إلى دردشاتك الأخيرة هنا.',

    help_title: 'مركز المساعدة',
    help_faq: 'الأسئلة الشائعة',
    help_contact: 'الاتصال بالدعم',
    help_docs: 'الوثائق',
    help_feedback: 'إرسال ملاحظات',
    help_search: 'البحث عن مساعدة...',
    home_stat_districts: 'منطقة مشمولة',
    home_stat_types: 'نوع تصريح',
    home_stat_time: 'توفير الوقت',
    home_stat_success: 'معدل النجاح',
    home_feature_agents: 'ذكاء اصطناعي متعدد الوكلاء',
    home_feature_agents_desc: 'يعمل وكلاء LangGraph على التخطيط والتصنيف والتحقق من الامتثال بالتوازي.',
    home_feature_districts: 'جميع المناطق الـ 39',
    home_feature_districts_desc: 'تغطية كاملة لإسطنبول — دعم جميع البلديات الـ 39 مع بروتوكولات محلية متميزة.',
    home_feature_tracking: 'تتبع في الوقت الحقيقي',
    home_feature_tracking_desc: 'تتم متابعة كل خطوة من خطوات طلب التصريح الخاص بك. لا شيء يغيب عن الحسبان.',
    home_step1_title: 'أخبرنا عن عملك',
    home_step1_desc: 'أجب عن بضعة أسئلة حول نوع عملك وموقعه ونطاقه.',
    home_step2_title: 'الذكاء الاصطناعي يرسم مسار التصريح',
    home_step2_desc: 'يحدد نظام الوكلاء لدينا كل تصريح ومستند مطلوب لحالتك.',
    home_step3_title: 'رفع المستندات',
    home_step3_desc: 'نقوم بإرشادك عبر كل مستند مطلوب مع قوائم مراجعة ونماذج.',
    home_step4_title: 'استلم موافقتك',
    home_step4_desc: 'تتبع كل موافقة في الوقت الحقيقي. جداول زمنية تقديرية لكل بلدية.',
    dashboard_toast_success_payment: 'تم تفعيل الاشتراك! أهلاً بك في المميز.',
    dashboard_toast_error_payment: 'فشلت عملية الدفع. يرجى المحاولة مرة أخرى.',
    dashboard_toast_error_sub: 'فشل بدء الاشتراك',
    assistant_permit: 'التراخيص',
    assistant_student: 'الطلاب',
    assistant_lawyer: 'محامي',
    dashboard_free_plan: 'خطة مجانية',
    dashboard_premium: 'مميز',
    dashboard_upgrade: 'ترقية',
    dashboard_starting: 'جاري البدء...',
    dashboard_integration: 'تكامل',
    dashboard_simulating: 'جاري محاكاة نظام البلدية...',
    dashboard_student_title: 'لوحة تحكم الطلاب',
    dashboard_legal_title: 'لوحة تحكم المحامين',
    chat_permit_desc: 'بروتوكول الأعمال والبلدية',
    chat_student_desc: 'المهام الأكاديمية وتجديد الهوية',
    chat_lawyer_desc: 'المشورة القانونية والامتثال',
    chat_sug_renew: 'تجديد الهوية',
    chat_sug_uni: 'أفضل الجامعات',
    chat_sug_roadmap: 'خارطة طريق التسجيل',
    chat_sug_deadlines: 'المواعيد النهائية',
    chat_sug_visas: 'تأشيرات الطلاب',
    chat_sug_shelp: 'مساعدة الطلاب',
    chat_sug_contract: 'مراجعة العقود',
    chat_sug_formation: 'تأسيس الشركات',
    chat_sug_employ: 'قانون العمل',
    chat_sug_times: 'الجداول الزمنية القانونية',
    chat_sug_resid: 'الإقامة/التصريح',
    chat_sug_dispute: 'النزاعات القانونية',
    pricing_title: 'تسعير بسيط وشفاف',
    pricing_subtitle: 'ابدأ مجانًا. قم بالترقية عندما تحتاج إلى أتمتة الامتثال التي تتوسع.',
    pricing_monthly: 'شهرياً',
    pricing_annual: 'سنوياً',
    pricing_save: 'وفر {amount}/سنة',
    pricing_free_desc: 'للأفراد الذين يستكشفون متطلبات التصاريح. لا يلزم وجود بطاقة ائتمان.',
    pricing_premium_desc: 'قدرات كاملة للشركات التي تدير الامتثال على نطاق واسع في إسطنبول.',
    pricing_current: 'الخطة الحالية',
    pricing_upgrade: 'الترقية إلى المميز',
    quota_reached_title: 'تم الوصول إلى حصة النموذج',
    quota_reached_desc: "لقد استنفدت الحصة الأساسية لخطتك. يرجى الانتظار حتى التجديد أو الترقية للمتابعة.",
    quota_refresh_msg: "سيتم تجديد الحصة الأساسية لخطتك في",
    quota_dismiss: 'إغلاق',
    tokens_unit: 'توكنز',
    pricing_most_popular: 'الأكثر شعبية',
    pricing_compare: 'قارن الخطط',
    pricing_compare_subtitle: 'كل ما تحتاجه لاتخاذ القرار الصحيح.',
    pricing_faq_title: 'الأسئلة الشائعة',
    pricing_faq_subtitle: 'هل لديك سؤال غير مدرج هنا؟',
    pricing_contact_us: 'اتصل بنا',
    pricing_cta_title: 'جاهز لتبسيط امتثالك؟',
    pricing_cta_subtitle: 'انضم إلى الشركات في جميع أنحاء إسطنبول التي تستخدم TurkGateway لأتمتة سير عملها التنظيمي.',
    pricing_secure_checkout: 'دفع آمن عبر iyzico',
    pricing_cancel_anytime: 'إلغاء في أي وقت',
    pricing_vat_included: 'فاتورة ضريبة القيمة المضافة متضمنة',
    auth_login_title: 'تسجيل الدخول',
    auth_login_subtitle: 'قم بالوصول إلى وكلاء TurkGateway AI المخصصين لك.',
    auth_email: 'البريد الإلكتروني',
    auth_password: 'كلمة المرور',
    auth_no_account: 'ليس لديك حساب؟',
    auth_has_account: 'لديك حساب بالفعل؟',
    auth_signup_title: 'إنشاء حساب',
    auth_signup_subtitle: 'ابدأ رحلتك مع وكلاء TurkGateway AI.',
    auth_full_name: 'الاسم الكامل',
    auth_signing_in: 'جاري تسجيل الدخول...',
    auth_signing_up: 'جاري إنشاء الحساب...',
    auth_enter_password: 'أدخل كلمة المرور',
    auth_email_not_found: 'لم نتمكن من العثور على حسابك في TurkGateway',
    pricing_billed_as: 'يتم احتساب الفاتورة بقيمة {amount}/سنوياً',
    pricing_billed_monthly: 'يتم احتساب الفاتورة شهرياً',
    pricing_monthly_unit: 'شهر',
    pricing_feat_label: 'الميزة',
    connect_in: 'في',
    agent_name: 'TurkGateway وكيل الذكاء الاصطناعي',
    agent_thinking: 'الوكيل يفكر الآن...',
    footer_version: 'محرك بروتوكول البلدية • v2.5',
    dist_adalar: 'الأميرات', dist_arnavutkoy: 'أرناووط كوي', dist_atasehir: 'أتاشهير', dist_avcilar: 'أفجيلار', dist_bagcilar: 'باغجيلار',
    dist_bahcelievler: 'باهتشيلي ايفلر', dist_bakirkoy: 'بكر كوي', dist_basaksehir: 'باشاك شهير', dist_bayrampasa: 'بايرام باشا', dist_besiktas: 'بشكتاش',
    dist_beykoz: 'بيكوز', dist_beylikduzu: 'بيليك دوزو', dist_beyoglu: 'بيوغلو', dist_buyukcekmece: 'بيوك تشكمجه', dist_catalca: 'شاتالجا',
    dist_cekmekoy: 'تشكمه كوي', dist_esenler: 'إيسنلار', dist_esenyurt: 'إيسنيورت', dist_eyupsultan: 'أيوب سلطان', dist_fatih: 'الفاتح',
    dist_gaziosmanpasa: 'غازي عثمان باشا', dist_gungoren: 'غونغوران', dist_kadikoy: 'كاديكوي', dist_kagithane: 'كاغيت هانة', dist_kartal: 'كارتال',
    dist_kucukcekmece: 'كوتشوك تشكمجه', dist_maltepe: 'مالتيبي', dist_pendik: 'بنديك', dist_sancaktepe: 'سانجاك تبي', dist_sariyer: 'ساريير',
    dist_sile: 'شيلا', dist_silivri: 'سيليفري', dist_sisli: 'شيشلي', dist_sultanbeyli: 'سلطان بيلي', dist_sultangazi: 'سلطان غازي',
    dist_tuzla: 'توزلا', dist_umraniye: 'عمرانية', dist_uskudar: 'أوسكودار', dist_zeytinburnu: 'زيتين بورنو',
    biz_restaurant: 'مطعم', biz_cafe: 'مقهى', biz_retail: 'متجر تجزئة', biz_office: 'مكتب', biz_pharmacy: 'صيدلية',
    biz_bakery: 'مخبز', biz_barber: 'صالون حلاقة', biz_gym: 'صالة رياضية', biz_shop: 'متجر', biz_store: 'محل', biz_company: 'شركة',
    biz_clothing: 'متجر ملابس', biz_hotel: 'فندق', biz_clinic: 'عيادة', biz_school: 'مدرسة',
    settings_title: 'الإعدادات',
    settings_appearance: 'المظهر',
    settings_profile: 'الملف الشخصي',
    settings_history: 'سجل الدردشة',
    settings_security_title: 'الأمن والخصوصية',
    settings_theme: 'السمة',
    settings_lang: 'اللغة',
    settings_2fa_title: 'المصادقة الثنائية',
    settings_2fa_desc: 'أضف طبقة أمان إضافية لحسابك.',
    settings_2fa_enable: 'تفعيل المصادقة الثنائية',
    settings_sessions_title: 'الجلسات النشطة',
    settings_sessions_desc: 'إدارة وتسجيل الخروج من الجلسات النشطة الأخرى.',
    settings_sessions_logout: 'تسجيل الخروج من الجلسات الأخرى',
    settings_danger_zone: 'منطقة الخطر',
    settings_delete_desc: 'بمجرد حذف حسابك، لن تتمكن من التراجع. يرجى التأكد.',
    settings_delete_account: 'حذف الحساب',
    settings_delete_confirm: 'اكتب "حذف" لتأكيد إزالة الحساب',
    settings_delete_yes: 'نعم، احذف حسابي',
    settings_confirm_clear: 'نعم، امسح السجل',
    settings_cancel: 'إلغاء',
    settings_clear_history: 'مسح السجل',
    scroll_right: 'مرر لليمين',
    click_to_flip: 'انقر للكشف',
    auth_terms: 'الشروط',
    auth_privacy: 'الخصوصية',
    auth_help: 'المساعدة',
    footer_english: 'الإنجليزية',
    footer_turkish: 'التركية',
    footer_arabic: 'العربية',
    auth_login_header: 'تسجيل الدخول',
    auth_login_subheader: 'باستخدام حساب TurkGateway الخاص بك',
    auth_forgot_email: 'هل نسيت البريد الإلكتروني؟',
    auth_guest_notice: 'هل تستخدم جهاز كمبيوتر غير خاص بك؟ استخدم وضع الضيف لتسجيل الدخول بخصوصية.',
    auth_learn_more: 'مزيد من المعلومات حول استخدام وضع الضيف',
    auth_next: 'التالي',
    auth_change_email: 'تغيير البريد الإلكتروني',
    auth_signup_header: 'إنشاء حساب',
    auth_signup_subheader: 'للمتابعة إلى TurkGateway',
    auth_signin_instead: 'تسجيل الدخول بدلاً من ذلك',
    auth_sign_in_as: 'تسجيل الدخول باسم',
    services_title: 'استكشف وكلاء الذكاء الاصطناعي',
    services_subtitle: 'قم بتوسيع رحلتك الإدارية بدعم احترافي من الذكاء الاصطناعي.',
    services_permit_desc: 'تراخيص الأعمال، تصاريح البيع بالتجزئة، وإعداد الامتثال الصناعي.',
    services_student_desc: 'التسجيل الجامعي، تصاريح الإقامة، وتجديدات الطلاب.',
    services_lawyer_desc: 'المساعدة القانونية المهنية وعمليات التحقق من الامتثال.',
    services_feat_retail: 'تصاريح المحلات التجارية',
    services_feat_restaurant: 'تراخيص المطاعم والمقاهي',
    services_feat_fire: 'الامتثال للسلامة من الحرائق',
    services_feat_municipal: 'بروتوكولات البلدية',
    services_feat_uni: 'التسجيل الجامعي',
    services_feat_visa: 'طلب تأشيرة الطالب',
    services_feat_kimlik: 'الحصول على الهوية وتجديدها (Kimlik)',
    services_feat_nufus: 'الحصول على النفوس (تسجيل العنوان)',
    services_feat_contract: 'مراجعة العقود',
    services_feat_formation: 'تأسيس الشركات',
    services_feat_disputes: 'النزاعات القانونية',
    services_feat_compliance: 'فحوصات الامتثال',
    services_status_available: 'متاح',
    services_status_active: 'نشط',
    services_status_waitlist: 'قائمة الانتظار',
    services_status_soon: 'قريباً',
    services_cta_describe: 'صف ما تحتاجه',
    services_ai_does_work: 'الذكاء الاصطناعي يقوم بالعمل',
    services_ai_desc: 'يعمل TurkGateway خلال كل خطوة، ويقوم بإطلاعك قبل أي شيء مهم. شاهد في الوقت الفعلي أو اترك العمل لنا.',
    services_control_title: 'أنت في التحكم',
    services_control_desc: 'أنت تختار البوابات وقواعد البيانات التي يمكن لـ TurkGateway الوصول إليها.',
    services_encryption: 'تشفير شامل',
    services_privacy: 'الخصوصية أولاً',
    services_allow_files: 'السماح للوكيل بتغيير الملفات؟',
    services_allow_desc: 'يتضمن ذلك نماذج البلدية وتنزيلات e-Devlet. سيتمكن الوكيل من قراءة الملفات وتحريرها وتخزينها مؤقتاً.',
    services_allow_access: 'السماح بالوصول',
    services_always_allow: 'السماح دائماً',
    services_list_title: 'لننجز بعض المهام من قائمتك',
    services_task_tax: 'الامتثال الضريبي',
    services_task_register: 'تأسيس شركة',
    services_task_enroll: 'التسجيل الجامعي',
    services_task_permit: 'تصريح عمل',
    services_task_legal: 'استشارة قانونية',
    services_task_renewal: 'تجديد الهوية',
    services_cta_title: 'صف ما تحتاجه',
    services_cta_desc: 'أخبر TurkGateway بما تريد تحقيقه. يختار وكلاؤنا أسرع مسار: الاتصال بالبوابات الحكومية، أو واجهات برمجة تطبيقات البلدية، أو استخدام OCR المتقدم لمعالجة مستنداتك على الفور.',
    services_launch_agent: 'تشغيل الوكيل',
    services_chat_greeting: 'كيف يمكنني مساعدتك اليوم؟',
    services_setup_agent: 'إعداد الوكيل',
    services_start_agent: 'بدء الوكيل',
    services_type_service: 'نوع الخدمة',
    services_select_service: 'اختر الخدمة',
    services_select_uni: 'اختر الجامعة',
    services_select_uni_placeholder: 'اختر جامعة',
    services_district: 'منطقة إسطنبول',
    services_select_district: 'اختر المنطقة',
    services_secure_session: 'جلسة مشفرة آمنة بقوة 256 بت',
    services_res_register: 'ممتاز. لقد قمت بتنشيط الوكيل القانوني. أنا أتصل ببوابة MERSİS لإنشاء خارطة طريق تأسيس شركتك المحدودة. إليك الخطوات الأولى...',
    services_res_tax: 'أقوم باسترداد أحدث قوائم المراجعة الضريبية للشركات من VDK وإنشاء بروتوكول تدقيق آلي لعملك الرقمي.',
    services_res_permit: 'بدء وكيل التصاريح. الاتصال ببوابة وزارة العمل لجلب إعفاءات الحصص الحالية ومتطلبات صاحب العمل.',
    services_res_enroll: 'تم تنشيط وكيل الطلاب. جلب متطلبات YÖK المحددة لجامعة كوتش وقائمة وثائق تصريح الإقامة الخاصة بك.',
    services_res_renewal: 'سأرشدك خلال طلب تمديد الإقامة الإلكترونية. الاتصال بـ API إدارة الهجرة للتحقق من حالة تصريحك الحالية...',
    services_res_legal: 'الوكيل القانوني يتابع. لقد وصلت إلى إطار القانون التجاري التركي لإنشاء معيار مراجعة لعقدك التجاري.',
    services_prompt_register: 'أريد فتح شركة محدودة جديدة في تركيا. ما هي المتطلبات والخطوات القانونية؟',
    services_prompt_tax: 'أحتاج إلى التأكد من أن عملي الرقمي متوافق تماماً مع ضريبة الشركات التركية.',
    services_prompt_permit: 'أريد التقدم بطلب للحصول على تصريح عمل لموظف أجنبي في إسطنبول.',
    services_prompt_enroll: 'أحتاج إلى مساعدة في التسجيل في جامعة كوتش والتقدم بطلب للحصول على تأشيرة طالب.',
    services_prompt_renewal: 'إقامتي الإلكترونية تنتهي الشهر المقبل، كيف يمكنني تجديدها؟',
    services_prompt_legal: 'أريد مراجعة عقد تجاري دولي بموجب القانون التجاري التركي.',
    guest_modal_title: "شكراً لتجربتك TurkGateWay",
    guest_modal_desc: "سجل الدخول أو أنشئ حساباً للحصول على إجابات أكثر ذكاءً، وفتح خرائط الطريق، والمزيد.",
    login: "تسجيل الدخول",
    signup_free: "سجل مجاناً",
    stay_logged_out: "البقاء دون تسجيل",
    chat_tab_suggested: 'مقترح',
    chat_tab_chat: 'دردشة',
    chip_cafe_restaurant: 'مقهى ومطعم',
    chip_retail_shop: 'محل تجاري',
    chip_office_tech: 'مكتب وتقنية',
    chip_pharmacy: 'صيدلية',
    chip_clinic: 'عيادة',
    chip_residence_permit: 'تصريح إقامة',
    chip_uni_reg: 'التسجيل الجامعي',
    chip_ikamet: 'الإقامة (İkamet)',
    chip_denklik: 'الدنكليك (معادلة الشهادة)',
    chip_dormitory: 'السكن والمبيت',
    chip_student_visa: 'تأشيرة الطالب',
    chip_istanbul_kart: 'إسطنبول كارت',
    chip_company_formation: 'تأسيس شركة',
    chip_contract_review: 'مراجعة العقود',
    chip_employment_law: 'قانون العمل',
    chip_legal_disputes: 'نزاعات قانونية',
    chip_residency_visas: 'الإقامة والتأشيرات',
    chip_real_estate: 'قانون العقارات',
    help_hero: 'كيف يمكننا مساعدتك؟',
    help_cat_docs_title: 'الوثائق',
    help_cat_docs_desc: 'أدلة تفصيلية للتراخيص التجارية وشؤون الطلاب وبروتوكولات المحامين',
    help_cat_community_title: 'المجتمع',
    help_cat_community_desc: 'انضم إلى أكثر من 10,000 شركة وطالب في إسطنبول',
    help_cat_resources_title: 'مركز الموارد',
    help_cat_resources_desc: 'قوائم المراجعة والقوانين والنماذج بصيغة PDF',
    help_explore: 'استكشف',
    help_faq_q1: 'كيف أبدأ جلسة جديدة مع وكيل الذكاء الاصطناعي؟',
    help_faq_a1: 'انتقل إلى صفحة الخدمات واختر هدفك (مثلاً: فتح عمل تجاري، التسجيل الجامعي). سيقوم الموجّه الذكي تلقائياً بتوصيلك بالوكيل المتخصص (التراخيص أو الطلاب أو القانوني) وإعداد السياق المناسب لاحتياجاتك.',
    help_faq_q2: 'لماذا يطلب وكيل الأعمال معرفة منطقتي ونوع عملي؟',
    help_faq_a2: 'تتباين المتطلبات البيروقراطية في تركيا بشكل كبير حسب البلدية (إلتشه) والقطاع (كود NACE). بتزويدنا بهذه المعلومات، يضمن محرك السياق أن الذكاء الاصطناعي يجلب اللوائح البلدية والقواعد الضريبية الدقيقة المنطبقة على حالتك تحديداً.',
    help_faq_q3: 'هل يمكن للذكاء الاصطناعي إنشاء النماذج والوثائق الرسمية بدلاً عني؟',
    help_faq_a3: 'نعم! يوفر الوكلاء خرائط طريق خطوة بخطوة ويمكنهم إرشادك في إعداد المستندات لـ e-Devlet وإدارة الهجرة (تصاريح الإقامة) وMERSİS (تأسيس الشركات). غير أنك تحتاج إلى تقديم هذه المستندات بنفسك رسمياً للجهات الحكومية.',
    help_faq_q4: 'ما مدى دقة نصائح الوكيل القانوني؟',
    help_faq_a4: 'تم تدريب الوكيل القانوني على قانون التجارة التركي وقوانين العمل المحدّثة. وبينما يقدم إرشادات تأسيسية ممتازة ومراجعة عقود، فإنه لا يُغني عن محامٍ مرخّص في الإجراءات القضائية الرسمية أو التمثيل القانوني الملزم.',
    help_faq_q5: 'كيف يمكنني تغيير لغة ردود الذكاء الاصطناعي؟',
    help_faq_a5: 'يمكنك تغيير لغة الواجهة باستخدام أيقونة الكرة الأرضية في شريط التنقل. سيتلقى الوكيل الذكي تعليمات تلقائية للرد بلغتك المختارة (الإنجليزية أو التركية أو العربية) باستخدام نظام التخزين المؤقت المحلي.',
    help_faq_q6: 'هل يتم حفظ سجل محادثتي بشكل آمن؟',
    help_faq_a6: 'نعم. تُخزَّن جلساتك النشطة محلياً في متصفحك للحفاظ على السياق. إذا مسحت بيانات المتصفح أو حذفت الجلسة من الشريط الجانبي، فسيُمحى سجل الحادثة لتلك الجلسة بشكل دائم.',
    help_still_questions: 'هل لا تزال لديك أسئلة؟',
    help_support_desc: 'فريق الدعم لدينا متاح على مدار الساعة طوال أيام الأسبوع لمساعدتك في التعامل مع التعقيدات البلدية.',
    help_email_support: 'الدعم عبر البريد الإلكتروني',
    help_ask_ai: 'اسأل المساعد الذكي',
    download_hero1: 'وكيل الذكاء الاصطناعي الخاص بك،',
    download_hero2: 'متاح على سطح المكتب.',
    download_desc: 'استمتع بالقوة الكاملة لـ TurkGateway مباشرةً من سطح المكتب. ردود أسرع ونافذة مخصصة وعمليات خلفية سلسة لنظامَي Windows وMac وLinux.',
    download_feat1_title: 'أداء أصلي',
    download_feat1_desc: 'يعمل خارج المتصفح بموارد مخصصة لذكاء اصطناعي أسرع.',
    download_feat2_title: 'معالجة محلية',
    download_feat2_desc: 'الواجهة الخلفية المدمجة تحافظ على سرية مستنداتك الحساسة دون اتصال.',
    download_feat3_title: 'تحديثات تلقائية',
    download_feat3_desc: 'تحديثات صامتة في الخلفية تُبقيك دائماً على أحدث إصدار.',
    docs_back: 'العودة إلى مركز المساعدة',
    docs_title: 'بنية TurkGateway الذكية',
    docs_subtitle: 'استكشف البنية التقنية وآليات التوجيه وخطوط معالجة البيانات التي تدعم منصتنا المتخصصة في البيروقراطية التركية.',
    docs_sec_architecture: 'بنية النظام',
    docs_sec_router: 'الموجّه الذكي والسياق',
    docs_sec_permit: 'وكيل الأعمال',
    docs_sec_student: 'وكيل الطلاب',
    docs_sec_legal: 'الوكيل القانوني',
    docs_sec_terms: 'شروط الخدمة',
    docs_sec_privacy: 'سياسة الخصوصية',
    docs_sec_resources: 'مركز الموارد',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Initialize state from localStorage if available to prevent flash of wrong language
  const [language, setLanguageState] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'ar', 'tr'].includes(saved)) {
      setLanguageState(saved);
      document.documentElement.lang = saved;
      document.documentElement.dir = saved === 'ar' ? 'rtl' : 'ltr';
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
      // Update DOM immediately for instant layout shift
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    }
  };

  useEffect(() => {
    if (mounted) {
      localStorage.setItem('language', language);
      document.documentElement.lang = language;
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }
  }, [language, mounted]);

  const t = (key: string) => {
    // During hydration, always use English to match server
    const displayLang = mounted ? language : 'en';
    return translations[displayLang]?.[key] || key;
  };

  const isRTL = language === 'ar';

  const translateHistory = (content: string) => {
    const original = content;
    const entries = Object.entries(translations.en);
    const matchingKey = entries.find(([k, v]) => v === original)?.[0];
    if (matchingKey) return t(matchingKey);
    return original;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, translateHistory }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
