'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
  translateHistory: (content: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    navbar_home: 'Home',
    navbar_chat: 'TurkGateway AI',
    navbar_dashboard: 'Dashboard',
    navbar_get_started: 'Get Started',
    home_hero_title: 'The AI Platform for Turkish Business, Law & Education.',
    home_hero_subtitle: 'Navigate permits, legal protocols, and university registration effortlessly. Our specialized AI agents build your personalized roadmap in seconds.',
    home_hero_greeting_user: 'Hi Hamza',
    home_hero_question: 'Where should we start?',
    home_hero_cta: 'Get Started',
    hero_cat_upload: 'Upload documents',
    hero_cat_status: 'Check status',
    hero_cat_protocols: 'District protocols',
    hero_cat_safety: 'Fire safety guide',
    how_it_works_label: 'How it works',
    process_title: 'The AI Process',
    process_subtitle: 'Let our AI Agents handle the heavy lifting for you.',
    process_step1_title: 'Describe',
    process_step1_desc: 'Tell us about your business, legal issue, or university goals in plain language. Our AI instantly understands local regulations and requirements.',
    process_step2_title: 'Analyze',
    process_step2_desc: 'Our specialized AI agents cross-reference municipal protocols, laws, and academic guidelines to build your exact roadmap.',
    process_step3_title: 'Execute',
    process_step3_desc: 'We map out every step—from e-Devlet filings and ID renewals to university enrollment—so you can focus on your goals without the bureaucratic headache.',
    dashboard_title: 'Permit Dashboard',
    dashboard_sync: 'Sync',
    dashboard_ask_ai: 'Ask AI',
    dashboard_upload: 'Upload Docs',
    chat_placeholder: 'Ask TurkGateway AI agents...',
    chat_new: 'New Chat',
    chat_greeting: 'Hello there.',
    chat_subtitle: 'How can I help with Istanbul permits today?',
    chat_q1: 'What permits do I need for a restaurant in Istanbul?',
    chat_q2: 'How long does the fire safety inspection take?',
    chat_q3: 'What documents does the municipality require?',
    chat_q4: 'What is the cost of a fire safety certificate?',
    dashboard_updated: 'Updated',
    dashboard_live_session: 'Live Session',
    dashboard_days: 'days',
    dashboard_active: 'active',
    dashboard_running: 'Running',
    dashboard_agent_status: 'Agent processing workflow',
    dashboard_ask_ai_step: 'Ask AI about this step',
    dashboard_no_session: 'No active session',
    dashboard_processing: 'Processing...',
    dashboard_compliance_score: 'Compliance Score',
    dashboard_steps_complete: 'Steps Complete',
    dashboard_est_days: 'Est. Days Left',
    dashboard_active_agents: 'Active AI Agents',
    dashboard_overall_progress: 'Overall Progress',
    dashboard_workflow_steps: 'Workflow Steps',
    dashboard_action_required: 'Action Required',
    dashboard_all_clear: 'All clear',
    dashboard_action_required_desc: 'Please complete the {step} step to proceed.',
    dashboard_bot_processing: 'System is currently processing agent tasks.',
    dashboard_whats_next: 'What\'s next',
    dashboard_next_step_desc: 'Once your initial documents are approved, your final Business License (İşyeri Açma ve Çalışma Ruhsatı) will be processed.',
    dashboard_init_title: 'Initialize Workflow',
    dashboard_init_summary: 'Start a chat to generate your permit plan.',
    dashboard_init_detail: 'Once you describe your business in the chat, the AI will generate a customized permit path for you here.',
    dashboard_mark_complete: 'Mark as Complete',
    dashboard_mark_done: 'Mark step as done',
    dashboard_syncing: 'Synchronizing with Local Municipality...',
    dashboard_toast_success: 'Document uploaded successfully!',
    dashboard_auto_execute: 'Auto-Execute Bot',
    status_completed: 'Completed',
    status_in_progress: 'In Progress',
    status_pending: 'Pending',
    chat_welcome: 'Hi {name}',
    chat_begin: 'Where do we begin?',
    chat_placeholder_alt: 'Ask your permit assistant...',
    chat_suggestion_business: 'I want to open a business',
    chat_suggestion_permit: 'I want to obtain a permit',
    chat_suggestion_location: 'My business location',
    chat_suggestion_duration: 'How long does it take?',
    chat_suggestion_cost: 'How much does it cost?',
    chat_suggestion_obtain: 'I want to obtain a business permit',
    chat_suggestion_steps: 'I want to know the steps',
    chat_suggestion_docs: 'What documents do I need?',
    chat_suggestion_help: 'How does it work?',
    sidebar_new_chat: 'New Chat',
    sidebar_recent: 'Recent',
    sidebar_help: 'Help',
    sidebar_activity: 'Activity',
    sidebar_settings: 'Settings',
    navbar_pricing: 'Pricing',
    sidebar_upgrade: 'Upgrade',
    sidebar_home: 'Home',
    sidebar_dashboard: 'Dashboard',
    sidebar_my_stuff: 'My stuff',
    sidebar_gems: 'Gems',
    sidebar_logout: 'Logout',
    navbar_logout: 'Logout',
    navbar_login: 'Login',
    navbar_signup: 'Sign Up',
    navbar_subscribers: 'Subscribers',
    dashboard_no_permits: 'No active permits found',
    sidebar_switch_assistant: 'Switch Assistant',
    sidebar_sign_in_prompt: 'Sign in to start saving your chats',
    sidebar_sign_in_desc: 'Once you\'re signed in, you can access your recent chats here.',

    help_title: 'Help Center',
    help_faq: 'FAQ',
    help_contact: 'Contact Support',
    help_docs: 'Documentation',
    help_feedback: 'Send Feedback',
    help_search: 'Search for help...',
    home_stat_districts: 'Districts covered',
    home_stat_types: 'Permit types',
    home_stat_time: 'Time saved',
    home_stat_success: 'Success rate',
    home_feature_agents: 'Multi-Agent AI',
    home_feature_agents_desc: 'LangGraph orchestrated agents run planning, classification, and compliance checking in parallel.',
    home_feature_districts: 'All 39 Districts',
    home_feature_districts_desc: 'Full Istanbul coverage — supporting all 39 municipalities with distinct local protocols.',
    home_feature_tracking: 'Real-Time Tracking',
    home_feature_tracking_desc: 'Every step of your permit application is tracked. Nothing falls through the cracks.',
    home_step1_title: 'Tell us about your business',
    home_step1_desc: 'Answer a few questions about your business type, location, and scope.',
    home_step2_title: 'AI maps your permit path',
    home_step2_desc: 'Our agent system identifies every permit and document required for your case.',
    home_step3_title: 'Upload documents',
    home_step3_desc: 'We guide you through each required document with checklists and templates.',
    home_step4_title: 'Receive your approval',
    home_step4_desc: 'Track every approval in real time. Estimated timelines per municipality.',
    dashboard_toast_success_payment: 'Subscription activated! Welcome to Premium.',
    dashboard_toast_error_payment: 'Payment failed. Please try again.',
    dashboard_toast_error_sub: 'Failed to start subscription',
    assistant_permit: 'Permit',
    assistant_student: 'Student',
    assistant_lawyer: 'Lawyer',
    dashboard_student_title: 'Student Roadmap',
    dashboard_legal_title: 'Legal Dashboard',
    dashboard_free_plan: 'Free Plan',
    dashboard_premium: 'Premium',
    dashboard_upgrade: 'Upgrade',
    dashboard_starting: 'Starting...',
    dashboard_integration: 'Integration',
    dashboard_simulating: 'Simulating Local Municipality API...',
    loading_preparing: 'Preparing your workspace...',
    loading_verifying: 'Verifying credentials with e-Devlet...',
    loading_analyzing: 'Analyzing district protocols...',
    loading_building: 'Building your custom roadmap...',
    loading_finalizing: 'Finalizing synchronization...',
    dashboard_rpa_desc: 'Our RPA bot requires your credentials to log into {url} and automatically submit the verified documents on your behalf.',
    dashboard_id_label: 'T.C. Kimlik No',
    dashboard_password_label: 'Password',
    dashboard_id_placeholder: '11-digit ID number',
    dashboard_password_placeholder: '••••••••••••',
    dashboard_disabled_law: 'DISABLED UNTIL LAW APPROVAL',
    dashboard_privacy_notice: 'Your credentials are used solely for this session and are NEVER logged into our database.',
    auth_login_title: 'Welcome Back',
    auth_login_subtitle: 'Continue your permit journey with AI.',
    auth_signup_title: 'Create Account',
    auth_signup_subtitle: 'Start your professional permit roadmap today.',
    auth_email: 'Email address',
    auth_password: 'Password',
    auth_full_name: 'Full Name',
    auth_forgot_password: 'Forgot password?',
    auth_no_account: 'Don\'t have an account?',
    auth_has_account: 'Already have an account?',
    auth_signing_in: 'Signing in...',
    auth_signing_up: 'Creating account...',
    chat_switch_assistant: 'Switch Assistant',
    chat_permit_desc: 'Business & Municipal Protocol',
    chat_student_desc: 'Academic Tasks & ID Renewals',
    chat_lawyer_desc: 'Legal Advice & Compliance',
    chat_sug_renew: 'Renew Kimlik/ID',
    chat_sug_uni: 'Best Universities',
    chat_sug_roadmap: 'Register Roadmap',
    chat_sug_deadlines: 'Deadlines',
    chat_sug_visas: 'Student Visas',
    chat_sug_shelp: 'Student Help',
    chat_sug_contract: 'Contract Review',
    chat_sug_formation: 'Company Formation',
    chat_sug_employ: 'Employment Law',
    chat_sug_times: 'Legal Timelines',
    chat_sug_resid: 'Residency/Permit',
    chat_sug_dispute: 'Legal Disputes',
    pricing_title: 'Simple, transparent pricing',
    pricing_subtitle: 'Start free. Upgrade when you need compliance automation that scales.',
    pricing_monthly: 'Monthly',
    pricing_annual: 'Annual',
    pricing_save: 'Save {amount}/yr',
    pricing_free_desc: 'For individuals exploring permit requirements. No credit card required.',
    pricing_premium_desc: 'Full capabilities for businesses managing compliance at scale in Istanbul.',
    pricing_current: 'Current Plan',
    pricing_upgrade: 'Upgrade to Premium',
    pricing_most_popular: 'Most Popular',
    pricing_compare: 'Compare plans',
    pricing_compare_subtitle: 'Everything you need to make the right decision.',
    pricing_faq_title: 'Frequently asked questions',
    pricing_faq_subtitle: 'Have a question not listed here?',
    pricing_contact_us: 'Contact us',
    pricing_cta_title: 'Ready to streamline your compliance?',
    pricing_cta_subtitle: 'Join businesses across Istanbul using TurkGateway to automate their regulatory workflows.',
    pricing_secure_checkout: 'Secure checkout via iyzico',
    pricing_cancel_anytime: 'Cancel anytime',
    pricing_vat_included: 'VAT invoice included',
    pricing_feat_ai: 'AI Permit Consultations',
    pricing_feat_sessions: 'Active Sessions',
    pricing_feat_history: 'Project History',
    pricing_feat_docs: 'Document Management',
    pricing_feat_priority: 'Priority Agent Workflows',
    pricing_feat_support: '1-on-1 Regulatory Support',
    pricing_feat_access: 'Early Access to New Regulations',
    pricing_feat_multi: 'Multi-language Support (TR/EN/AR)',
    pricing_feat_comm: 'Community Access',
    pricing_feat_limited: 'Limited',
    pricing_feat_unlimited: 'Unlimited',
    pricing_feat_7days: '7 days',
    pricing_faq_q1: 'Can I cancel my subscription at any time?',
    pricing_faq_a1: 'Yes. You can cancel your Premium subscription at any time from your account settings. You will retain access until the end of your current billing period.',
    pricing_faq_q2: 'Is my payment information secure?',
    pricing_faq_a2: 'All payments are processed by iyzico, a PCI-DSS Level 1 certified payment provider. We never store your card details on our servers.',
    pricing_faq_q3: 'What happens when I upgrade from Free to Premium?',
    pricing_faq_a3: 'Your account is upgraded instantly. All limits are lifted and priority features become available immediately after payment confirmation.',
    pricing_faq_q4: 'Do you offer invoices for business accounting?',
    pricing_faq_a4: 'Yes. A VAT-compliant invoice is automatically issued via iyzico after every successful payment and can be downloaded from your account.',
    pricing_trust_enc: 'Bank-level encryption',
    pricing_trust_pci: 'PCI-DSS Compliant',
    pricing_trust_supp: 'Priority support',
    pricing_trust_resp: 'avg. 2h response',
    pricing_trust_cancel: 'Cancel anytime',
    pricing_trust_lockin: 'No lock-in contracts',
    pricing_get_started: 'Get started with Premium',
    pricing_ready: 'Ready to streamline your compliance?',
    connect_in: 'in',
    agent_name: 'TurkGateway AI Advisor',
    agent_thinking: 'Agent is thinking...',
    footer_version: 'Municipal Protocol Engine • v2.5',
    dist_adalar: 'Adalar', dist_arnavutkoy: 'Arnavutköy', dist_atasehir: 'Ataşehir', dist_avcilar: 'Avcılar', dist_bagcilar: 'Bağcılar',
    dist_bahcelievler: 'Bahçelievler', dist_bakirkoy: 'Bakırköy', dist_basaksehir: 'Başakşehir', dist_bayrampasa: 'Bayrampaşa', dist_besiktas: 'Beşiktaş',
    dist_beykoz: 'Beykoz', dist_beylikduzu: 'Beylikdüzü', dist_beyoglu: 'Beyoğlu', dist_buyukcekmece: 'Büyükçekmece', dist_catalca: 'Çatalca',
    dist_cekmekoy: 'Çekmeköy', dist_esenler: 'Esenler', dist_esenyurt: 'Esenyurt', dist_eyupsultan: 'Eyüpsultan', dist_fatih: 'الفاتح',
    dist_gaziosmanpasa: 'Gaziosmanpaşa', dist_gungoren: 'Güngören', dist_kadikoy: 'Kadıköy', dist_kagithane: 'Kağıthane', dist_kartal: 'Kartal',
    dist_kucukcekmece: 'Küçükçekmece', dist_maltepe: 'Maltepe', dist_pendik: 'Pendik', dist_sancaktepe: 'Sancaktepe', dist_sariyer: 'Sarıyer',
    dist_sile: 'Şile', dist_silivri: 'Silivri', dist_sisli: 'Şişli', dist_sultanbeyli: 'Sultanbeyli', dist_sultangazi: 'Sultangazi',
    dist_tuzla: 'Tuzla', dist_umraniye: 'Ümraniye', dist_uskudar: 'Üsküdar', dist_zeytinburnu: 'Zeytinburnu',
    biz_restaurant: 'Restaurant', biz_cafe: 'Café', biz_retail: 'Retail Store', biz_office: 'Office', biz_pharmacy: 'Pharmacy',
    biz_bakery: 'Bakery', biz_barber: 'Barber Shop', biz_gym: 'Gym', biz_shop: 'Shop', biz_store: 'Store', biz_company: 'Company',
    settings_title: 'Settings',
    settings_appearance: 'Appearance',
    settings_profile: 'Profile',
    settings_history: 'Chat History',
    settings_security_title: 'Security & Privacy',
    settings_theme: 'Theme',
    settings_lang: 'Language',
    settings_2fa_title: 'Two-Factor Authentication',
    settings_2fa_desc: 'Add an extra layer of security to your account.',
    settings_2fa_enable: 'Enable 2FA',
    settings_sessions_title: 'Active Sessions',
    settings_sessions_desc: 'Manage and sign out of other active sessions.',
    settings_sessions_logout: 'Sign out other sessions',
    settings_danger_zone: 'Danger Zone',
    settings_delete_desc: 'Once you delete your account, there is no going back. Please be certain.',
    settings_delete_account: 'Delete Account',
    settings_delete_confirm: 'TYPE "DELETE" TO CONFIRM ACCOUNT REMOVAL',
    settings_delete_yes: 'Yes, delete my account',
    settings_confirm_clear: 'Yes, clear history',
    settings_cancel: 'Cancel',
    settings_clear_history: 'Clear History',
    biz_clothing: 'Clothing Store', biz_hotel: 'Hotel', biz_clinic: 'Clinic', biz_school: 'School',
    scroll_right: 'Scroll Right',
    click_to_flip: 'Tap to reveal',
  },
  tr: {
    navbar_home: 'Ana Sayfa',
    navbar_chat: 'TurkGateway AI',
    navbar_dashboard: 'Dashboard',
    navbar_get_started: 'Başla',
    home_hero_title: 'Türkiye\'de İş, Hukuk ve Eğitim İçin AI Platformu.',
    home_hero_subtitle: 'İzinler, hukuki protokoller ve üniversite kayıt süreçlerinde kolayca ilerleyin. Uzman ajanlarımız, size özel yol haritanızı anında oluşturur.',
    home_hero_greeting_user: 'Selam Hamza',
    home_hero_question: 'Nereden başlayalım?',
    home_hero_cta: 'Başla',
    hero_cat_upload: 'Belge yükle',
    hero_cat_status: 'Durumu kontrol et',
    hero_cat_protocols: 'Belediye protokolleri',
    hero_cat_safety: 'Yangın güvenliği rehberi',
    how_it_works_label: 'Nasıl çalışır',
    process_title: 'Yapay Zeka Süreci',
    process_subtitle: 'Ağır bürokratik işlemleri Yapay Zeka Ajanlarımıza bırakın.',
    process_step1_title: 'Tarif Et',
    process_step1_desc: 'İşletmenizi, hukuki sorununuzu veya üniversite hedeflerinizi kendi kelimelerinizle anlatın. Yapay zekamız yerel mevzuatları anında kavrar.',
    process_step2_title: 'Analiz Et',
    process_step2_desc: 'Uzman AI ajanlarımız, size özel yol haritasını çıkarmak için belediye protokollerini, yasaları ve akademik yönergeleri tarar.',
    process_step3_title: 'Uygula',
    process_step3_desc: 'e-Devlet işlemlerinden kimlik yenilemeye ve üniversite kayıtlarına kadar her adımı planlıyoruz; böylece bürokrasiyle uğraşmadan hedeflerinize odaklanabilirsiniz.',
    dashboard_title: 'İzin Paneli',
    dashboard_sync: 'Senkronize Et',
    dashboard_ask_ai: 'AI\'ya Sor',
    dashboard_upload: 'Belge Yükle',
    chat_placeholder: 'TurkGateway AI ajanlarına sorun...',
    chat_new: 'Yeni Sohbet',
    chat_greeting: 'Selam.',
    chat_subtitle: 'Bugün İstanbul izinleri konusunda nasıl yardımcı olabilirim?',
    chat_q1: 'İstanbul\'da restoran için hangi izinlere ihtiyacım var?',
    chat_q2: 'Yangın güvenliği denetimi ne kadar sürer?',
    chat_q3: 'Belediye hangi belgeleri istiyor?',
    chat_q4: 'Yangın güvenlik sertifikasının maliyeti nedir?',
    dashboard_updated: 'Güncellendi',
    dashboard_live_session: 'Canlı Oturum',
    dashboard_days: 'gün',
    dashboard_active: 'aktif',
    dashboard_running: 'Çalışıyor',
    dashboard_agent_status: 'Ajan iş akışını işliyor',
    dashboard_ask_ai_step: 'Bu adım hakkında AI\'ya sor',
    dashboard_no_session: 'Aktif oturum yok',
    dashboard_processing: 'İşleniyor...',
    dashboard_compliance_score: 'Uyum Skoru',
    dashboard_auto_execute: 'Botu Otomatik Çalıştır',
    dashboard_steps_complete: 'Tamamlanan Adımlar',
    dashboard_est_days: 'Tahmini Kalan Gün',
    dashboard_active_agents: 'Aktif AI Ajanları',
    dashboard_overall_progress: 'Genel İlerleme',
    dashboard_workflow_steps: 'İş Akışı Adımları',
    dashboard_action_required: 'Eylem Gerekiyor',
    dashboard_all_clear: 'Her şey yolunda',
    dashboard_action_required_desc: 'Lütfen devam etmek için {step} adımını tamamlayın.',
    dashboard_bot_processing: 'Sistem şu anda ajan görevlerini işliyor.',
    dashboard_whats_next: 'Sıradaki ne?',
    dashboard_next_step_desc: 'Başlangıç belgeleriniz onaylandıktan sonra, nihai İşyeri Açma ve Çalışma Ruhsatınız işleme alınacaktır.',
    dashboard_init_title: 'İş Akışını Başlat',
    dashboard_init_summary: 'İzin planınızı oluşturmak için bir sohbet başlatın.',
    dashboard_init_detail: 'Sohbet kısmında işinizi tarif ettiğinizde, yapay zeka size özel izin yolunu burada oluşturacaktır.',
    dashboard_mark_complete: 'Tamamlandı Olarak İşaretle',
    dashboard_mark_done: 'Adımı tamamlandı işaretle',
    dashboard_syncing: 'Yerel Belediye ile senkronize ediliyor...',
    dashboard_toast_success: 'Belge başarıyla yüklendi!',
    status_completed: 'Tamamlandı',
    status_in_progress: 'Devam Ediyor',
    status_pending: 'Beklemede',
    chat_welcome: 'Selam {name}',
    chat_begin: 'Nereden başlayalım?',
    chat_placeholder_alt: 'İzin asistanınıza sorun...',
    chat_suggestion_business: 'İşletme açmak istiyorum',
    chat_suggestion_permit: 'İzin almak istiyorum',
    chat_suggestion_location: 'İşletme konumum',
    chat_suggestion_duration: 'Ne kadar sürer?',
    chat_suggestion_cost: 'Maliyeti nedir?',
    chat_suggestion_obtain: 'İş yeri açma ruhsatı almak istiyorum',
    chat_suggestion_steps: 'Adımları öğrenmek istiyorum',
    chat_suggestion_docs: 'Hangi belgelere ihtiyacım var?',
    chat_suggestion_help: 'Nasıl çalışır?',
    sidebar_new_chat: 'Yeni Sohbet',
    sidebar_recent: 'Geçmiş',
    sidebar_help: 'Yardım',
    sidebar_activity: 'Etkinlik',
    sidebar_settings: 'Ayarlar',
    navbar_pricing: 'Fiyatlandırma',
    sidebar_upgrade: 'Yükselt',
    sidebar_home: 'Ana Sayfa',
    sidebar_dashboard: 'Dashboard',
    sidebar_my_stuff: 'Benimkiler',
    sidebar_gems: 'Cevherler',
    sidebar_logout: 'Çıkış Yap',
    navbar_logout: 'Çıkış Yap',
    navbar_login: 'Giriş Yap',
    navbar_signup: 'Üye Ol',
    navbar_subscribers: 'Aboneler',
    dashboard_no_permits: 'Aktif izin bulunamadı',
    sidebar_switch_assistant: 'Asistanı Değiştir',
    sidebar_sign_in_prompt: 'Sohbetlerinizi kaydetmek için giriş yapın',
    sidebar_sign_in_desc: 'Giriş yaptıktan sonra geçmiş sohbetlerinize buradan erişebilirsiniz.',

    help_title: 'Yardım Merkezi',
    help_faq: 'SSS',
    help_contact: 'Destekle İletişime Geç',
    help_docs: 'Dokümantasyon',
    help_feedback: 'Geri Bildirim Gönder',
    help_search: 'Yardım ara...',
    home_stat_districts: 'Kapsanan İlçe',
    home_stat_types: 'İzin Türü',
    home_stat_time: 'Zaman Tasarrufu',
    home_stat_success: 'Başarı Oranı',
    home_feature_agents: 'Çoklu Ajan Yapay Zeka',
    home_feature_agents_desc: 'LangGraph orkestrasyonlu ajanlar; planlama, sınıflandırma ve uyum kontrollerini paralel yürütür.',
    home_feature_districts: 'Tüm 39 İlçe',
    home_feature_districts_desc: 'Tüm İstanbul kapsamı — yerel protokolleri olan 39 belediyenin tamamını destekler.',
    home_feature_tracking: 'Gerçek Zamanlı Takip',
    home_feature_tracking_desc: 'İzin başvurunuzun her adımı takip edilir. Hiçbir detay gözden kaçmaz.',
    home_step1_title: 'İşletmenizden bahsedin',
    home_step1_desc: 'İşletme türünüz, konumunuz ve kapsamınız hakkında birkaç soruyu yanıtlayın.',
    home_step2_title: 'AI izin yolunuzu haritalar',
    home_step2_desc: 'Ajan sistemimiz, durumunuz için gerekli her izni ve belgeyi tanımlar.',
    home_step3_title: 'Belgeleri yükleyin',
    home_step3_desc: 'Kontrol listeleri ve şablonlarla her gerekli belgede size rehberlik ediyoruz.',
    home_step4_title: 'Onayınızı alın',
    home_step4_desc: 'Her onayı gerçek zamanlı takip edin. Belediye bazlı tahmini süreler.',
    dashboard_toast_success_payment: 'Abonelik aktif edildi! Premium\'a hoş geldiniz.',
    dashboard_toast_error_payment: 'Ödeme başarısız. Lütfen tekrar deneyin.',
    dashboard_toast_error_sub: 'Abonelik başlatılamadı',
    assistant_permit: 'İzin',
    assistant_student: 'Öğrenci',
    assistant_lawyer: 'Avukat',
    dashboard_student_title: 'Öğrenci Yol Haritası',
    dashboard_legal_title: 'Hukuki Panel',
    dashboard_free_plan: 'Ücretsiz Plan',
    dashboard_premium: 'Premium',
    dashboard_upgrade: 'Yükselt',
    dashboard_starting: 'Başlatılıyor...',
    dashboard_integration: 'Entegrasyonu',
    dashboard_simulating: 'Yerel Belediye API\'sı Simüle Ediliyor...',
    loading_preparing: 'Çalışma alanınız hazırlanıyor...',
    loading_verifying: 'e-Devlet ile kimlik bilgileri doğrulanıyor...',
    loading_analyzing: 'İlçe protokolleri analiz ediliyor...',
    loading_building: 'Özel yol haritanız oluşturuluyor...',
    loading_finalizing: 'Senkronizasyon tamamlanıyor...',
    dashboard_rpa_desc: 'RPA botumuz, {url} adresine giriş yapmak ve doğrulanan belgeleri adınıza otomatik olarak göndermek için kimlik bilgilerinize ihtiyaç duyar.',
    dashboard_id_label: 'T.C. Kimlik No',
    dashboard_password_label: 'Şifre',
    dashboard_id_placeholder: '11 haneli kimlik numarası',
    dashboard_password_placeholder: '••••••••••••',
    dashboard_disabled_law: 'YASAL ONAY ALINANA KADAR DEVRE DIŞI',
    dashboard_privacy_notice: 'Kimlik bilgileriniz yalnızca bu oturum için kullanılır ve asla veritabanımıza kaydedilmez.',
    auth_login_title: 'Tekrar Hoş Geldiniz',
    auth_login_subtitle: 'İzin yolculuğunuza AI ile devam edin.',
    auth_signup_title: 'Hesap Oluştur',
    auth_signup_subtitle: 'Profesyonel izin yol haritanıza bugün başlayın.',
    auth_email: 'E-posta adresi',
    auth_password: 'Şifre',
    auth_full_name: 'Ad Soyad',
    auth_forgot_password: 'Şifremi unuttum?',
    auth_no_account: 'Hesabınız yok mu?',
    auth_has_account: 'Zaten hesabınız var mı?',
    auth_signing_in: 'Giriş yapılıyor...',
    auth_signing_up: 'Hesap oluşturuluyor...',
    chat_switch_assistant: 'Asistan Değiştir',
    chat_permit_desc: 'İşletme ve Belediye Protokolü',
    chat_student_desc: 'Akademik Görevler ve Kimlik Yenileme',
    chat_lawyer_desc: 'Hukuki Danışmanlık ve Uyum',
    chat_sug_renew: 'Kimlik Yenileme',
    chat_sug_uni: 'En İyi Üniversiteler',
    chat_sug_roadmap: 'Kayıt Yol Haritası',
    chat_sug_deadlines: 'Son Tarihler',
    chat_sug_visas: 'Öğrenci Vizeleri',
    chat_sug_shelp: 'Öğrenci Yardımı',
    chat_sug_contract: 'Sözleşme İncelemesi',
    chat_sug_formation: 'Şirket Kurulumu',
    chat_sug_employ: 'İş Hukuku',
    chat_sug_times: 'Yasal Süreler',
    chat_sug_resid: 'İkamet/İzin',
    chat_sug_dispute: 'Hukuki Uyuşmazlıklar',
    pricing_title: 'Basit, şeffaf fiyatlandırma',
    pricing_subtitle: 'Ücretsiz başlayın. Ölçeklenen uyumluluk otomasyonuna ihtiyaç duyduğunuzda yükseltin.',
    pricing_monthly: 'Aylık',
    pricing_annual: 'Yıllık',
    pricing_save: 'Yılda {amount} tasarruf edin',
    pricing_free_desc: 'İzin gereksinimlerini keşfeden bireyler için. Kredi kartı gerekmez.',
    pricing_premium_desc: 'İstanbul\'da ölçekli uyumluluk yöneten işletmeler için tam kapasite.',
    pricing_current: 'Mevcut Plan',
    pricing_upgrade: 'Premium\'a Yükselt',
    pricing_most_popular: 'En Popüler',
    pricing_compare: 'Planları karşılaştırın',
    pricing_compare_subtitle: 'Doğru kararı vermek için ihtiyacınız olan her şey.',
    pricing_faq_title: 'Sıkça sorulan sorular',
    pricing_faq_subtitle: 'Burada listelenmeyen bir sorunuz mu var?',
    pricing_contact_us: 'Bize ulaşın',
    pricing_cta_title: 'Uyumluluğunuzu kolaylaştırmaya hazır mısınız?',
    pricing_cta_subtitle: 'Mevzuat iş akışlarını otomatikleştirmek için TurkGateway kullanan İstanbul genelindeki işletmelere katılın.',
    pricing_secure_checkout: 'iyzico üzerinden güvenli ödeme',
    pricing_cancel_anytime: 'İstediğiniz zaman iptal edin',
    pricing_vat_included: 'KDV dahil fatura',
    pricing_feat_ai: 'AI İzin Danışmanlığı',
    pricing_feat_sessions: 'Aktif Oturumlar',
    pricing_feat_history: 'Proje Geçmişi',
    pricing_feat_docs: 'Belge Yönetimi',
    pricing_feat_priority: 'Öncelikli Temsilci İş Akışları',
    pricing_feat_support: 'Bire Bir Mevzuat Desteği',
    pricing_feat_access: 'Yeni Düzenlemelere Erken Erişim',
    pricing_feat_multi: 'Çoklu Dil Desteği (TR/EN/AR)',
    pricing_feat_comm: 'Topluluk Erişimi',
    pricing_feat_limited: 'Sınırlı',
    pricing_feat_unlimited: 'Sınırsız',
    pricing_feat_7days: '7 gün',
    pricing_faq_q1: 'Aboneliğimi istediğim zaman iptal edebilir miyim?',
    pricing_faq_a1: 'Evet. Premium aboneliğinizi hesap ayarlarınızdan istediğiniz zaman iptal edebilirsiniz. Mevcut faturalandırma döneminizin sonuna kadar erişiminizi sürdürürsünüz.',
    pricing_faq_q2: 'Ödeme bilgilerim güvende mi?',
    pricing_faq_a2: 'Tüm ödemeler, PCI-DSS Seviye 1 sertifikalı bir ödeme sağlayıcısı olan iyzico tarafından işlenir. Kart bilgilerinizi asla sunucularımızda saklamayız.',
    pricing_faq_q3: 'Ücretsizden Premium\'a yükselttiğimde ne olur?',
    pricing_faq_a3: 'Hesabınız anında yükseltilir. Tüm sınırlar kaldırılır ve ödeme onayından hemen sonra öncelikli özellikler kullanılabilir hale gelir.',
    pricing_faq_q4: 'İşletme muhasebesi için fatura sunuyor musunuz?',
    pricing_faq_a4: 'Evet. Her başarılı ödemeden sonra iyzico aracılığıyla otomatik olarak KDV uyumlu bir fatura kesilir ve hesabınızdan indirilebilir.',
    pricing_trust_enc: 'Banka düzeyinde şifreleme',
    pricing_trust_pci: 'PCI-DSS Uyumlu',
    pricing_trust_supp: 'Öncelikli destek',
    pricing_trust_resp: 'ort. 2 saat yanıt',
    pricing_trust_cancel: 'İstediğiniz zaman iptal edin',
    pricing_trust_lockin: 'Taahhüt yok',
    pricing_get_started: 'Premium ile başlayın',
    pricing_ready: 'Uyumluluğunuzu kolaylaştırmaya hazır mısınız?',
    connect_in: 'İçinde',
    agent_name: 'TurkGateway Yapay Zeka Danışmanı',
    agent_thinking: 'Ajan düşünüyor...',
    footer_version: 'Belediye Protokol Motoru • v2.5',
    dist_adalar: 'Adalar', dist_arnavutkoy: 'Arnavutköy', dist_atasehir: 'Ataşehir', dist_avcilar: 'Avcılar', dist_bagcilar: 'Bağcılar',
    dist_bahcelievler: 'Bahçelievler', dist_bakirkoy: 'Bakırköy', dist_basaksehir: 'Başakşehir', dist_bayrampasa: 'Bayrampaşa', dist_besiktas: 'Beşiktaş',
    dist_beykoz: 'Beykoz', dist_beylikduzu: 'Beylikdüzü', dist_beyoglu: 'Beyoğlu', dist_buyukcekmece: 'Büyükçekmece', dist_catalca: 'Çatalca',
    dist_cekmekoy: 'Çekmeköy', dist_esenler: 'Esenler', dist_esenyurt: 'Esenyurt', dist_eyupsultan: 'Eyüpsultan', dist_fatih: 'Fatih',
    dist_gaziosmanpasa: 'Gaziosmanpaşa', dist_gungoren: 'Güngören', dist_kadikoy: 'Kadıköy', dist_kagithane: 'Kağıthane', dist_kartal: 'Kartal',
    dist_kucukcekmece: 'Küçükçekmece', dist_maltepe: 'Maltepe', dist_pendik: 'Pendik', dist_sancaktepe: 'Sancaktepe', dist_sariyer: 'Sarıyer',
    dist_sile: 'Şile', dist_silivri: 'Silivri', dist_sisli: 'Şişli', dist_sultanbeyli: 'Sultanbeyli', dist_sultangazi: 'Sultangazi',
    dist_tuzla: 'Tuzla', dist_umraniye: 'Ümraniye', dist_uskudar: 'Üsküdar', dist_zeytinburnu: 'Zeytinburnu',
    biz_restaurant: 'Restoran', biz_cafe: 'Kafe', biz_retail: 'Perakende Mağaza', biz_office: 'Ofis', biz_pharmacy: 'Eczane',
    biz_bakery: 'Fırın', biz_barber: 'Berber', biz_gym: 'Spor Salonu', biz_shop: 'Dükkan', biz_store: 'Mağaza', biz_company: 'Şirket',
    biz_clothing: 'Giyim Mağazası', biz_hotel: 'Otel', biz_clinic: 'Klinik', biz_school: 'Okul',
    settings_title: 'Ayarlar',
    settings_appearance: 'Görünüm',
    settings_profile: 'Profil',
    settings_history: 'Sohbet Geçmişi',
    settings_security_title: 'Güvenlik ve Gizlilik',
    settings_theme: 'Tema',
    settings_lang: 'Dil',
    settings_2fa_title: 'İki Faktörlü Doğrulama',
    settings_2fa_desc: 'Hesabınıza ekstra bir güvenlik katmanı ekleyin.',
    settings_2fa_enable: '2FA\'yı Etkinleştir',
    settings_sessions_title: 'Aktif Oturumlar',
    settings_sessions_desc: 'Diğer aktif oturumları yönetin ve çıkış yapın.',
    settings_sessions_logout: 'Diğer oturumlardan çıkış yap',
    settings_danger_zone: 'Tehlikeli Bölge',
    settings_delete_desc: 'Hesabınızı sildiğinizde geri dönüş yoktur. Lütfen emin olun.',
    settings_delete_account: 'Hesabı Sil',
    settings_delete_confirm: 'HESAP SİLMEYİ ONAYLAMAK İÇİN "SİL" YAZIN',
    settings_delete_yes: 'Evet, hesabımı sil',
    settings_confirm_clear: 'Evet, geçmişi temizle',
    settings_cancel: 'İptal',
    settings_clear_history: 'Geçmişi Temizle',
    scroll_right: 'Sağa Kaydır',
    click_to_flip: 'Görmek için dokun',
  },
  ar: {
    navbar_home: 'الرئيسية',
    navbar_chat: 'TurkGateway AI',
    navbar_dashboard: 'Dashboard',
    navbar_get_started: 'ابدأ الآن',
    home_hero_title: 'منصة الذكاء الاصطناعي للأعمال والقانون والتعليم في تركيا.',
    home_hero_subtitle: 'تنقل بين التصاريح والبروتوكولات القانونية والتسجيل الجامعي بسهولة. يقوم وكلاؤنا المتخصصون بإنشاء خارطة طريق مخصصة لك في ثوانٍ.',
    home_hero_greeting_user: 'أهلاً حمزة',
    home_hero_question: 'من أين نبدأ؟',
    home_hero_cta: 'ابدأ الآن',
    hero_cat_upload: 'رفع المستندات',
    hero_cat_status: 'تحقق من الحالة',
    hero_cat_protocols: 'بروتوكولات البلدية',
    hero_cat_safety: 'دليل السلامة من الحرائق',
    how_it_works_label: 'كيف يعمل',
    process_title: 'عملية الذكاء الاصطناعي',
    process_subtitle: 'دع وكلاء الذكاء الاصطناعي لدينا يتولون المهام الصعبة نيابة عنك.',
    process_step1_title: 'صف حالتك',
    process_step1_desc: 'أخبرنا عن عملك أو مشكلتك القانونية أو أهدافك الجامعية بلغة بسيطة. يفهم الذكاء الاصطناعي اللوائح والمتطلبات المحلية على الفور.',
    process_step2_title: 'التحليل',
    process_step2_desc: 'يقوم وكلاؤنا المتخصصون بمراجعة بروتوكولات البلدية والقوانين والمبادئ التوجيهية الأكاديمية لبناء خارطة طريقك الدقيقة.',
    process_step3_title: 'التنفيذ',
    process_step3_desc: 'نحن نخطط لكل خطوة—من ملفات e-Devlet وتجديد الهوية إلى التسجيل الجامعي—لتتمكن من التركيز على أهدافك دون صداع بيروقراطي.',
    dashboard_title: 'لوحة التحكم',
    dashboard_sync: 'مزامنة',
    dashboard_ask_ai: 'اسأل الذكاء الاصطناعي',
    dashboard_upload: 'رفع المستندات',
    chat_placeholder: 'اسأل وكلاء TurkGateway AI...',
    chat_new: 'دردشة جديدة',
    chat_greeting: 'أهلاً بك.',
    chat_subtitle: 'كيف يمكنني مساعدتك في تصاريح إسطنبول اليوم؟',
    chat_q1: 'ما هي التصاريح التي أحتاجها لمطعم في إسطنبول؟',
    chat_q2: 'كم يستغرق فحص السلامة من الحرائق؟',
    chat_q3: 'ما هي المستندات التي تطلبها البلدية؟',
    chat_q4: 'ما هي تكلفة شهادة السلامة من الحرائق؟',
    dashboard_updated: 'تم التحديث',
    dashboard_live_session: 'جلسة مباشرة',
    dashboard_days: 'أيام',
    dashboard_active: 'نشط',
    dashboard_running: 'يعمل',
    dashboard_agent_status: 'الوكيل يعالج سير العمل',
    dashboard_ask_ai_step: 'اسأل الذكاء الاصطناعي عن هذه الخطوة',
    dashboard_no_session: 'لا توجد جلسة نشطة',
    dashboard_processing: 'جاري المعالجة...',
    loading_preparing: 'جاري تحضير مساحة العمل...',
    loading_verifying: 'التحقق من البيانات عبر e-Devlet...',
    loading_analyzing: 'تحليل بروتوكولات البلدية...',
    loading_building: 'بناء خارطة الطريق المخصصة...',
    loading_finalizing: 'إنهاء عملية المزامنة...',
    dashboard_compliance_score: 'درجة الامتثال',
    dashboard_steps_complete: 'الخطوات المكتملة',
    dashboard_est_days: 'الأيام المتبقية المتوقعة',
    dashboard_active_agents: 'وكلاء الذكاء الاصطناعي النشطون',
    dashboard_overall_progress: 'التقدم العام',
    dashboard_workflow_steps: 'خطوات سير العمل',
    dashboard_action_required: 'إجراء مطلوب',
    dashboard_all_clear: 'كل شيء جاهز',
    dashboard_action_required_desc: 'يرجى إكمال خطوة {step} للمتابعة.',
    dashboard_bot_processing: 'يقوم النظام حاليًا بمعالجة مهام الوكيل.',
    dashboard_whats_next: 'ماذا بعد؟',
    dashboard_next_step_desc: 'بمجرد الموافقة على مستنداتك الأولية، سيتم تفعيل رخصة فتح وممارسة العمل (İşyeri Açma ve Çalışma Ruhsatı) الخاصة بك.',
    dashboard_init_title: 'بدء سير العمل',
    dashboard_init_summary: 'ابدأ دردشة لإنشاء خطة التصريح الخاصة بك.',
    dashboard_init_detail: 'بمجرد وصف عملك في الدردشة ، سيقوم الذكاء الاصطناعي بإنشاء مسار تصريح مخصص لك هنا.',
    dashboard_mark_complete: 'تحديد كمكتمل',
    dashboard_mark_done: 'حدد الخطوة كمكتملة',
    dashboard_syncing: 'جاري المزامنة مع البلدية المحلية...',
    dashboard_toast_success: 'تم رفع المستند بنجاح!',
    status_completed: 'مكتمل',
    status_in_progress: 'قيد التنفيذ',
    status_pending: 'قيد الانتظار',
    dashboard_auto_execute: 'تشغيل البوت تلقائياً',
    chat_welcome: 'أهلاً {name}',
    chat_begin: 'من أين نبدأ؟',
    chat_placeholder_alt: 'اسأل مساعد التصاريح الخاص بك...',
    chat_suggestion_business: 'أريد فتح مشروع تجاري',
    chat_suggestion_permit: 'أريد الحصول على تصريح',
    chat_suggestion_location: 'موقع عملي',
    chat_suggestion_duration: 'كم من الوقت يستغرق؟',
    chat_suggestion_cost: 'كم يكلف؟',
    chat_suggestion_obtain: 'أريد الحصول على تصريح عمل',
    chat_suggestion_steps: 'أريد معرفة الخطوات',
    chat_suggestion_docs: 'ما هي الوثائق التي أحتاجها؟',
    chat_suggestion_help: 'كيف يعمل؟',
    sidebar_new_chat: 'دردشة جديدة',
    sidebar_recent: 'الأخيرة',
    sidebar_help: 'المساعدة',
    sidebar_activity: 'النشاط',
    sidebar_settings: 'الإعدادات',
    navbar_pricing: 'التسعير',
    sidebar_upgrade: 'ترقية',
    sidebar_home: 'الرئيسية',
    sidebar_dashboard: 'Dashboard',
    sidebar_my_stuff: 'أشيائي',
    sidebar_gems: 'الجواهر',
    sidebar_logout: 'تسجيل الخروج',
    navbar_logout: 'تسجيل الخروج',
    navbar_login: 'تسجيل الدخول',
    navbar_signup: 'إنشاء حساب',
    navbar_subscribers: 'المشتركين',
    dashboard_no_permits: 'لم يتم العثور على تصاريح نشطة',
    sidebar_switch_assistant: 'تبديل المساعد',
    sidebar_sign_in_prompt: 'سجل الدخول لبدء حفظ دردشاتك',
    sidebar_sign_in_desc: 'بمجرد تسجيل الدخول، يمكنك الوصول إلى دردشاتك الأخيرة هنا.',

    help_title: 'مركز المساعدة',
    help_faq: 'الأسئلة الشائعة',
    help_contact: 'الاتصال بالدعم',
    help_docs: 'الوثائق',
    help_feedback: 'إرسال ملاحظات',
    help_search: 'البحث عن مساعدة...',
    home_stat_districts: 'منطقة مشمولة',
    home_stat_types: 'نوع تصريح',
    home_stat_time: 'توفير الوقت',
    home_stat_success: 'معدل النجاح',
    home_feature_agents: 'ذكاء اصطناعي متعدد الوكلاء',
    home_feature_agents_desc: 'يعمل وكلاء LangGraph على التخطيط والتصنيف والتحقق من الامتثال بالتوازي.',
    home_feature_districts: 'جميع المناطق الـ 39',
    home_feature_districts_desc: 'تغطية كاملة لإسطنبول — دعم جميع البلديات الـ 39 مع بروتوكولات محلية متميزة.',
    home_feature_tracking: 'تتبع في الوقت الحقيقي',
    home_feature_tracking_desc: 'تتم متابعة كل خطوة من خطوات طلب التصريح الخاص بك. لا شيء يغيب عن الحسبان.',
    home_step1_title: 'أخبرنا عن عملك',
    home_step1_desc: 'أجب عن بضعة أسئلة حول نوع عملك وموقعه ونطاقه.',
    home_step2_title: 'الذكاء الاصطناعي يرسم مسار التصريح',
    home_step2_desc: 'يحدد نظام الوكلاء لدينا كل تصريح ومستند مطلوب لحالتك.',
    home_step3_title: 'رفع المستندات',
    home_step3_desc: 'نقوم بإرشادك عبر كل مستند مطلوب مع قوائم مراجعة ونماذج.',
    home_step4_title: 'استلم موافقتك',
    home_step4_desc: 'تتبع كل موافقة في الوقت الحقيقي. جداول زمنية تقديرية لكل بلدية.',
    dashboard_toast_success_payment: 'تم تفعيل الاشتراك! أهلاً بك في المميز.',
    dashboard_toast_error_payment: 'فشلت عملية الدفع. يرجى المحاولة مرة أخرى.',
    dashboard_toast_error_sub: 'فشل بدء الاشتراك',
    assistant_permit: 'تصريح',
    assistant_student: 'طالب',
    assistant_lawyer: 'محامي',
    chat_switch_assistant: 'تبديل المساعد',
    chat_permit_desc: 'بروتوكول الأعمال والبلدية',
    chat_student_desc: 'المهام الأكاديمية وتجديد الهوية',
    chat_lawyer_desc: 'المشورة القانونية والامتثال',
    chat_sug_renew: 'تجديد الهوية',
    chat_sug_uni: 'أفضل الجامعات',
    chat_sug_roadmap: 'خارطة طريق التسجيل',
    chat_sug_deadlines: 'المواعيد النهائية',
    chat_sug_visas: 'تأشيرات الطلاب',
    chat_sug_shelp: 'مساعدة الطلاب',
    chat_sug_contract: 'مراجعة العقود',
    chat_sug_formation: 'تأسيس الشركات',
    chat_sug_employ: 'قانون العمل',
    chat_sug_times: 'الجداول الزمنية القانونية',
    chat_sug_resid: 'الإقامة/التصريح',
    chat_sug_dispute: 'النزاعات القانونية',
    pricing_title: 'تسعير بسيط وشفاف',
    pricing_subtitle: 'ابدأ مجانًا. قم بالترقية عندما تحتاج إلى أتمتة الامتثال التي تتوسع.',
    pricing_monthly: 'شهرياً',
    pricing_annual: 'سنوياً',
    pricing_save: 'وفر {amount}/سنة',
    pricing_free_desc: 'للأفراد الذين يستكشفون متطلبات التصاريح. لا يلزم وجود بطاقة ائتمان.',
    pricing_premium_desc: 'قدرات كاملة للشركات التي تدير الامتثال على نطاق واسع في إسطنبول.',
    pricing_current: 'الخطة الحالية',
    pricing_upgrade: 'الترقية إلى المميز',
    pricing_most_popular: 'الأكثر شعبية',
    pricing_compare: 'قارن الخطط',
    pricing_compare_subtitle: 'كل ما تحتاجه لاتخاذ القرار الصحيح.',
    pricing_faq_title: 'الأسئلة الشائعة',
    pricing_faq_subtitle: 'هل لديك سؤال غير مدرج هنا؟',
    pricing_contact_us: 'اتصل بنا',
    pricing_cta_title: 'جاهز لتبسيط امتثالك؟',
    pricing_cta_subtitle: 'انضم إلى الشركات في جميع أنحاء إسطنبول التي تستخدم TurkGateway لأتمتة سير عملها التنظيمي.',
    pricing_secure_checkout: 'دفع آمن عبر iyzico',
    pricing_cancel_anytime: 'إلغاء في أي وقت',
    pricing_vat_included: 'فاتورة ضريبة القيمة المضافة متضمنة',
    auth_login_title: 'تسجيل الدخول',
    auth_login_subtitle: 'مرحبًا بعودتك! يرجى إدخال بياناتك.',
    auth_email: 'البريد الإلكتروني',
    auth_password: 'كلمة المرور',
    auth_no_account: 'ليس لديك حساب؟',
    auth_has_account: 'لديك حساب بالفعل؟',
    auth_signup_title: 'إنشاء حساب',
    auth_signup_subtitle: 'ابدأ رحلتك مع TurkGateway اليوم.',
    auth_full_name: 'الاسم الكامل',
    auth_signing_in: 'جاري تسجيل الدخول...',
    auth_signing_up: 'جاري إنشاء الحساب...',
    pricing_billed_as: 'يتم احتساب الفاتورة بقيمة {amount}/سنوياً',
    pricing_billed_monthly: 'يتم احتساب الفاتورة شهرياً',
    pricing_monthly_unit: 'شهر',
    pricing_feat_label: 'الميزة',
    connect_in: 'في',
    agent_name: 'TurkGateway مستشار الذكاء الاصطناعي',
    agent_thinking: 'الوكيل يفكر الآن...',
    footer_version: 'محرك بروتوكول البلدية • v2.5',
    dist_adalar: 'الأميرات', dist_arnavutkoy: 'أرناووط كوي', dist_atasehir: 'أتاشهير', dist_avcilar: 'أفجيلار', dist_bagcilar: 'باغجيلار',
    dist_bahcelievler: 'باهتشيلي ايفلر', dist_bakirkoy: 'بكر كوي', dist_basaksehir: 'باشاك شهير', dist_bayrampasa: 'بايرام باشا', dist_besiktas: 'بشكتاش',
    dist_beykoz: 'بيكوز', dist_beylikduzu: 'بيليك دوزو', dist_beyoglu: 'بيوغلو', dist_buyukcekmece: 'بيوك تشكمجه', dist_catalca: 'شاتالجا',
    dist_cekmekoy: 'تشكمه كوي', dist_esenler: 'إيسنلار', dist_esenyurt: 'إيسنيورت', dist_eyupsultan: 'أيوب سلطان', dist_fatih: 'الفاتح',
    dist_gaziosmanpasa: 'غازي عثمان باشا', dist_gungoren: 'غونغوران', dist_kadikoy: 'كاديكوي', dist_kagithane: 'كاغيت هانة', dist_kartal: 'كارتال',
    dist_kucukcekmece: 'كوتشوك تشكمجه', dist_maltepe: 'مالتيبي', dist_pendik: 'بنديك', dist_sancaktepe: 'سانجاك تبي', dist_sariyer: 'ساريير',
    dist_sile: 'شيلا', dist_silivri: 'سيليفري', dist_sisli: 'شيشلي', dist_sultanbeyli: 'سلطان بيلي', dist_sultangazi: 'سلطان غازي',
    dist_tuzla: 'توزلا', dist_umraniye: 'عمرانية', dist_uskudar: 'أوسكودار', dist_zeytinburnu: 'زيتين بورنو',
    biz_restaurant: 'مطعم', biz_cafe: 'مقهى', biz_retail: 'متجر تجزئة', biz_office: 'مكتب', biz_pharmacy: 'صيدلية',
    biz_bakery: 'مخبز', biz_barber: 'صالون حلاقة', biz_gym: 'صالة رياضية', biz_shop: 'متجر', biz_store: 'محل', biz_company: 'شركة',
    biz_clothing: 'متجر ملابس', biz_hotel: 'فندق', biz_clinic: 'عيادة', biz_school: 'مدرسة',
    settings_title: 'الإعدادات',
    settings_appearance: 'المظهر',
    settings_profile: 'الملف الشخصي',
    settings_history: 'سجل الدردشة',
    settings_security_title: 'الأمن والخصوصية',
    settings_theme: 'السمة',
    settings_lang: 'اللغة',
    settings_2fa_title: 'المصادقة الثنائية',
    settings_2fa_desc: 'أضف طبقة أمان إضافية لحسابك.',
    settings_2fa_enable: 'تفعيل المصادقة الثنائية',
    settings_sessions_title: 'الجلسات النشطة',
    settings_sessions_desc: 'إدارة وتسجيل الخروج من الجلسات النشطة الأخرى.',
    settings_sessions_logout: 'تسجيل الخروج من الجلسات الأخرى',
    settings_danger_zone: 'منطقة الخطر',
    settings_delete_desc: 'بمجرد حذف حسابك، لن تتمكن من التراجع. يرجى التأكد.',
    settings_delete_account: 'حذف الحساب',
    settings_delete_confirm: 'اكتب "حذف" لتأكيد إزالة الحساب',
    settings_delete_yes: 'نعم، احذف حسابي',
    settings_confirm_clear: 'نعم، امسح السجل',
    settings_cancel: 'إلغاء',
    settings_clear_history: 'مسح السجل',
    scroll_right: 'مرر لليمين',
    click_to_flip: 'انقر للكشف',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'ar', 'tr'].includes(saved)) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  const translateHistory = (content: string) => {
    const original = content;
    const entries = Object.entries(translations.en);
    const matchingKey = entries.find(([k, v]) => v === original)?.[0];
    if (matchingKey) return t(matchingKey);
    return original;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, translateHistory }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
