export const runtime = 'nodejs';

import { db } from '@/lib/db';
import { applicationDocuments, applications } from '@/lib/schema';
import { eq } from 'drizzle-orm';
import { requireUser } from '@/lib/user-helper';

/**
 * GET /api/documents/[id] — download a document generated by an agent
 * (deliver_form). Owner-only: the row is joined to its application and served
 * only to the user the application belongs to. A purged or foreign row
 * answers 404 so the id space leaks nothing.
 */
export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await requireUser(req);
    const { id } = await params;
    const docId = Number(id);
    if (!Number.isInteger(docId) || docId <= 0) {
      return Response.json({ detail: 'Not found' }, { status: 404 });
    }

    const rows = await db
      .select({
        id: applicationDocuments.id,
        filename: applicationDocuments.filename,
        mime_type: applicationDocuments.mime_type,
        data: applicationDocuments.data,
        owner_id: applications.user_id,
      })
      .from(applicationDocuments)
      .innerJoin(applications, eq(applicationDocuments.application_id, applications.id))
      .where(eq(applicationDocuments.id, docId))
      .limit(1);

    const doc = rows[0];
    if (!doc || doc.owner_id !== user.id) {
      return Response.json({ detail: 'Not found' }, { status: 404 });
    }

    const bytes = Buffer.isBuffer(doc.data) ? doc.data : Buffer.from(doc.data as string);
    const safeName = String(doc.filename || 'document.pdf').replace(/[^\w.\- ]/g, '_');

    return new Response(new Uint8Array(bytes), {
      headers: {
        'Content-Type': doc.mime_type || 'application/pdf',
        'Content-Disposition': `attachment; filename="${safeName}"`,
        'Cache-Control': 'private, no-store',
      },
    });
  } catch (e: any) {
    if (e instanceof Response) return e;
    console.error('[api/documents]', e);
    return Response.json({ detail: 'Error' }, { status: 500 });
  }
}
